### ISSUE TITLE
[BUG] `get_estimator_results` does not return results for different estimator casing

### ISSUE THREAD

**Issue by MatthewMiddlehurst** [aeon-toolkit/aeon#1007]
### Describe the bug

`["kmeans-dtw", "kmedoids-dtw", "kmedoids-msm"]` is a valid input, while `["KMeans-DTW", "KMedoids-DTW", "KMedoids-MSM"]` is not. This may be the case for datasets as well, but I have not checked.

### Steps/Code to reproduce the bug

```python
datasets = ["ArrowHead", "GunPoint", "ItalyPowerDemand", "Chinatown", "BeetleFly"]
benchmarks = ["KMeans-DTW", "KMedoids-DTW", "KMedoids-MSM"]
res = get_estimator_results(
    datasets=datasets,
    estimators=benchmarks,
    task="clustering",
    type="accuracy",
)
```

### Expected results

Results are returned regardless of case.

### Actual results

```python-traceback
ValueError: Unknown estimator name KMeans-DTW
```

**Comment by TonyBagnall** [comment]
so the classifier names are case sensitive, not simply a case of to lower. I can alias them, but we could move to all lower case?

**Comment by TonyBagnall** [comment]
![image](https://github.com/aeon-toolkit/aeon/assets/9594042/bb1520b3-df3b-47bb-8517-528c7bf87fbe)

**Comment by TonyBagnall** [comment]
dataset names are also case sensitive, but I dont mind that

**Comment by TonyBagnall** [comment]
names of files on tsc.com

![image](https://github.com/aeon-toolkit/aeon/assets/9594042/ac30414d-d209-4ca0-aa84-8b33c2dc6c3b)

**Comment by TonyBagnall** [comment]
personally, I dont think we should make names all lower case, given they are acronyms, but just add aliases. But if others think differently, fine be me if someone wants to change all the file names.

**Comment by TonyBagnall** [comment]
I'll close this because aliases for the examples given are now in the mapping and I dont think it is a bug really

    # Clustering
    "dtw-dba": {"DTW-DBA"},
    "kmeans-ed": {"ed-kmeans", "kmeans-euclidean", "k-means-ed", "KMeans-ED"},
    "kmeans-dtw": {"dtw-kmeans", "k-means-dtw", "KMeans-DTW"},
    "kmeans-msm": {"msm-kmeans", "k-means-msm", "KMeans-MSM"},
    "kmeans-twe": {"twe-kmeans", "k-means-twe", "KMeans-TWE"},
