### ISSUE TITLE
[BUG] HouseholdPowerConsumption1 incosistent number of dimensions when used with "load_regression()"

### ISSUE THREAD

**Issue by andregdmitri** [aeon-toolkit/aeon#1011]
### Describe the bug

The dataset "HouseholdPowerConsumption1" from aeon.datasets.tser_data_lists doesn't load with load_regression() from aeon.datasets._data_loaders. All the other datasets on this list were loaded without issues.

### Steps/Code to reproduce the bug

```
dataset = "HouseholdPowerConsumption1"
X, y = load_regression(dataset)
```

### Expected results

The X and y to be correctly loaded

### Actual results

```
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
Cell In[21], line 2
      1 dataset = "HouseholdPowerConsumption1"
----> 2 load_regression(dataset)

File ~/anaconda3/lib/python3.11/site-packages/aeon/datasets/_data_loaders.py:1093, in load_regression(name, split, extract_path, return_metadata)
   1086             raise ValueError(
   1087                 f"Invalid dataset name ={name} one or both of TRAIN and TEST is "
   1088                 f"not available on path ={local_module}/{local_dirname}/{name}.\n "
   1089                 f"Nor is it available on tseregression.org via path {url_train} "
   1090                 f"or {url_test}"
   1091             )
   1092 #            zipfile.ZipFile(file_save, "r").extractall(f"{extract_path}/{name}/")
-> 1093 return _load_saved_dataset(
   1094     name=name,
   1095     split=split,
   1096     local_module=local_module,
   1097     local_dirname=local_dirname,
   1098     return_meta=return_metadata,
   1099 )

File ~/anaconda3/lib/python3.11/site-packages/aeon/datasets/_data_loaders.py:334, in _load_saved_dataset(name, split, return_X_y, return_type, local_module, local_dirname, return_meta)
    332 fname = name + "_TEST.ts"
    333 abspath = os.path.join(local_module, local_dirname, name, fname)
--> 334 X_test, y_test, meta_data_test = load_from_tsfile(
    335     abspath, return_meta_data=True
    336 )
    337 if meta_data["equallength"]:
    338     X = np.concatenate([X_train, X_test])

File ~/anaconda3/lib/python3.11/site-packages/aeon/datasets/_data_loaders.py:259, in load_from_tsfile(full_file_path_and_name, replace_missing_vals_with, return_meta_data, return_type)
    257     meta_data = _load_header_info(file)
    258     # load into list of numpy
--> 259     data, y, meta_data = _load_data(file, meta_data)
    261 # if equal load to 3D numpy
    262 if meta_data["equallength"]:

File ~/anaconda3/lib/python3.11/site-packages/aeon/datasets/_data_loaders.py:174, in _load_data(file, meta_data, replace_missing_vals_with)
    172 else:
    173     if current_channels != n_channels:
--> 174         raise IOError(
    175             f"Inconsistent number of dimensions in case {n_cases}. "
    176             f"Expecting {n_channels} but have read {current_channels}"
    177         )
    178     if meta_data["univariate"]:
    179         if current_channels > 1:

OSError: Inconsistent number of dimensions in case 174. Expecting 5 but have read 1
```

### Versions

<details>
System:
    python: 3.11.5 (main, Sep 11 2023, 13:54:46) [GCC 11.2.0]
executable: /home/andre/anaconda3/bin/python
   machine: Linux-6.5.0-14-generic-x86_64-with-glibc2.38

Python dependencies:
          pip: 23.2.1
   setuptools: 68.0.0
 scikit-learn: 1.2.2
         aeon: 0.6.0
  statsmodels: 0.14.0
        numpy: 1.24.3
        scipy: 1.11.3
       pandas: 2.0.3
   matplotlib: 3.8.0
       joblib: 1.2.0
        numba: 0.58.0
     pmdarima: 2.0.4
      tsfresh: 0.20.1
</details>

**Comment by TonyBagnall** [comment]
hi @andregdmitri actually looking at these data now, in the process of added 40 odd new regression problems. I'll take a look. iirc household had time stamps, which I thought I had sorted

**Comment by TonyBagnall** [comment]
this works for me, I suggest 

```python
from aeon.datasets import load_regression

dataset = "HouseholdPowerConsumption1"
X, y = load_regression(dataset)
print("Shape of X = ",X.shape)
```
Shape of X =  (1431, 5, 1440)

you probably need to update aeon version, latest is 0.6. Alternatively, you can download it from here

https://timeseriesclassification.com/aeon-toolkit/HouseholdPowerConsumption1.zip

this contains the version we use with imputed missing values (HouseholdPowerConsumption1_nmv)

**Comment by TonyBagnall** [comment]
I just put that there now, Im in the process of adding 63 regression problems to tsc.com, including monash ones

**Comment by andregdmitri** [comment]
Hi, thanks for the reply. I was using the latest version (0.6) , as shown in the Versions -> Details tab, I also tried using `pip install --force-reinstall git+https://github.com/aeon-toolkit/aeon.git ` and installing with all_extras.
I had no problems loading the data from the zip you posted with `load_from_tsfile`, but trying to use `load_regression` copying the code cell above still doesn't work for me.

**Comment by TonyBagnall** [comment]
weird, I cant recreate it and cant think what dependencies would cause it to fail, not sure what to suggest

**Comment by andregdmitri** [comment]
fair enough, thanks for the help anyway

**Comment by andregdmitri** [comment]
fair enough, thanks for the help anyway

**Comment by MatthewMiddlehurst** [comment]
Hi, also gave this a go. Had no issue loading the dataset (at least no error using your example), but was on a Windows machine. Not sure if that would make a difference though.
