### ISSUE TITLE
[BUG] Cant import classifiers from aeon.classification

### ISSUE THREAD

**Issue by louis288** [aeon-toolkit/aeon#1019]
### Describe the bug

Cant import classifiers from aeon.classification

### Steps/Code to reproduce the bug

from aeon.classification.distance_based import KNeighborsTimeSeriesClassifier

### Expected results

Program should end after running for a period of time.

### Actual results

The program is constantly running and cannot be ended.

### Versions

System:
    python: 3.11.7 | packaged by conda-forge | (main, Dec 23 2023, 14:27:59) [MSC v.1937 64 bit (AMD64)]
executable: D:\Apps\Anaconda3\envs\aeon-env\python.exe
   machine: Windows-10-10.0.22000-SP0

Python dependencies:
          pip: 23.3.2
   setuptools: 68.2.2
 scikit-learn: 1.3.2
         aeon: 0.6.0
  statsmodels: None
        numpy: 1.26.2
        scipy: 1.11.4
       pandas: 2.0.3
   matplotlib: 3.8.2
       joblib: 1.3.2
        numba: 0.58.1
     pmdarima: None
      tsfresh: None

**Comment by baraline** [comment]
Hi @louis288, thanks for raising an issue. Did you install aeon from PyPI or from source on GitHub ?

I cannot reproduce your issue using the following (Win 11 AMD64):
```bash
conda update conda
conda config --add channels conda-forge
conda create --name aeon_test python=3.11.7
conda activate aeon_test
pip install aeon
python
```
```python
from aeon.classification.distance_based import KNeighborsTimeSeriesClassifier
```

There is indeed some loading time the first time you import things from aeon (probably due to some numba compilation in the background ? Maybe @MatthewMiddlehurst would know better than me)
Could you try to obtain some more detail about where the program seems stuck ?

**Comment by louis288** [comment]
@baraline Thank you very much for your response! I have identified the issue: the aeon.classification module can only be imported with **administrator privileges**. However, other modules, such as `from aeon.forecasting.trend import TrendForecaster`, can be imported without administrator privileges. I have never encountered this situation before. Do you know how to import all aeon modules without requiring administrator privileges?

**Comment by baraline** [comment]
I am not aware of such issue with aeon. This may be due to the install location of your environnement or OS setting. Could you try to uninstall aeon and reinstall it with pip using the `--user` options ? 

If the issue persist could you please provide the path to the conda env folder in your system ? 

Thanks !

**Comment by MatthewMiddlehurst** [comment]
Strange, I can't think of anything `aeon` specific which would cause this though. Possibly `numba` related as @baraline says. I have never run into a situation like this.

**Comment by louis288** [comment]
> I am not aware of such issue with aeon. This may be due to the install location of your environnement or OS setting. Could you try to uninstall aeon and reinstall it with pip using the `--user` option if you didn't use it the first time ?
> 
> If the issue persist could you please provide the path to the conda env folder in your system ?
> 
> Thanks !

@baraline Thank you for your advice! I figured out that the root cause of the aforementioned issue (inability to import certain aeon modules without administrator privileges) was that I had previously created a **shared** conda virtual environment with administrator privileges (environment path: `D:\Apps\Anaconda3\envs\'env_name'`). However, when I create a new **private** conda virtual environment without administrator privileges (environment path: `C:\Users\'user_name'\.conda\envs\'env_name'`), it is able to import aeon modules successfully.

Currently, this approach temporarily meets my needs. However, it would be better if the bug could be fixed in the future, allowing the shared conda virtual environment to run the code without any issues (enabling multiple accounts on the same device to use the same shared conda environment).

Finally, I sincerely appreciate your outstanding contributions. @baraline @MatthewMiddlehurst

**Comment by baraline** [comment]
Glad you could solve it !Tthe problem is most likely that numba is trying to compile aeon functions for more efficient execution, and is unable to write the compiled functions to disk for later usage. (See: [numba caching documentation](https://numba.readthedocs.io/en/stable/developer/caching.html) for more details on this.)

This might occur if any package using numba was installed by an administrator or super-user, and ordinary users may not have permission to write files in the same folder.

There are two ways to address this issue:
- Install the package as the same user who will be executing code 
- Change the NUMBA_CACHE_DIR environment variable to a folder which the user does have write permissions to. See [numba environment variables](https://numba.readthedocs.io/en/stable/reference/envvars.html#numba-envvars-caching) for details.

Others may confirm but I don't think this Is something we can fix within aeon.

**Comment by louis288** [comment]
I completely understand now. I genuinely appreciate your patient and detailed explanation!
