### ISSUE TITLE
[ENH] Scatter plots

### ISSUE THREAD

**Issue by TonyBagnall** [aeon-toolkit/aeon#1030]
### Describe the feature or idea you want to propose

the new scatter plots are great
![image](https://github.com/aeon-toolkit/aeon/assets/9594042/4c742648-a2d1-40e8-98e0-12c8ca8908d5)
we were just talking about them and thought it might be good if the dotted line represented the median not the mean, so we can show half above the line half below it. What do you think @dguijo ?

### Describe your proposed solution

change dotted line to show median not mean

**Comment by dguijo** [comment]
Hello, Tony! 

Sure, I can change it. 

I have one question. The values that are shown in the X and Y axis are the average of the approaches being compared. Do you want to change that value to the median instead of the average?

**Comment by TonyBagnall** [comment]
I think keep the averages there as numbers and median as visual? Not sure really, just a thought
