### ISSUE TITLE
[ENH] Implement accuracy performance measure for clustering

### ISSUE THREAD

**Issue by TonyBagnall** [aeon-toolkit/aeon#1037]
### Describe the feature or idea you want to propose

there is no sklearn clustering accuracy performance measure, and we use it in comparing clusterers. Be good to have one in aeon

### Describe your proposed solution

new module in performance_metrics called clustering, with a function that returns the clustering accuracy found through permuting possible alignments

**Comment by TonyBagnall** [comment]
see #1048

**Comment by MatthewMiddlehurst** [comment]
I guess solves is not a keyword 🙂.
