### ISSUE TITLE
[ENH] Adding control over the `score` method of estimators

### ISSUE THREAD

**Issue by hadifawaz1999** [aeon-toolkit/aeon#1062]
### Describe the feature or idea you want to propose

For now, the base class of each estimator sector has a scoring technique, for instance its R2 score in base regressor, its open to override in inherited classes. I think its best if we add parameter string to the base class score function, defaulted to R2 for example in regression, accuracy in classification etc. and depending on that argument, the score function calculates a metric.

### Describe your proposed solution

This should be done over all the estimator sectors i.e. classification, regression, forecasting etc. but one by one !

**Comment by aadya940** [comment]
> I think its best if we add parameter string to the base class score function, defaulted to R2 for example in regression, accuracy in classification etc. and depending on that argument, the score function calculates a metric.

So, what are the scoring metrics we are planning to support for classification and regression respectively? @hadifawaz1999

**Comment by itsdivya1309** [comment]
> > I think its best if we add parameter string to the base class score function, defaulted to R2 for example in regression, accuracy in classification etc. and depending on that argument, the score function calculates a metric.
> 
> So, what are the scoring metrics we are planning to support for classification and regression respectively? @hadifawaz1999

For classification it should include the performance measures: accuracy, AUROC, Negative log likelihood (NLL) and balanced accuracy. These are the ones used in Bake off redux.
