### ISSUE TITLE
[DOC] Broken link for the guide on creating pull request 

### ISSUE THREAD

**Issue by andregdmitri** [aeon-toolkit/aeon#1064]
### Describe the issue linked to the documentation

When opening a pull request to AEON, the following description is shown

'''

'''

When you click the link in the description (https://github.com/aeon-toolkit/aeon/blob/main/CONTRIBUTING.md)
This message is shown:

'''
"You can find our contributing guide on our [website](https://www.aeon-toolkit.org/en/latest/get_involved/contributing.html)"
'''

When you go to the website, the page doesn't exist, you get 404 Not Found.

### Suggest a potential alternative/fix

The correct link should be [https://www.aeon-toolkit.org/en/latest/developer_guide.html](https://www.aeon-toolkit.org/en/latest/developer_guide.html)

**Comment by TonyBagnall** [comment]
thanks for that @andregdmitri we will fix it

**Comment by MatthewMiddlehurst** [comment]
Thanks, I have fixed this in #1075.
