### ISSUE TITLE
[MNT] `tensorflow-probability` as a dependency

### ISSUE THREAD

**Issue by MatthewMiddlehurst** [aeon-toolkit/aeon#1077]
### Describe the issue

`tensorflow-probability` as a dependency is currently only used in a single place in the forecasting package, to simulate a normal distribution. This seems rather unnecessary at first glance, and alternatives should be investigated.

### Suggest a potential alternative/fix

Replace the current usage and `tensorflow-probability` as a dependency.

**Comment by TonyBagnall** [comment]
This is I think the only usage in aeon in forecasting base _predict_proba. Basically used to  create a normal distribution object. I cannot find anywhere this is used, so its purely a convenience: I cannot see there is any contract imposed on the pred_dist, but not sure. Needs investigating

```python
        pred_var = self._predict_var(fh=fh, X=X)
        pred_std = np.sqrt(pred_var)
        pred_mean = self.predict(fh=fh, X=X)
        # ensure that pred_mean is a pd.DataFrame
        df_types = ["pd.DataFrame", "pd-multiindex", "pd_multiindex_hier"]
        pred_mean = convert_to(pred_mean, to_type=df_types)
        import tensorflow_probability as tfp
        d = tfp.distributions.Normal
        pred_dist = d(loc=pred_mean, scale=pred_std)
```

**Comment by TonyBagnall** [comment]
the docstring says this

**Comment by TonyBagnall** [comment]
scipy has a normal distribution
```python
from scipy.stats import norm
# Create a normal distribution object
# mean (loc) = 0, standard deviation (scale) = 1
normal_distribution = norm(loc=0, scale=1)
```

**Comment by TonyBagnall** [comment]
so just swapped out this

**Comment by ltsaprounis** [comment]
I agree with this and I'm partially guilty for the tensorflow-probability dependency. The idea was to use it for all distributional forecasting, but in retrospect for the use-cases I've seen, scipy is more practical and of course more lightweight.
