### ISSUE TITLE
[MNT,DOC] Updates to `CODEOWNERS` and file maintenance

### ISSUE THREAD

**Issue by MatthewMiddlehurst** [aeon-toolkit/aeon#1095]
### Describe the issue

We currently have a `CODEOWNERS` file and `__author__`  at the top of individual python files to denote who has worked on and maintains bits of code. However, `CODEOWNERS` has functional limitations based on the listed users write access to the repository and over time (especially with the fork) the `__author__` list has become outdated and unreliable for maintenance.

A while back in Slack I mentioned replacing the `__author__` list at the top of the file with `__maintainer__`, the contents of which can change as needed and is a reliable source for who to contact if necessary regarding a file. I do not really see the loss of the `__author__` list as major, as they can get very bloated and [commit history](https://github.com/aeon-toolkit/aeon/commits/main/aeon/distances/_distance.py) (very easily available through GitHub) is a much better method for tracking contributions.

### Suggest a potential alternative/fix

Replace cases of `__author__`  with blank `__maintainer__` lists and begin to populate these over time.

### Additional context

Currently, the `CODEOWNERS` file has broken entries as a result of its usage as a maintainer tracker. Keeping maintainers listed elsewhere will allow us to fix these and use the file for its intended purpose (sending out review requests for people who want/need them).

**Comment by TonyBagnall** [comment]
I agree I think, would we also get rid of the CODEOWNERS? I would like to do so. I wonder if there is a tool for collating commit history, auto generate class vs contributor record? Just a random thought
