### ISSUE TITLE
[ENH] Classifier _get_train_probs method

### ISSUE THREAD

**Issue by TonyBagnall** [aeon-toolkit/aeon#1102]
### Describe the feature or idea you want to propose

_get_train_probs is implemented in some classifiers and used in meta ensembles such as hive cote. There is a fair amount of repeated code and a class to an out of date converter. It should be standardised

### Describe your proposed solution

I think a base class get_train_probs with conversions and checks, then a default _get_train_probs that does a 10x CV on the train data, which can be overridden by alternatives such as internal bagging

**Comment by MatthewMiddlehurst** [comment]
Resolved in #1107 and subsequent PRs
