### ISSUE TITLE
[BUG] Wrong version threshold for changing name of argument when calling sklearn.preprocessing.OneHotEncoder

### ISSUE THREAD

**Issue by julu98** [aeon-toolkit/aeon#1109]
### Describe the bug

Due to other dependancies I need to use scikit-learn version 1.1.3.

When trying to fit a CNNClassifier, the convert_y_to_keras() method of the BaseDeepClassifier-Class raises a TypeError due to an unexpected keyword argument 'sparse_output' when trying to call sklearn.preprocessing.OneHotEncoder

The method contains this check to determine how to call the OneHotEncoder:

```python
  # Get the installed version of scikit-learn
  installed_version = sklearn.__version__
  # Compare the installed version with the target version
  # categories='auto' to get rid of FutureWarning
  if version.parse(installed_version) < version.parse("1.1"):
      self.onehot_encoder = OneHotEncoder(sparse=False)
  else:
      self.onehot_encoder = OneHotEncoder(sparse_output=False)
  y = self.onehot_encoder.fit_transform(y)
```

Scikit-learn changed the argument name from 'sparse' to 'sparse_output', but this happend with release of version 1.2, not 1.1 as implied in the code (see [release notes of scikit-learn version 1.2](https://scikit-learn.org/stable/whats_new/v1.2.html#changes-1-2)).

After changing the threshold to 1.2, everything works as expected.

### Steps/Code to reproduce the bug

```python
import numpy as np
from aeon.classification.deep_learning import CNNClassifier

X = np.zeros((5,5))  
y = np.array([1.0,0,2.0,1.0,0], dtype=np.float32)

model = CNNClassifier()

model.fit(X, y)
```

### Expected results

Successfully fitting the model to the data

### Actual results

```python-traceback
Traceback (most recent call last):
  File "c:\Users\...", line 10, in <module>
    model.fit(X, y)
  File "C:\Users\user\miniconda3\envs\...\Lib\site-packages\aeon\classification\base.py", line 156, in fit
    self._fit(X, y)
  File "C:\Users\user\miniconda3\envs\...\Lib\site-packages\aeon\classification\deep_learning\_cnn.py", line 236, in _fit
    y_onehot = self.convert_y_to_keras(y)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\miniconda3\envs\...\Lib\site-packages\aeon\classification\deep_learning\base.py", line 151, in convert_y_to_keras
    self.onehot_encoder = OneHotEncoder(sparse_output=False)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: OneHotEncoder.__init__() got an unexpected keyword argument 'sparse_output'
```

### Versions

<details>
System:
    python: 3.11.5 | packaged by Anaconda, Inc. | (main, Sep 11 2023, 13:26:23) [MSC v.1916 64 bit (AMD64)]
executable: C:\Users\user\miniconda3\envs\bugtest\python.exe
   machine: Windows-10-10.0.22631-SP0

Python dependencies:
          pip: 23.3.1
   setuptools: 68.2.2
 scikit-learn: 1.1.3
         aeon: 0.6.0
  statsmodels: 0.14.1
        numpy: 1.23.5
        scipy: 1.12.0
       pandas: 2.0.3
   matplotlib: 3.8.2
       joblib: 1.3.2
        numba: 0.58.1
     pmdarima: None
      tsfresh: None

**Comment by TonyBagnall** [comment]
thanks for that, we will take a look

**Comment by TonyBagnall** [comment]
sorry, I rushed to fix it but then realised I should have asked you for the PR. Would you be willing to put it in? We want to welcome new contributors as much as possible!

**Comment by julu98** [comment]
Sure, I will do it
