### ISSUE TITLE
[BUG] EncoderClassifier produces end of life warning

### ISSUE THREAD

**Issue by TonyBagnall** [aeon-toolkit/aeon#1144]
### Describe the bug

the EncoderClassifier produces this warning
"TFA has entered a minimal maintenance and release mode until a planned end of life in May 2024."

### Steps/Code to reproduce the bug

```python
from aeon.testing.data_generation import make_example_3d_numpy
from aeon.classification.deep_learning._encoder import EncoderClassifier
X, y = make_example_3d_numpy(n_cases=4, n_timepoints=20, n_labels=2, return_y=True)
enc = EncoderClassifier()
```

### Expected results

no warnings

### Actual results
```python-traceback
C:\Code\aeon\venv\lib\site-packages\tensorflow_addons\utils\tfa_eol_msg.py:23: UserWarning: 
TensorFlow Addons (TFA) has ended development and introduction of new features.
TFA has entered a minimal maintenance and release mode until a planned end of life in May 2024.
Please modify downstream libraries to take dependencies from other repositories in our TensorFlow community (e.g. Keras, Keras-CV, and Keras-NLP). 
For more information see: https://github.com/tensorflow/addons/issues/2807 
  warnings.warn(
```

When fitting you get this
```python-traceback
WARNING:root:The given value for groups will be overwritten.
WARNING:root:The given value for groups will be overwritten.
WARNING:root:The given value for groups will be overwritten.
WARNING:root:The given value for groups will be overwritten.
```

**Comment by hadifawaz1999** [comment]
That's a shame they will deprecate the package... Will try to implement the instance normalization myself then :) thanks for putting this up @TonyBagnall  !

**Comment by TonyBagnall** [comment]
pinging this @hadifawaz1999 since it says end of life May 2024

**Comment by hadifawaz1999** [comment]
> pinging this @hadifawaz1999 since it says end of life May 2024

Will take care of it in the next couple of days

**Comment by hadifawaz1999** [comment]
When removing tensorflow addons and no longer have a bound on tensorflow, for some reason the combincation of python 3.12 and MAC OS 13 gets stuck in CI at one test for infinite loop, after seeing the details, it shows that its stucking on some transformation test https://github.com/aeon-toolkit/aeon/actions/runs/9355511121/job/25750819343?pr=1421

**Comment by TonyBagnall** [comment]
only transformer that uses tensorflow is RocketGPU, but this problem predates that I think?

**Comment by hadifawaz1999** [comment]
its meged to main now, but before that it was still happening, so yeah the problem predates it

**Comment by TonyBagnall** [comment]
where are we with this bug? Is it purely the MAcOS?
