### ISSUE TITLE
[ENH] refactor write_to_tsfile to use `n_timepoints` instead of `series_length`

### ISSUE THREAD

**Issue by TonyBagnall** [aeon-toolkit/aeon#1149]
### Describe the feature or idea you want to propose

some time ago we agreed on calling the shape of collections of time series `(n_cases, n_channels, n_timepoints)`. Some classes and functions still use `series_length` instead of `n_timepoints` , which is fine, but we would like to standardise. For example, the function `_write_data_to_tsfile` in `datasets._datawriters` internally used `series_length`

### Describe your proposed solution

refactor this function so that it uses a local variable `n_timepoints` instead of `series_length`

**Comment by Neelaksh-Singh** [comment]
Hi, I would like to take up this issue.

**Comment by TonyBagnall** [comment]
yes its fixed
