### ISSUE TITLE
[ENH] Benchmarking module

### ISSUE THREAD

**Issue by TonyBagnall** [aeon-toolkit/aeon#116]
**Is your feature request related to a problem? Please describe.**
The majority of the benchmarking module has sat there for two or three years with no one maintaining or developing it. The majority of the code is an object model of Task, Strategy, Orchestrator, Evaluator, Datasets, Results. I think we should just remove it all, and adopt a much simpler model for benchmarking that focussing on running experiments, storing results and comparing results to other benchmarks provided. In support

1. The code is not well documented, the doc strings are all one liners
2. The code is disconnected from the rest of the tool kit. Not a bad thing per se, but it indicates no one has used it much
3. There is a lot of testing that involves writing and reading, and these tests sometimes take a while

**Describe the solution you'd like**
I would like to strip out the whole Strategy model and replace it with simple functions, with code to reproduce forecasting, classification, regression and clustering, along the lines started here

https://github.com/sktime/sktime/issues/1123

one of the reasons Ive not got round to this is the weight of all this legacy code. 

**Describe alternatives you've considered**
If someone wants to adopt this module as it is, I'd be happy

**Comment by patrickzib** [comment]
I have not been using it.

IMO: It might be worth to consider removing it and moving the new module to an own repository? This way the documentation could also be improved.

**Comment by TonyBagnall** [comment]
I think I would like some benchmarking code here, not least because it will be a USP, we are quite good at benchmarking after all :) Ultimately, I would like something equivalent to our java MultipleEstimatorEvaluator module, but in a much more functional, interactive way. So given your own set of results, you can pull results of other classifiers off tsc.com, draw CDs, plot results, find different metrics etc. I would also like single problem evaluators to draw AUROC etc.  I think it could make good intern  projects. But I do not want to do it in this design

**Comment by DBCerigo** [comment]
Hi, we (myself and pals) implemented a simple replacement benchmarking module in sktime in late 2022/early 2023. I think benchmarking "results collator" (as per https://github.com/sktime/sktime/issues/1123) would be an apt description of what we were attempting. You can see an example usage/tutorial usage notebook for it [here](https://github.com/datavaluepeople/sktime/blob/kotsu-benchmarking-v2/examples/04_benchmarking_v2.ipynb), and the code for it [here](https://github.com/sktime/sktime/pull/2977/files).

It uses a small package we wrote - [kotsu](https://github.com/datavaluepeople/kotsu) (again 'benchmarking results collator' would be a good description of it) - but we're not necessarily tied to that. 

Back then we also felt that starting afresh (though with the option to cherry pick certain parts of what's already there if we wanted) on the benchmarking module would have been a good thing.  

If the above sounds generally good to you I'd be happy to put some time in contributing on the benchmarking module. Happy to further discuss what we already did, and discuss any different requirements/prioritise for within aeon.

**Comment by TonyBagnall** [comment]
This is fantastic, yes to all of it afaik..Maybe easiest to join our slack and discuss there?
