### ISSUE TITLE
[ENH] Refactor Deep learning classifier/clusterer/regression parameters

### ISSUE THREAD

**Issue by TonyBagnall** [aeon-toolkit/aeon#1168]
### Describe the feature or idea you want to propose

some of the deep learners use variables called `nb_something`, (e.g. `nb_filters`), but our standard notation is `n_something`, e.g.
![image](https://github.com/aeon-toolkit/aeon/assets/9594042/f265d8f8-b1ea-4d83-a832-c7f9fb7dc32a)
  

### Describe your proposed solution

refactor any variables called `nb_something` to be `n_something`, mostly seems to be inception time, in networks, classification and regression (maybe not all in one PR)

**Comment by itsdivya1309** [comment]
Hi! I want to work on this issue.
I have a question though; in the above picture you shared, there are two variables:
`nb_filters` 
`nb_conv_per_layer`
We refactor both of them, right? (Only `nb_filters` is highlighted so I'm a little confused)

**Comment by hadifawaz1999** [comment]
> Hi! I want to work on this issue. I have a question though; in the above picture you shared, there are two variables: `nb_filters` `nb_conv_per_layer` We refactor both of them, right? (Only `nb_filters` is highlighted so I'm a little confused)

Basically all parameters that start with `nb` should become `n`
