### ISSUE TITLE
[ENH] Refactor _TestRegressor in regression testing module to be a MockRegressor in testing/mock_estimators

### ISSUE THREAD

**Issue by TonyBagnall** [aeon-toolkit/aeon#1171]
### Describe the feature or idea you want to propose

we create testing instances of each module to test base class functionality. We recently centralised most of these into testing/mock_estimators (they are called Mock to distinguish from DummyClassifier/Regressor, that make default predictions). The regression module has three testing regressors, _TestRegressor, _TestHandlesAllInput and _DummyHandlesAllInput

### Describe your proposed solution

_DummyHandlesAllInput can be removed, seems to be left over. The other two can be refactored to me in file mock_regressors and named to match the mock classifiers

**Comment by tvilight4** [comment]
@TonyBagnall please do review my PR and suggest the required changes , if any necessary.

**Comment by TonyBagnall** [comment]
closed by #1213 , thanks
