### ISSUE TITLE
[ENH] replace get_train_probs for regressors

### ISSUE THREAD

**Issue by TonyBagnall** [aeon-toolkit/aeon#1178]
### Describe the feature or idea you want to propose

classification has replace `get_train_preds` with `fit_predict`, would be good to do the same with regression (I think its only implemented for FreshPrinceRegressor).

### Describe your proposed solution

redesign regressors for fit_predict

**Comment by MatthewMiddlehurst** [comment]
Hi @AnonymousCodes911, this is currently being resolved in #1200. This implements a method similar to the one in `BaseClassifier`. We don't really want `fit_predict` to just simply call each of the methods, as this is generally undesirable and produces biased results which we don't want to encourage.

**Comment by AnonymousCodes911** [comment]
I see, There was no PR mentioned hence i picked it up!
