### ISSUE TITLE
[DOC] Update shapelet notebook

### ISSUE THREAD

**Issue by TonyBagnall** [aeon-toolkit/aeon#1184]
### Describe the issue linked to the documentation

we have more shapelet based alogorithms and no references on the classification/shapelet_based notebook

**Comment by baraline** [comment]
I wanted to do a notebook about RDST shapelet interpretation (#973), would it be a good fit in this notebook or should this go in a separate one ?

**Comment by TonyBagnall** [comment]
I'd put it in this one, so we can profile them together. I will end each category with a comparison of performance from the redux
