### ISSUE TITLE
[ENH] BaseIntervalForest low coverage

### ISSUE THREAD

**Issue by TonyBagnall** [aeon-toolkit/aeon#1186]
### Describe the feature or idea you want to propose

BaseIntervalForest has only 65% coverage, 190 lines not covered or partial, it would be good to test this class

https://app.codecov.io/gh/aeon-toolkit/aeon/tree/main/aeon%2Fbase%2Festimator%2Finterval_based

### Describe your proposed solution

write test function(s) for uncovered code

**Comment by MatthewMiddlehurst** [comment]
duplicate of #955

**Comment by TonyBagnall** [comment]
lol :)
