### ISSUE TITLE
[MNT] Review `test_sklearn_compatibility.py` tests

### ISSUE THREAD

**Issue by MatthewMiddlehurst** [aeon-toolkit/aeon#1189]
### Describe the issue

I'm not quite sure if some of the tests in `test_sklearn_compatibility.py` make sense currently. I'm fairly certain for the KNN and SVM one using a different set would break it completely at least, as it seems to be just creating a distance matrix and using that to build the estimator.

### Suggest a potential alternative/fix

Review the testing in the file to see if they make sense to keep, expand on them if the functionality is useful.

**Comment by TonyBagnall** [comment]
fixed by #1193 (I think, feel free to reopen @MatthewMiddlehurst )
