### ISSUE TITLE
[DOC] Add comments/basic docstrings to testing functions

### ISSUE THREAD

**Issue by MatthewMiddlehurst** [aeon-toolkit/aeon#1191]
### Describe the issue linked to the documentation

[pydocstyle](https://github.com/pycqa/pydocstyle) is deprecated, the recommended replacement is [ruff](https://github.com/astral-sh/ruff).

A lot of testing functions are currently missing the new `pre-commit` requirements introduced by this change. 

### Suggest a potential alternative/fix

Add comments describing the test functions. These can be basic and do not have to all be done in the same PR. 

See #1055 for current PR swapping the `pre-commit` hook and the failing `pre-commit` action on the PR ([this](https://github.com/aeon-toolkit/aeon/actions/runs/7996469823/job/21838996920?pr=1055#step:6:172) at the time of posting) for functions which require fixing.

**Comment by AnonymousCodes911** [comment]
@MatthewMiddlehurst 
 I ran `ruff` and found some inconsistencies with the  PEP 257 docstring conventions, should i raise a PR while addressing the same?

**Comment by MatthewMiddlehurst** [comment]
That would be great. I already have done some fixes in #1055, I will put them in as a separate PR right now so there is no overlap.

**Comment by AnonymousCodes911** [comment]
sure thing!
