### ISSUE TITLE
[ENH] Adapt `MLPClassifier`, `EncoderClassifier`, `LITETimeClassifier` and `IndividualLITEClassifier` from deep learning classification to regression

### ISSUE THREAD

**Issue by hadifawaz1999** [aeon-toolkit/aeon#1198]
### Describe the feature or idea you want to propose

By comparing `FCNClassifier` in classification/deep_learning and `FCNRegressor` in regression/deep_learning, you can see the only difference is the last layer's task changing from classification to regression, the loss function, and some documentation stuff.

### Describe your proposed solution

It would be good if we do the same for `MLPClassifier` and have `MLPRegressor`.

Same goes for `EncoderClassifier` to have `EncoderRegressor`

So as for `LITETimeClassifier` and `IndividualLITEClassifier` and have regressor versions (for LITE, easier to see how `InceptionTimeClassifier` and `IndividualInceptionClassifier` were adapted for regression)

### Additional context

Done or in-progress:
- [x] #1217 (solved in #1214 )
- [x] #1218 (solved in #1226)
- [x] #1219 (solved in #1221 )
- [x] #1220 (Requires `IndividualLITERegressor`) (solved in #1221)

**Comment by AnonymousCodes911** [comment]
Greetings @hadifawaz1999, 
I was going through the codebase and please advise me if i have to **create** `MLPRegressor` `EncoderRegressor` and so on to mirror their counterpart classes at `classification/deeplearning`. Could you guide me on how to proceed with creating these classes? Additionally, if there are any references or examples that I should follow?
Thank you for your time and consideration

**Comment by AnonymousCodes911** [comment]
@hadifawaz1999, 
I was working towards a basic scaffolding for` _mlp.py(for MLPRegressor)` and `__init__.py` file in regression/deeplearning, but when i tried committing those changes, i was prompted with flake8 error(W292) and even after fixing it, i am unable to make a PR, can you please guide me?
Thankyou

**Comment by hadifawaz1999** [comment]
hello @AnonymousCodes911 thanks for taking care of this. I just saw your comments and seems you were able to do the pull request, so i suppose its all good now ?

For the creation of the classes, the best thing is to really compare how FCNRegressor and FCNClassifier differ from each other, and then do the same thing for MLPClassifier

**Comment by AnonymousCodes911** [comment]
@hadifawaz1999, thank you for the input, yes the errors were resolved. I'll be working towards the next parts
