### ISSUE TITLE
[ENH] Terminology for multivariate classification problems: columns, dimensions or channels?

### ISSUE THREAD

**Issue by TonyBagnall** [aeon-toolkit/aeon#121]
I am rewriting the classification notebook to focus more on numpy arrays. There are some terminology issues to fix. Using basic motions as an example, which has 40 instances, 6 dimensions and series length 100. We store this in an array shape  (n_instances, n_dimensions, n_timepoints),

What do we call axis 1: columns, dimensions or channels? I do not like columns, it makes no sense with numpy 3D arrays. I have in the past mostly used dimensions, but then this creates a confusion with the array dimensions, n_dims. I am leaning to a complete switch to call them channels. I think channels works for basic motions, but it could be weird in some applications though.

Any thoughts?

**Comment by haskarb** [comment]
In our group, we discussed the same a few years back; if I remember correctly, we didn't choose the "dimension" because it confuses people from tabular data. The channel seemed ambiguous, yet better because it could be data from video, image, or sensors, where the term is prevalent.

**Comment by hadifawaz1999** [comment]
I think the term "channels" is the best fit here, especially that in the literature they use "channel" term for multivariate TS.

**Comment by TonyBagnall** [comment]
ok, so channels it is!
