### ISSUE TITLE
[BUG] The registry.all_estimators() function fails if pytest is not installed

### ISSUE THREAD

**Issue by CodeLionX** [aeon-toolkit/aeon#1228]
### Describe the bug

Listing all estimators via the `aeon.registry.all_estimators()`-function raises the below error if `pytest` is not installed. I assume that the function accidentally loads a test module while traversing the aeon source modules.

I also noticed that the first execution takes a considerable amount of time (around one minute), which I find too slow. I cannot reproduce the long runtime in an existing workspace (venv).

### Steps/Code to reproduce the bug

```python
from timeit import Timer
from aeon import registry
from aeon import show_versions

show_versions()

timer = Timer(lambda: registry.all_estimators(estimator_types="clusterer", return_tags=True))
try:
    timer.timeit(100)
    print(f"Executing 'registry.all_estimators()' runtime measurements")
except Exception:
    timer.print_exc()

print(timer)
```

### Expected results

The registry lists all clustering estimators with their tags (probably a list of dictionaries).

### Actual results

```python-traceback
Traceback (most recent call last):
  File "/home/sebastian/Documents/projects/ts-clustering/aeon-registry-bug.py", line 10, in <module>
    timer.timeit(100)
  File "/home/sebastian/.conda/envs/aeon/lib/python3.10/timeit.py", line 178, in timeit
    timing = self.inner(it, self.timer)
  File "<timeit-src>", line 6, in inner
    _stmt()
  File "/home/sebastian/Documents/projects/ts-clustering/aeon-registry-bug.py", line 8, in <lambda>
    timer = Timer(lambda: registry.all_estimators(estimator_types="clusterer", return_tags=True))
  File "/home/sebastian/.conda/envs/aeon/lib/python3.10/site-packages/aeon/registry/_lookup.py", line 249, in all_estimators
    raise e
  File "/home/sebastian/.conda/envs/aeon/lib/python3.10/site-packages/aeon/registry/_lookup.py", line 233, in all_estimators
    module = import_module(module_name)
  File "/home/sebastian/.conda/envs/aeon/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/sebastian/.conda/envs/aeon/lib/python3.10/site-packages/aeon/testing/test_all_estimators.py", line 15, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
```

### Versions

<details>

System:
    python: 3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0]
executable: /home/sebastian/.conda/envs/aeon/bin/python
   machine: Linux-5.15.0-94-generic-x86_64-with-glibc2.35

Python dependencies:
          pip: 23.3.1
   setuptools: 68.2.2
 scikit-learn: 1.4.1.post1
         aeon: 0.7.0
  statsmodels: None
        numpy: 1.23.5
        scipy: 1.10.0
       pandas: 2.0.3
   matplotlib: None
       joblib: 1.3.2
        numba: 0.56.4
     pmdarima: None
      tsfresh: None
</details>

**Comment by aadya940** [comment]
@MatthewMiddlehurst I think there are a few test files defined outside the `tests` folder in the `testing` module. Hence, it is not skipped by `MODULES_TO_IGNORE` in `_lookup.all_estimators` causing this issue?

**Comment by TonyBagnall** [comment]
I have also noted all_estimators takes a long time sometimes, 

> @MatthewMiddlehurst I think there are a few test files defined outside the `tests` folder in the `testing` module. Hence, it is not skipped by `MODULES_TO_IGNORE` in `_lookup.all_estimators` causing this issue?

good spot! Maybe just include testing in the MODULES_TO_IGNORE? Should also ignore datatypes, datasets and maybe visualisation?

**Comment by TonyBagnall** [comment]
I can reproduce this, but also note that return_tags is not a boolean

```python
return_tags: str or list of str, optional (default=None)
```

**Comment by TonyBagnall** [comment]
if I remove the return_tags argument in the above example and add testing to the modules to ignore, it works fine. I think it should be set to this
```python
    MODULES_TO_IGNORE = ("tests", "setup", "benchmarking", "utils", "all",
                         "testing", "datasets","registry","datatypes","visualisation")
```
do you agree @MatthewMiddlehurst?

thanks @CodeLionX for reporting it and @aadya940 for fixing it :) @CodeLionX would you like to fix it by creating a PR changing all_estimators MODULES_TO_IGNORE to the above (assuming matthew agrees to the list)?

**Comment by TonyBagnall** [comment]
I think slow execution is a separate issue, I'll run some tests, iirc its very slow when an incorrect tag is given but needs testing.

**Comment by CodeLionX** [comment]
I'll prepare a fix for the `pytest`-issue.

**Comment by MatthewMiddlehurst** [comment]
Was away for a bit, thanks for working on this. Merged the PR by @CodeLionX. Agreed that the slowness of the method should be separate.
