### ISSUE TITLE
[MNT] Cleanup Deep Learning Models

### ISSUE THREAD

**Issue by aadya940** [aeon-toolkit/aeon#1230]
### Describe the issue

In many of our deep learning models, we have the keyword argument `metrics = None`. Then we use the following code: 
```
if self.metrics is None:
            metrics = ["accuracy"]
else:
            metrics = self.metrics
```
Instead we could directly start with `metrics = ["accuracy"]` for brevity and remove the above given block. 

### Suggest a potential alternative/fix

Change as given above!

**Comment by AnonymousCodes911** [comment]
is anyone working on this?

**Comment by harshithasudhakar** [comment]
`metrics = "accuracy"` seems more concise. But wouldn't it sacrifice the flexibility and customization options that the current implementation provides? @aadya940

**Comment by harshithasudhakar** [comment]
Sure, I'd like to know the community's opinion on this. If @aadya940 's approach is more preferrable, can I take up this issue? :)

**Comment by harshithasudhakar** [comment]
@MatthewMiddlehurst may I know your opinion on this?

**Comment by MatthewMiddlehurst** [comment]
@hadifawaz1999 

`metrics="accuracy"` Seems better. It should be easy to check if the input is a string and turn it into a list. This may require editing the docstring to update the valid inputs (I assume str and list of str?).

**Comment by hadifawaz1999** [comment]
@MatthewMiddlehurst as long as its always transformed to list inside the code than it should be good to go, good first issue

**Comment by harshithasudhakar** [comment]
Thanks on your opinions. Would you assign this issue to me, I'd like to work in it :)
