### ISSUE TITLE
[BUG] Squaring the weights in KNN even though no sqrt is used for distances

### ISSUE THREAD

**Issue by hadifawaz1999** [aeon-toolkit/aeon#1234]
### Describe the bug

it seems [here](https://github.com/aeon-toolkit/aeon/blob/620caa54d29481c9c85b06799354e65b9dd28464/aeon/classification/distance_based/_time_series_neighbors.py#L207) that we square the weights in knn when finding the nearest neighbors, but in reality we dont sqrt the distances, so we are basically ending up with quadruple distance at the end 

### Expected results

it should only square the weights if we sqrt the distance

### Actual results

we are squaring the weights without sqrt the distance

**Comment by AgrawalTitiksha** [comment]
Hey there, maybe this could help when we use KNN algo we use euclidean distance formula to calculate distance so according to the formula first we need to take the root of the distance. Here's the code,

if self.weights == "distance":
    ws = np.sqrt(distances[closest_idx])  # Square root the distances
    # No need to square the weights, since we're already square rooting the distances
    ws = 1 / (ws + np.finfo(float).eps)

I guess this would have been a little helpful somehow
