### ISSUE TITLE
[BUG] intermittent failure in test_update_predict_predicted_index[STLForecaster-1-y:...]

### ISSUE THREAD

**Issue by TonyBagnall** [aeon-toolkit/aeon#124]
changes to a notebook have created a test failure

FAILED sktime/forecasting/tests/test_all_forecasters.py::TestAllForecasters::test_update_predict_predicted_index[STLForecaster-1-y:1cols-update_params=False-step=1-1-fh=[2 5]]
= 1 failed, 30728 passed, 529 skipped, 8 xfailed, 2 xpassed, 2963 warnings in 4171.41s (1:09:31) =

this fails on the unix test but not windows, suggesting it is an intermittent bug. 30k tests, 529 skipped and 2963 warning is not great. 

https://github.com/scikit-time/scikit-time/actions/runs/4284789715/jobs/7463679204

**Comment by TonyBagnall** [comment]
another example, testing needs complete overhaul, purge the nonsense, but it will take a long time to unpick the spaghetti

![image](https://user-images.githubusercontent.com/9594042/222543252-87ea24c1-3990-41a8-baf1-f840eba70a12.png)

**Comment by aiwalter** [comment]
> 2023-02-27T19:43:44.7411790Z worker 'gw0' crashed while running

might be just a random worker failure?

**Comment by MatthewMiddlehurst** [comment]
I don't believe this has reappeared, so I agree with @aiwalter that it's most unrelated to us

**Comment by MatthewMiddlehurst** [comment]
closing for now
