### ISSUE TITLE
[DOC] Proposal: list capabilities of individual estimators in their documentation

### ISSUE THREAD

**Issue by CodeLionX** [aeon-toolkit/aeon#1242]
### Describe the issue linked to the documentation

When browsing the available estimators (classifiers, clusterers, ...) in the aeon documentation or using IntelliSense, I cannot directly see which estimator supports which input types (the source code is of limited use because of class inheritance etc.).

### Suggest a potential alternative/fix

Aeon already stores the capabilities of individual estimators as tags in machine-readable form (see below), and we can list estimators based on their tags using the registry (e.g., with `registry.all_estimators(filter_tags={"capability:unequal_length": True})`).

https://github.com/aeon-toolkit/aeon/blob/620caa54d29481c9c85b06799354e65b9dd28464/aeon/base/_base_collection.py#L30-L37

and

https://github.com/aeon-toolkit/aeon/blob/620caa54d29481c9c85b06799354e65b9dd28464/aeon/base/_base_series.py#L57-L62

Can we use the tags to display the estimator's capabilities also in the documentation?

**Comment by TonyBagnall** [comment]
It's a good idea, it would be easy to make a single page displaying them in a table, more complex to embed in docstrings (i.e. I don't know how to:)

**Comment by TonyBagnall** [comment]
We could just list them in the docstring, i.e. insert manually?

**Comment by CodeLionX** [comment]
Sure. That would help me as well.

**Comment by MatthewMiddlehurst** [comment]
There could be a way to add the tags to the automatic API generation for the webpage, but I don't imagine this is simple. When it comes to adding it to the source docstring, I'm afraid that may have to be manual.

What sounds the easiest from our end, would be to bring back the [estimator overview page](https://www.aeon-toolkit.org/en/v0.3.0/estimator_overview.html) (but useful). Would having a searchable table which displays the tags be helpful for your usage at all @CodeLionX? Obviously not the best solution, and we didnt really see a point in keeping the previous iterarion.
