### ISSUE TITLE
[ENH] Implement Learning Shapelet algorithm for Time Series Classification

### ISSUE THREAD

**Issue by itsdivya1309** [aeon-toolkit/aeon#1246]
### Describe the feature or idea you want to propose

Learning shapelet is a TSC algorithm with several advantages over the Shapelet Transform algorithm. Currently, aeon doesn't have its implementation but it would be great to have one.

https://www.ismll.uni-hildesheim.de/pub/pdfs/grabocka2014e-kdd.pdf

### Describe your proposed solution

As discussed on Slack, we can wrap the TSLearn implementation for now and then improve its performance.

**Comment by baraline** [comment]
Hi, I think it's a good idea, a simple solution could be to warp around the TSlearn, but it would be nice to have our own implementation of it so we can extend it to further developments that were made in this field, such as DTW-preserving shapelets, contrastive shapelets etc... any thought on this @TonyBagnall  ?

**Comment by itsdivya1309** [comment]
Yes, I'll wrap the TSLearn implementation as a starting point.
