### ISSUE TITLE
[ENH] classifier_type tags in classifiers

### ISSUE THREAD

**Issue by TonyBagnall** [aeon-toolkit/aeon#126]
Looking to tidy up note books so we have one for each classifier type. Classifiers have a tag classifier_type to reflect the package they are in. For example, the FreshPrince classifier is in the feature_based package and has this tag
        "classifier_type": "feature"
a quick look indicates these tags are not present in all classifiers, and some may be incorrect. For example, deep_learning do not have tags, and convolution_based should change from kernel to convolution. Currently, the tags for this as follows

(
    "classifier_type",
    "classifier",
    (
        "list",
        [
            "dictionary",
            "distance",
            "feature",
            "hybrid",
            "interval",
            "kernel",
            "shapelet",
        ],
    ),
    "which type the classifier falls under in the taxonomy of time series "
    "classification algorithms.",
so I am going to make the following changes

kernel -> convolution, 
add one for deep learning ("deep_learning"?). sklearn and compose

then I will add in any missing. Just putting this here in case there is some issue I have overlooked with changing tags, it cascades throughout the whole toolikit ....

**Comment by lmmentel** [comment]
Do you have any insight into how those tags are used?

**Comment by TonyBagnall** [comment]
our tags are used purely descriptively, so we can do things like this in notebooks

**Comment by TonyBagnall** [comment]
scikit tags _estimator_type is used in things like CV
https://scikit-learn.org/stable/developers/develop.html

![image](https://user-images.githubusercontent.com/9594042/222141082-6e06e37b-9b8b-49a1-af98-2e2346105e02.png)
