### ISSUE TITLE
[ENH] AEP: new module for channel selection

### ISSUE THREAD

**Issue by TonyBagnall** [aeon-toolkit/aeon#1270]
### Describe the feature or idea you want to propose

we are researching the best way of channel selection for EEG, but it is applicable generally. Over the summer we will introduce new functionality. Currently we have a single file called channel_selection containing two BaseCollectionTransformers, ElbowClassSum and ElbowClassPairwise .

### Describe your proposed solution

 I propose a new submodule in transformation.collection called channel_selection and refactoring the these two into a file _elbow_class, with deprecation of the old ones in 0.9

**Comment by aadya940** [comment]
Can I work on this? @TonyBagnall

**Comment by TonyBagnall** [comment]
hi @aadya940 sorry, missed this, probably easiest if I do the restructuring, but if you are interested in channel selection that would be great

**Comment by aadya940** [comment]
@TonyBagnall Yes, I'd be very happy to work on channel selection algorithms ( seperately from GSoC since I'm applying for proximity forest ) :-). Please let me know any papers I'll need to read for this.
