### ISSUE TITLE
[MNT] CI test warnings

### ISSUE THREAD

**Issue by chrisholder** [aeon-toolkit/aeon#1282]
There test CI has a lot of warnings once the tests are run. I would like to clean most of these up (where possible). I have created a list of the general warnings we can begin cleaning up. 

### Deprecation Warnings
- [ ]  _base.py Future Warnings
- [ ]  Address the deprecation of SklearnClassifierPipeline class. It's advised to use ClassifierPipeline or the sklearn pipeline instead. See _base.py:569.
- [ ]  Update the initialization method for ClassifierPipeline to avoid breakage when the positions of the classifier and transformers arguments are swapped. See _base.py:569.
- [ ]  _reduce.py Deprecation Warnings
- [ ]  Correct the use of converting an array with ndim > 0 to a scalar to avoid future errors. This affects various test files including test_all_forecasters.py, test_reduce.py, test_autoensemble.py, test_reduce_global.py, and test_pipeline.py. See _reduce.py:629 and _reduce.py:937.

### Future Warnings
- [ ]  Deprecated Function get_examples
- [ ]  Replace the deprecated get_examples function across various datatypes tests (test_check.py, test_convert.py, test_vectorize.py) with its newer version from the testing module.
- [ ]  Statsmodels Index Support
- [ ]  Address the future warning regarding the lack of supported index in test_all_forecasters.py. This warning originates from the Statsmodels library.
- [ ]  Joblib Deprecation Warnings
- [ ]  Update code to avoid using deprecated Joblib features related to ast.Num and n attribute, as seen in various tests (test_softdeps.py, test_window_summarizer.py, test_optionalpassthrough.py, test_reduce_global.py).

### Class and Method Deprecations
- [x]  Deprecated Classes warnings
- [x]  Update or replace usage of deprecated classes such as MatrixProfileClassifier, BaseForecastingErrorMetric, HMM, and Hidalgo across various tests and modules.
- [ ]  Sklearn Pipeline and Classifier Warnings
- [ ]  Address the deprecation of SklearnClassifierPipeline and related warnings in test_all_estimators.py and classification/tests.
- [ ]  Numpy and Scipy Warnings
- [ ]  Address deprecation warnings related to numpy array operations and scipy optimizations.
- [ ]  General Cleanup

Here is a link to a CI run for more details: https://github.com/aeon-toolkit/aeon/actions/runs/8145354708/job/22261460345

**Comment by TonyBagnall** [comment]
https://github.com/aeon-toolkit/aeon/issues/1238

**Comment by TonyBagnall** [comment]
there are still a lot of warnings, but they are different to those listed and the link is now dead, so closing this. Should look at warnings again though
