### ISSUE TITLE
[ENH] What to do with DummyClassifier?

### ISSUE THREAD

**Issue by TonyBagnall** [aeon-toolkit/aeon#130]
DummyClassifier is simply a wrapper for SklearnDummyClassifier, I dont really see the point, I think we should look to promote using scikit learn tools, not wrap them. It is simply this

        self.sklearn_dummy_classifier = SklearnDummyClassifier(
            strategy=strategy, random_state=random_state, constant=constant
        )

fit:        self.sklearn_dummy_classifier.fit(np.zeros(X.shape), y)
        return self
predict:
        return self.sklearn_dummy_classifier.predict(np.zeros(X.shape))

I think that this will  just confuse the user used to using scikit. It also uses "nested_univ" (dataframe) internal data type and creates an empty numpy

**Comment by patrickzib** [comment]
I agree. I do not see the point in duplicating sklearn functionality.

**Comment by MatthewMiddlehurst** [comment]
While it can probably be improved, I think having an extremely simple and quick classifier for interface testing is useful.

**Comment by TonyBagnall** [comment]
fair enough, lets keep it. I dont like it being in its own package though, I'm guessing if it goes in classification/ it will cause import problems?
