### ISSUE TITLE
[BUG] _coerce_to_period fails when not passed a freq argument 

### ISSUE THREAD

**Issue by TonyBagnall** [aeon-toolkit/aeon#1346]
### Describe the bug

whilst writing tests noticed that this fails

```python

def _coerce_to_period(x, freq=None):
    if isinstance(x, pd.Timestamp) and freq is None:
        freq = x.freq
        raise ValueError(
            "_coerce_to_period requires freq argument to be passed if x is pd.Timestamp"
        )
```

it is never called without a freq argument and its a private method, and then it raises an error, so not sure what freq=x.freq is meant to do

### Steps/Code to reproduce the bug

```
from aeon.forecasting.base._fh import _coerce_to_period

import pandas as pd
import pytest

timestamp = pd.Timestamp("2022-01-01")
result = _coerce_to_period(timestamp)
```

### Expected results

freq = x.freq

### Actual results

```python-traceback
  File "C:\Code\aeon\aeon\local\debug.py", line 35, in <module>
    result = _coerce_to_period(timestamp)
  File "C:\Code\aeon\aeon\forecasting\base\_fh.py", line 792, in _coerce_to_period
    freq = x.freq
AttributeError: 'Timestamp' object has no attribute 'freq'
```

**Comment by baraline** [comment]
Isn't the `freq=None`  argument meant to be used when x is a series or a dataframe ? In which case, `x.freq` do make sense. But if it is never used, as it is a private function, I also see no use of it.
