### ISSUE TITLE
[DOC] Correcting the documentation of the `random_state` parameter

### ISSUE THREAD

**Issue by hadifawaz1999** [aeon-toolkit/aeon#1349]
### Describe the issue linked to the documentation

Given the problem solved in #1271 we should make sure in all modules if there exists a miss-explanation of the `random_state` parameter in the docstrings

**Comment by hx4nn** [comment]
hey @AnonymousCodes911, can you assign this to me..

**Comment by AnonymousCodes911** [comment]
Hi @hx4nn, I am already in the process of doing this 😅

**Comment by hx4nn** [comment]
sure 👍

**Comment by hadifawaz1999** [comment]
i think we can close this now and re-open if we find something again or disagree
