### ISSUE TITLE
[BUG] Squaring weights in `KNeighborsTimeSeriesRegressor`

### ISSUE THREAD

**Issue by AnonymousCodes911** [aeon-toolkit/aeon#1355]
### Describe the bug

refer: #1234 and #1240 
see [this](https://github.com/aeon-toolkit/aeon/blob/2240e5c59d1e8e6db9442343c5fc6a4b95258e98/aeon/regression/distance_based/_time_series_neighbors.py#L175) we dont need to square the weights here !

### Steps/Code to reproduce the bug

in `class KNeighborsTimeSeriesRegressor(BaseRegressor):`

```python
        if self.weights == "distance":
            ws = distances[closest_idx]
            ws = ws**2 # after removing this

            # Using epsilon ~= 0 to avoid division by zero
            ws = 1 / (ws + np.finfo(float).eps)
```

### Expected results

the [`test_time_series_neighbors.py`](https://github.com/aeon-toolkit/aeon/blob/2240e5c59d1e8e6db9442343c5fc6a4b95258e98/aeon/regression/distance_based/tests/test_time_series_neighbors.py) should return :
Expected predictions: [-216.06541863 -4.54133078 -324.7624233 ]

### Actual results

But it returns : 
```python
AssertionError: assert 94.78595550443961 < 1e-06
```
and Actual predictions : [-144.41037008 -25.55876587 -229.9764678 ]

**Comment by TonyBagnall** [comment]
just looking into this. The inverse distances are used as weights to average predictions, so its natural that squaring them would produce different predictions than if you didnt. I think we just make it correct then run the experiments to see if it makes a difference
