### ISSUE TITLE
[ENH] Update Catch22 transformer

### ISSUE THREAD

**Issue by MatthewMiddlehurst** [aeon-toolkit/aeon#1384]
### Describe the feature or idea you want to propose

Since its implementation, the numba version of `Catch22` ([code here](https://github.com/aeon-toolkit/aeon/blob/main/aeon/transformations/collection/feature_based/_catch22.py)) has become slightly out of date compared to the [original implementation](https://github.com/DynamicsAndNeuralSystems/pycatch22).

The features which now differ should be updated, and parity with the original output should be verified

### Describe your proposed solution

Look at the [authors implementation](https://github.com/DynamicsAndNeuralSystems/pycatch22) (C code), and update our version of the features in numba to match.

The transformer has a parameter to use this package, so the results can be compared to verify they are the same (or similar).

**Comment by hadifawaz1999** [comment]
this can be a good first issue @MatthewMiddlehurst you agree ?

**Comment by MatthewMiddlehurst** [comment]
It requires an understanding of the algorithm and involves comparing to and probably running C code, so probably not.

**Comment by MatthewMiddlehurst** [comment]
I still don't really trust it due to previous issues with installation and Windows. If it is proven to be stable then can consider it.
