### ISSUE TITLE
[BUG] Dependencies version checking not handling python release candidate correctly

### ISSUE THREAD

**Issue by zobelb** [aeon-toolkit/aeon#1395]
### Describe the bug

When using Python 3.11.0rc1, an exception is thrown stating this is not a release less than 3.12. I suspect that there being no space between 3.11.0 and rc1 is causing this version test to fail.

An exception occurred: IndividualInceptionClassifier requires python version to be <3.12, but system python version is 3.11.0rc1 (main, Aug 12 2022, 10:02:14) [GCC 11.2.0].

### Steps/Code to reproduce the bug

```from aeon.classification.deep_learning import InceptionTimeClassifier
from aeon.datasets import load_unit_test

X_train, y_train = load_unit_test(split="train")
X_test, y_test = load_unit_test(split="test")

inctime = InceptionTimeClassifier(n_epochs=20,batch_size=4)
print(inctime.fit(X_train, y_train))
```

### Expected results

InceptionTimeClassifier(batch_size=4, n_epochs=20)

### Actual results

```
File "/home/username/aeon_test.py", line 10, in <module>
    print(inctime.fit(X_train, y_train))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aeon/classification/base.py", line 175, in fit
    self._fit(X, y)
  File "/usr/local/lib/python3.11/dist-packages/aeon/classification/deep_learning/_inception_time.py", line 249, in _fit
    cls = IndividualInceptionClassifier(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aeon/classification/deep_learning/_inception_time.py", line 540, in __init__
    super().__init__(
  File "/usr/local/lib/python3.11/dist-packages/aeon/classification/deep_learning/base.py", line 63, in __init__
    super().__init__()
  File "/usr/local/lib/python3.11/dist-packages/aeon/classification/base.py", line 86, in __init__
    super().__init__()
  File "/usr/local/lib/python3.11/dist-packages/aeon/base/_base_collection.py", line 44, in __init__
    _check_estimator_deps(self)
  File "/usr/local/lib/python3.11/dist-packages/aeon/utils/validation/_dependencies.py", line 351, in _check_estimator_deps
    compatible = compatible and _check_python_version(obj, severity=severity)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aeon/utils/validation/_dependencies.py", line 289, in _check_python_version
    raise ModuleNotFoundError(msg)
ModuleNotFoundError: IndividualInceptionClassifier requires python version to be <3.12, but system python version is 3.11.0rc1 (main, Aug 12 2022, 10:02:14) [GCC 11.2.0].
```

### Versions

<details>Python 3.11.0rc1 (main, Aug 12 2022, 10:02:14) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from aeon import show_versions;show_versions()

System:
    python: 3.11.0rc1 (main, Aug 12 2022, 10:02:14) [GCC 11.2.0]
executable: /usr/bin/python
   machine: Linux-6.5.0-26-generic-x86_64-with-glibc2.35

Python dependencies:
          pip: 23.3.1
   setuptools: 69.0.1
 scikit-learn: 1.4.1.post1
         aeon: 0.7.1
  statsmodels: None
        numpy: 1.26.2
        scipy: 1.12.0
       pandas: 2.0.3
   matplotlib: 3.8.4
       joblib: 1.3.2
        numba: 0.59.1
     pmdarima: None
      tsfresh: None
</details>

**Comment by baraline** [comment]
Hi @zobelb I do not seem to be able to reproduce your issue on python 3.11. What is your TensorFlow version ? That might be the origin of the conflict. I'm using `2.16.1`.

```python
from aeon.datasets import load_unit_test
from aeon.classification.deep_learning import InceptionTimeClassifier

X_train, y_train = load_unit_test(split="train")
X_test, y_test = load_unit_test(split="test")

inctime = InceptionTimeClassifier(n_epochs=20,batch_size=4)
print(inctime.fit(X_train, y_train))
```

System config :
```
System:
    python: 3.11.8 | packaged by conda-forge | (main, Feb 16 2024, 20:40:50) [MSC v.1937 64 bit (AMD64)]
executable: C:\Users\antoine\anaconda3\envs\test_env\python.exe
   machine: Windows-10-10.0.22631-SP0

Python dependencies:
          pip: 24.0
   setuptools: 69.2.0
 scikit-learn: 1.4.2
         aeon: 0.8.0
  statsmodels: None
        numpy: 1.26.4
        scipy: 1.12.0
       pandas: 2.0.3
   matplotlib: None
       joblib: 1.4.0
        numba: 0.59.1
     pmdarima: None
      tsfresh: None
```

**Comment by zobelb** [comment]
Antoine, this is with the Tensorflow Docker containers that are packed with Python 3.11.0rc1. My suspicion is that it's the "rc1" part that is causing the issue from what I can see in the code. I've tried creating a development install of the aeon package on my computer but am running into issues with that so I can't verify my theory.

ERROR: Project file: aeon has a 'pyproject.toml' and its build backend is missing the 'build_editable' hook. Since it does not have a 'setup.py' nor a 'setup.cfg', it cannot be installed in editable mode. Consider using a build backend that supports PEP 660. 

I thought setuptool 69.2.0 should get rid of that error.

**Comment by baraline** [comment]
You get this error while trying to install aeon from sources right ? This should indeed not happen, which command are you using ? 

I'll take a look at the rc1 thing, maybe @MatthewMiddlehurst knows more or maybe @hadifawaz1999 has encountered similar issues during his work on DL ?

**Comment by zobelb** [comment]
Following the instructions here: https://www.aeon-toolkit.org/en/stable/developer_guide/dev_installation.html

**Comment by MatthewMiddlehurst** [comment]
A bit strange that an old release candidate is being used, but I'm sure there's a valid reason. Not sure if the function for version checking can handle that, I agree. 

AFAIK `setuptools>=64` supports PEP 660? The install failure seems a bit weird. If you raise the `build-system` bound in `pyproject.toml` does that change anything?

**Comment by baraline** [comment]
Good job ! 
If you want to contribute this change you are welcome to ! Just tell us wheter you would want to do it (so we can implement the fix ourselves if you don't). If you need some help on contributing don't hesitate to message us on Slack.
