### ISSUE TITLE
[DOC] Add plot_windows to docs and provide docstring example

### ISSUE THREAD

**Issue by aiwalter** [aeon-toolkit/aeon#140]
function can be found here:
https://github.com/scikit-time/scikit-time/blob/15a3faf2a203b22f6e0b536a5e2d99352c83ac7a/sktime/utils/plotting.py#L387

**Comment by vermaaatul07** [comment]
I am working on this , assign it to me please.

**Comment by TonyBagnall** [comment]
I think this issue is stale post visualisation and KWF, closing it, feel free to bring it back if Im wrong
