### ISSUE TITLE
[ENH] Distance transformer

### ISSUE THREAD

**Issue by TonyBagnall** [aeon-toolkit/aeon#144]
There is a transformer DistanceFeatures introduced without review in Sept 2022. It transforms data so each feature is a distance to to a train example, 
https://github.com/sktime/sktime/pull/3356

much as is done here, for example, here
"Using dynamic time warping distances as features for improved time series
classification" https://link.springer.com/article/10.1007/s10618-015-0418-x

This transformer is being removed in #143  , because it uses dists_and_kerns, and because it has a hugely inefficient internal conversion mechanism. In principle, I think it a useful tool, although not used much in research any more, so I think it would be a good enhancement, once transformations is sorted out, to have a transformer that works internally with numpy arrays

So the good first issue is to write a transformer that takes a 3D train set (n_train_instances,n_dimensions,series_length) as input, and a distance function, transforms and returns a 2D distance function (n_train_instances,n_train_instances) where the cell [i][j] is the distance between the ith and jth train set. Fit should take a 3D testset (n_test_instances,n_dimensions,series_length)  returns a 2D matrix(n_test_instances, n_train_instances) where the cell [i][j] is the distance between the ith test instance and jth train instance.

**Comment by patrickzib** [comment]
I believe this could easily be implemented using sklearn and pairwise distances:

https://scikit-learn.org/stable/modules/generated/sklearn.metrics.pairwise_distances.html

**Comment by TonyBagnall** [comment]
we have a function for pairwise distances in distances module I think @chrisholder, this would just wrap that in the transformer, although maybe wait until the transformer interface has settled down somewhat
