### ISSUE TITLE
[DOC] Create map of how to chose rights estimator/transformers/pipeline etc

### ISSUE THREAD

**Issue by aiwalter** [aeon-toolkit/aeon#145]
create a visualization map similar to this from `scikit-learn`:
https://scikit-learn.org/stable/tutorial/machine_learning_map/index.html

It should guide user to make decision for:

- different learning problems
- data shape
- seasonality/trend
- parameters choices
- pipelines
- pre and post-processing

we could start with one learning problem and then extend

**Comment by TonyBagnall** [comment]
closing due to KWF, can reintroduce at a later date
