### ISSUE TITLE
[DOC] Remove optional from docstrings

### ISSUE THREAD

**Issue by TonyBagnall** [aeon-toolkit/aeon#1451]
### Describe the issue linked to the documentation

this is a minor change to allow new contributors to figure out the github workflow and make a first minor contribution. Our current standard doc comment for optional parameters is the

```
   window_length : int, default=10
```
however, in many places it is still listed as this

```
   window_length : int, optional (default=10)
```
it would be good to standardise across the toolkit. Feel free to change as few or as many as these as you want in order to make a contribution

**Comment by griegner** [comment]
Happy to take on this issue, using vscode's find/replace to find regex pattern `optional \(default=(.*)\)` and replace with `default=$1`. I'll double check all replacements to verify that this procedure doesn't cause any problems with edge cases.
