### ISSUE TITLE
[DOC] Spelling mistake lenght

### ISSUE THREAD

**Issue by TonyBagnall** [aeon-toolkit/aeon#1452]
### Describe the issue linked to the documentation

this is a minor change to allow new contributors to figure out the github workflow and make a first minor contribution. 

there are three occurrences of "lenght" instead of "length". Good first contribution is to correct this spelling mistake

**Comment by RishavKumarSinha** [comment]
Hello there! I want to claim this issue, can you please provide the link to file that consists of the spelling mistakes?

**Comment by TonyBagnall** [comment]
sure, search shows this
<img width="434" alt="image" src="https://github.com/aeon-toolkit/aeon/assets/9594042/9a8e1d13-c636-41d9-a45c-239c526a6cf1">
