### ISSUE TITLE
[ENH] Implement the Multi Comparison Matrix in visualization module

### ISSUE THREAD

**Issue by hadifawaz1999** [aeon-toolkit/aeon#1463]
### Describe the feature or idea you want to propose

it would be good if we port in the MCM from this paper: https://arxiv.org/abs/2305.11921 for the evaluation visulization

### Describe your proposed solution

The provided code for the paper: https://github.com/MSD-IRIMAS/Multi_Comparison_Matrix

**Comment by TonyBagnall** [comment]
so looking at this, I would guess the tasks are
1. Copy the MCM directory into the visualisation module
2. Update  the  docstrings so they conform to aeon
3. Make sure softdeps are correctly dealt with
4. Add testing
5. Add a notebook to the show usage.

does that sound about right? Some of the utils could possibly be moved to the util directory, but that can be part of a wider tidying up of tests etc. Might also ask @dguijo to advise, there may be reproduction of functionality

**Comment by hadifawaz1999** [comment]
> so looking at this, I would guess the tasks are
> 
>     1. Copy the MCM directory into the visualisation module
> 
>     2. Update  the  docstrings so they conform to aeon
> 
>     3. Make sure softdeps are correctly dealt with
> 
>     4. Add testing
> 
>     5. Add a notebook to the show usage.
> 
> 
> does that sound about right? Some of the utils could possibly be moved to the util directory, but that can be part of a wider tidying up of tests etc. Might also ask @dguijo to advise, there may be reproduction of functionality


Yes it all sounds good @TonyBagnall , should note though that the code of MCM gives ability to save the file in either pdf.png format and as well as latex format, so the code produces a latex version of the MCM plot (not with matplotlib but pure latex) and outputs a .tex file, so i think for aeon we will keep the pdf one for sure generated with matplotlib, but do we keep the latex version as well ?
