### ISSUE TITLE
[ENH] Implement Yeo-Johnson Series Transformer

### ISSUE THREAD

**Issue by TonyBagnall** [aeon-toolkit/aeon#1475]
### Describe the feature or idea you want to propose

a long time ago I experimented with the Yeo-Johnson regressor transform.

https://ieeexplore.ieee.org/document/1716845

Yeo-Johnson is an extension of Box-Cox that allows xero and negative regressor values. We have an implementation of Box Cox, it would be nice to include Yeo-Johnson 

### Describe your proposed solution

either extend Box Cox once it is moved into series tranformers, or implement a new BaseSeriesTransformer

**Comment by alexbanwell1** [comment]
@aeon-actions-bot assign @alexbanwell1
