### ISSUE TITLE
[BUG]  matrix profile distance index out of bounds test failure

### ISSUE THREAD

**Issue by MatthewMiddlehurst** [aeon-toolkit/aeon#1498]
### Describe the bug

The matrix profile distance is currently failing on the code coverage tests which disable numba. Most likely from changes in #1415.

Why does the `test_mpdist` test fail and the other distances ones don't, is the distance function only being used here?

### Steps/Code to reproduce the bug

Run the `test_mpdist` test without numba

https://github.com/aeon-toolkit/aeon/actions/runs/8978393264/job/24658747510

### Expected results

Test passes with and without numba

### Actual results

Test fails with no numba

### Versions

See CI failure

**Comment by TonyBagnall** [comment]
I can reproduce this, its weird!

**Comment by TonyBagnall** [comment]
I dont think a zero length subsequence makes much sense, and m should be constrained to be >0

**Comment by TonyBagnall** [comment]
but then in _stomp_ab we have
```
    len_x = len(x)
    len_y = len(y)
    if m == 0:
        if len_x > len_y:
            m = int(len_x / 4)
        else:
            m = int(len_y / 4)
```
so zero is indicating set to 1/4 length really. I should go back and remind myself how it works lol
