### ISSUE TITLE
[DOC] Update regression API docs

### ISSUE THREAD

**Issue by MatthewMiddlehurst** [aeon-toolkit/aeon#1500]
### Describe the issue linked to the documentation

The [regression API page](https://www.aeon-toolkit.org/en/stable/api_reference/regression.html) should be updated to add new regressors.

### Suggest a potential alternative/fix

Look through the regression module estimators, and update the API page to reflect the current state.

**Comment by Moonzyyy** [comment]
Hello! I am happy to fix this issue, good way for me to start learning more about open source integration too!
