### ISSUE TITLE
[ENH] Implement or add tests for `FunctionalTransformer`

### ISSUE THREAD

**Issue by MatthewMiddlehurst** [aeon-toolkit/aeon#152]
`sklearn` has a `FunctionalTransformer` which simply allows user functions to be used as transformers. We should add tests to make sure this works for our interface or implement a version that does.

See: https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.FunctionTransformer.html

**Comment by aiwalter** [comment]
We got one: https://github.com/scikit-time/scikit-time/blob/main/sktime/transformations/series/func_transform.py

**Comment by MatthewMiddlehurst** [comment]
I still think it would be worthwhile testing the `sklearn` version as well. There have been a lot of suggestions for wrappers in the past where `sklearn` works fine.

**Comment by TonyBagnall** [comment]
See also https://github.com/aeon-toolkit/aeon/issues/144

**Comment by TonyBagnall** [comment]
just tried this
```python
import numpy as np

from sklearn.preprocessing import FunctionTransformer
from aeon.distances import dtw_distance, dtw_pairwise_distance
X = np.random.random(size=(10,1,20))

ft = FunctionTransformer(func=dtw_pairwise_distance, check_inverse=False)
X2 = ft.transform(X)
print("Shape of X = ",X2.shape)
d1 =dtw_distance(X[0],X[0])
d2 =dtw_distance(X[0],X[1])
d3 =dtw_distance(X[8],X[9])

print(" (0,0) = ",d1," and ", X2[0][0])
print(" (0,1) = ",d2," and ", X2[0][1])
print(" (8,9) = ",d3," and ", X2[8][9])
```
and it works fine. I will add some sklearn compatibility tests and also add this to the sklearn-distances notebook
