### ISSUE TITLE
[ENH] Implement `MockClusterer`

### ISSUE THREAD

**Issue by MatthewMiddlehurst** [aeon-toolkit/aeon#1529]
### Describe the feature or idea you want to propose

Add a `MockClusterer` to the `testing` module.

### Describe your proposed solution

This should be simple in line with the `classification` and `regression`, used for unit tests and similar.

**Comment by notaryanramani** [comment]
Hi @MatthewMiddlehurst, just for a small clarification we want to add a `MockCluster` class to testing which is in line with `MockClassifier` and `MockRegressor`.

**Comment by MatthewMiddlehurst** [comment]
@notaryanramani yep! the clustering do not have to make any sense really, just needs to follow the interface

**Comment by notaryanramani** [comment]
Okay! Can you assign this issue to me? @MatthewMiddlehurst
