### ISSUE TITLE
[ENH] `BaseClusterer` inconsistencies with other base classes

### ISSUE THREAD

**Issue by MatthewMiddlehurst** [aeon-toolkit/aeon#1530]
There are a few issues present in the `BaseClusterer` class IMO:

- The `predict` function has a `y` input, this is inconsistent with other collection classes and with `predict_proba` from the same class
- The `score` function is functionally different to other bases and is a required method. Can all algorithms produce scores like this? What about pipelines etc.
- `fit_predict` does not have a private equivalent like other classes. Also, by default it seems like this should return `labels_` rather than calling `_predict`?
- `n_clusters` is a required attribute, but not all algorithms have a set number of clusters.

Agreed at the dev meeting 25/10/25:

- [x] The predict function has a y input, this is inconsistent with other collection classes and with predict_proba from the same class
- [ ] The score function is functionally different to other bases and is a required method. Can all algorithms produce scores like this? What about pipelines etc.
- [ ] fit_predict does not have a private equivalent like other classes. Also, by default it seems like this should return labels_ rather than calling _predict?
- [ ] n_clusters is a required attribute, but not all algorithms have a set number of clusters.

**Comment by TonyBagnall** [comment]
"n_clusters is a required attribute, but not all algorithms have a set number of clusters."

I think all of our clusterers do require number of clusters? This was a choice since we only currently have partitional clusterers and we deferred it until we have a hierarchical clusterer to avoid excessive subclassing

**Comment by MatthewMiddlehurst** [comment]
It becomes a bit more of an issue for simple pipelines i.e. #1548, which just pass features to an `sklearn` clusterer as these may not have an `n_clusters` parameter.

**Comment by TonyBagnall** [comment]
has it already been changed? Doesnt seem to be required atm

```python
class BaseClusterer(BaseCollectionEstimator, ABC):
    """Abstract base class for time series clusterers.

    Parameters
    ----------
    n_clusters : int, default=None
        Number of clusters for model.
    """

    def __init__(self, n_clusters: int = None):
        self.n_clusters = n_clusters
        # required for compatibility with some sklearn interfaces e.g.
        # CalibratedClassifierCV
        self._estimator_type = "clusterer"

        super().__init__()
        _check_estimator_deps(self)
```

**Comment by MatthewMiddlehurst** [comment]
Its still a required attribute even if None, is that the intention even for algorithms which dont set it?

**Comment by chrisholder** [comment]
When making the initial base class with predict_proba and requiring n_clusters we knew this wouldn't work for all clusterers but I think we said we'd worry about fixing that when we have clusterers it doesn't apply to. Happy to rework the base class.

**Comment by TonyBagnall** [comment]
1. The predict function has a y input, this is inconsistent with other collection classes and with predict_proba from the same class

this is wrong to fix it

2. The score function is functionally different to other bases and is a required method. Can all algorithms produce scores like this? What about pipelines etc.

agreed to remove score from base class

3. fit_predict does not have a private equivalent like other classes. Also, by default it seems like this should return labels_ rather 
than calling _predict?

add private fit_predict for consistency

>by default it seems like this should return labels_ 

4. n_clusters is a required attribute, but not all algorithms have a set number of clusters.

agreed to remove from base class.
