### ISSUE TITLE
[DOC] Mix Docstring styles in aeon.

### ISSUE THREAD

**Issue by aadya940** [aeon-toolkit/aeon#1540]
### Describe the issue linked to the documentation

Some methods uses Parameters, Returns in the docstring whereas some methods uses Arguments, Returns, for example, `AEFCNNetwork.build_network`. I think we could use the same style for consistency, shifting everything to Numpy style docstrings (Parameters, Returns)?

**Comment by TonyBagnall** [comment]
yes I agree

**Comment by Moonzyyy** [comment]
Just went through the doc and haven't seen any (Arguments, Returns). I am assuming someone has fixed this, but hasn't closed this issue

**Comment by aadya940** [comment]
Check `aeon.networks._ae_fcn.py`. Check the `build_network` method in the file.

**Comment by aadya940** [comment]
You can find other files using `grep -i` if you're using linux.

**Comment by IRKnyazev** [comment]
Aeon-Assign bot assign @IRKnyazev
