### ISSUE TITLE
[ENH] Extend support to python 3.11

### ISSUE THREAD

**Issue by lmmentel** [aeon-toolkit/aeon#155]
Python 3.11 was release some months ago (24 Oct 2022) and we should try to include it as supported version.

Waiting for:
- https://github.com/numba/numba/issues/8304
- https://github.com/numba/numba/issues/8841

**Comment by MatthewMiddlehurst** [comment]
One of the main hold-ups for this is `numba`, which seems to be close to supporting 3.11 (see https://github.com/numba/numba/issues/8304)

**Comment by lmmentel** [comment]
Nów waiting for the release
