### ISSUE TITLE
[DOC] Find good images for examples docs

### ISSUE THREAD

**Issue by TonyBagnall** [aeon-toolkit/aeon#1568]
### Describe the issue linked to the documentation

our examples are presented in blocks with an image, 
https://www.aeon-toolkit.org/en/stable/examples.html

it would be nice to populate it with relevant images (which we have permission to use)

The documents are stored in aeon/examples (e.g. aeon/examples/classification/img) and linked into the docs in docs/examples.md, e.g

## Classification

::::{grid} 2 3 4 4
:gutter: 1

:::{grid-item-card}
:img-top: examples/classification/img/tsc.png
:class-img-top: aeon-card-image-m
:link: /examples/classification/classification.ipynb
:link-type: ref
:text-align: center

**Comment by Abhash297** [comment]
I would like to work on this

**Comment by MatthewMiddlehurst** [comment]
Thanks, let us know if you need any help.
