### ISSUE TITLE
[ENH] Naming of feature based collection transformers

### ISSUE THREAD

**Issue by TonyBagnall** [aeon-toolkit/aeon#1569]
### Describe the feature or idea you want to propose

we currently have four collection transformers that extract a vector of features. These are called

```python
__all__ = [
    "Catch22",
    "TSFreshFeatureExtractor",
    "TSFreshRelevantFeatureExtractor",
    "SevenNumberSummaryTransformer",
]
```

The naming convention is not consistent. I think we should choose one way of doing it and use that. 

### Describe your proposed solution

three options are
1. No suffix: Catch22, TSFresh, TSFreshRelevant
2. CollectionTransformer suffix
3. FeatureExtractor suffix

I dont mind which, but we should be consistent. Any thoughts?

### Describe alternatives you've considered, if relevant

I could stop concerning myself with naming conventions :)

**Comment by MatthewMiddlehurst** [comment]
My preference is option 1. Should tidy up TSFresh at some point 🙂
