### ISSUE TITLE
[DOC] write_to_tsfile function documentation ends abruptly

### ISSUE THREAD

**Issue by CodeLionX** [aeon-toolkit/aeon#1578]
### Describe the issue linked to the documentation

The documentation of `write_to_tsfile` ends with an incomplete sentence and I wonder whether the sentence is actually supposed to be there:

https://github.com/aeon-toolkit/aeon/blob/04e34db2cee7d5c8f65722e0c12fe9bd4c917fad/aeon/datasets/_data_writers.py#L260-L266

This part is also rendered in the public API documentation:
https://www.aeon-toolkit.org/en/stable/api_reference/auto_generated/aeon.datasets.write_to_tsfile.html#aeon.datasets.write_to_tsfile

### Suggest a potential alternative/fix

Either remove last sentence or finish it.

**Comment by TonyBagnall** [comment]
lol, I have a terrible tendency to do this

**Comment by TonyBagnall** [comment]
note that this is still a there  Note that this hanging sentence is still in the function write_to_tsf_file (#1706 removed a different sentence) so this is the easiest of easy good first issues.
