### ISSUE TITLE
[MNT] Investigate random state failure in test_feature_selection[None-2-random]

### ISSUE THREAD

**Issue by aiwalter** [aeon-toolkit/aeon#158]
test `test_feature_selection[None-2-random]` was failing "randomly", need to investigate it.

pipeline: https://github.com/aeon-toolkit/aeon/actions/runs/4344052231/jobs/7587082413

**Comment by TonyBagnall** [comment]
any way related to this? #124?

**Comment by TonyBagnall** [comment]
same here https://github.com/aeon-toolkit/aeon/actions/runs/4375356487/jobs/7656160003
