### ISSUE TITLE
[ENH] Saving models when testing deep learning estimators

### ISSUE THREAD

**Issue by TonyBagnall** [aeon-toolkit/aeon#1621]
### Describe the feature or idea you want to propose

as I understand it, deep learning estimators save a model by default, as is standard practice in the field. This means that all our testing saves models, and this causes occasional CI fails (and is unnecessary really)

### Describe your proposed solution

set default test parameters to not save a model, then introduce a specific test to test saving that uses a temp directory

**Comment by hadifawaz1999** [comment]
It wouldnt work, the whole module is constructed in a way that it will always have to use the best model after training, and its impossible to do that without saving during training with the ModelCheckpoint callback, so cant see a work arount it

**Comment by TonyBagnall** [comment]
given the answer above, closing this issue :)
