### ISSUE TITLE
[ENH] Transformers Wish-List

### ISSUE THREAD

**Issue by patrickzib** [aeon-toolkit/aeon#166]
A couple of nice to haves features for the _new transformers_:

- `y` should be accepted as input with numpy 1d-arrays. Currently, I am getting an error message (though this might just be a problem with choosing the correct tags?)

> E TypeError: y must be in an sktime compatible format, of scitype Series, Panel or Hierarchical, for instance a pandas.DataFrame with sktime compatible time indices, or with MultiIndex and last(-1) level an sktime compatible time index.

- Support for scipy `csr_matrix` as return type, which is used by dictionary models using SFA.

- No conversion (vectorization) of 2d input data (ongoing issue)

- Option to disable `fit()` and force `fit_transform()` instead? It is faster on many occasions to do both in one go, as `fit()` often involves the `transform()`, too, but this would not be accessible if called like `fit().transform()` and doubles computations.

**Comment by TonyBagnall** [comment]
In preparation, list of classifier dependencies on transformers is here. 

https://hackmd.io/TcGsAV2bRS-IWvm5D5ogCA

See also #85 #98 #146 #100

**Comment by TonyBagnall** [comment]
just scoping it a bit

**Comment by TonyBagnall** [comment]
transformers have moved on, this issue is not really relevant to the current code base, @patrickzib feel free to update or create a new issue
