### ISSUE TITLE
[ENH] SATClassifier plot_most_important_feature_on_ts

### ISSUE THREAD

**Issue by TonyBagnall** [aeon-toolkit/aeon#1684]
### Describe the feature or idea you want to propose

the SAST (scalable and accurate subsequence transform) classifier has a public function plot_most_important_feature_on_ts which has no example and is not tested. Its not clear to me what the ``feature_importance`` parameter should be (number of shapelets? number of time points) and this should be generalisable to all.

### Describe your proposed solution

1. It would be good to have an example in the function
2. It needs a test (doing this)
3. it should be generalised for all shapelet approaches and moved to visualisation

Any thoughts @frankl?

**Comment by baraline** [comment]
I'll try to cover all shapelet classifiers and transformers in #1703, so it should solved by the associated PR. feature importance is attached to the feature generated by individual shapelets, and obtained on the fitted classifier. For example feature importance on forests and weights associated to each class in linear models like ridge.
