### ISSUE TITLE
[ENH] Code improvement in `ElasticEnsemble` classifier

### ISSUE THREAD

**Issue by itsdivya1309** [aeon-toolkit/aeon#1718]
### Describe the feature or idea you want to propose

When `ddtw` or `wddtw` distance measures are used, the derivative of X is calculated and then used with `dtw` or `wdtw`. This need not be done as `ddtw` and `wddtw` themselves calculate the derivatives of the time series.
https://github.com/aeon-toolkit/aeon/blob/v0.9.0/aeon/classification/distance_based/_elastic_ensemble.py#L159

### Describe your proposed solution

The data should not be transformed into derivatives and the `ddtw` and `wddtw` distances from the distance module should be used directly like the other distances.

**Comment by TonyBagnall** [comment]
its worth a look, but irrc this is intentional to avoid doing the difference operation multiple times especially when cross validating. I will take another look though

**Comment by TonyBagnall** [comment]
we discussed this at deve meeting 11/10 and think its more efficient to stay as it is
