### ISSUE TITLE
[DOC] Add `ddtw` distance to the API references

### ISSUE THREAD

**Issue by itsdivya1309** [aeon-toolkit/aeon#1720]
### Describe the issue linked to the documentation

The API reference for the distance module does not show the Derivative Dynamic Time Warping (`ddtw`) distance measure.
https://www.aeon-toolkit.org/en/latest/api_reference/distances.html

### Suggest a potential alternative/fix

Simply update [docs/api_reference/distances.rst](docs/api_reference/distances.rst) and add `ddtw`.

**Comment by Cyril-Meyer** [comment]
@aeon-actions-bot assign @Cyril-Meyer
