### ISSUE TITLE
[ENH] Remove update function from BaseCollectionTransformer

### ISSUE THREAD

**Issue by TonyBagnall** [aeon-toolkit/aeon#1732]
### Describe the feature or idea you want to propose

I dont see the point of this function, I dont think it is implemented any where. 

### Describe your proposed solution

I think just remove it

**Comment by MatthewMiddlehurst** [comment]
I agree, can be re-added when it is needed if ever. Can roll it into v1.0.0 or deprecate.

**Comment by TonyBagnall** [comment]
v1 is going to be huge, I will do it here, I think we will go 0.11.0 before 1.0.0
