### ISSUE TITLE
[ENH] Categorisation of MrSQM and MrSEQL algorithms

### ISSUE THREAD

**Issue by heerme** [aeon-toolkit/aeon#1738]
### Describe the issue

MrSQM and MrSEQL are  currently categorised under TSC shapelet methods. We think the categorisation  should change to dictionary_methods. We don't think of them as shapelet methods, because they are more similar to dictionary-methods of the WEASEL type, than shapelet methods in how they work, e.g. there is no distance involved in the MrSQM/MrSEQL algorithms as in shapelet methods.

Both algos can be easily installed with pip:
pip install mrseql
pip install mrsqm

MrSQM can also be used as a transformer to extract features, see here:
https://github.com/mlgig/mrsqm/blob/main/example/Time_Series_Classification_and_Explanation_with_MrSQM.ipynb

**Comment by TonyBagnall** [comment]
sure, can do that, we will deprecate the current ones and replace with new ones in dictionary_based
