### ISSUE TITLE
[ENH] Describe base class attributes in doc strings?

### ISSUE THREAD

**Issue by TonyBagnall** [aeon-toolkit/aeon#175]
some of the classifiers describe the BaseClassifier attributes in their docs strings, e.g. TemporalDictionaryEnsemble has these attributes

    n_classes_ : int
        The number of classes.
    classes_ : list
        The classes labels.

I personally dont think they should, since they are in the base class docstring. Any opinions?

**Comment by MatthewMiddlehurst** [comment]
BaseClassifier attributes are TemporalDictionaryEnsemble attributes. There is no inheritance with docs, so to display these attributes in the TDE docs they have to be included.

Don't think we should expect everyone to read the BaseClassifier docs prior to individual algorithms.

**Comment by TonyBagnall** [comment]
Fair enough, I'll adopt this policy, previously didn't do so
