### ISSUE TITLE
[MNT] Tensorflow still not fully supported on python 3.12, CI breaking

### ISSUE THREAD

**Issue by hadifawaz1999** [aeon-toolkit/aeon#1760]
### Describe the issue

CI will keep breaking even after getting new MAC setup as tensorflow is still not supported on python 3,12 and is giving many issues in the community

check tensorflow's issue here: https://github.com/tensorflow/tensorflow/issues/62003

### Suggest a potential alternative/fix

We should wait a while to see how tensorflow will resolve this issue before removing the limit on tensorflow/python version in CI

**Comment by TonyBagnall** [comment]
further on this, shall we raise the bound on tensor flow to >2.13, since you said it was very hard to get everything to work well with it?

https://github.com/aeon-toolkit/aeon/issues/1477

**Comment by hadifawaz1999** [comment]
> further on this, shall we raise the bound on tensor flow to >2.13, since you said it was very hard to get everything to work well with it?
> 
> #1477

i would put it >=2.14
yes

**Comment by hadifawaz1999** [comment]
This is closed as completed in #2256
