### ISSUE TITLE
[BUG] random test failure of test_write_panel_to_tsfile_equal_length[nested_univ-BasicMotions] 

### ISSUE THREAD

**Issue by aiwalter** [aeon-toolkit/aeon#181]
see https://github.com/aeon-toolkit/aeon/actions/runs/4379728150/jobs/7666116794

**Comment by MatthewMiddlehurst** [comment]
It doesn't look like this has appeared since, but I will take a look at the test for anything off looking.

**Comment by TonyBagnall** [comment]
I'm closing this @aiwalter if thats ok, since test_write_panel_to_tsfile_equal_length no longer exists. Tests are now in  datasets/tests/test_data_writers, the equivalent test is test_write_dataframe_to_ts and it has never failed.
