### ISSUE TITLE
[DOC] Typo present in getting start guide: Redundant use of 'n_timepoints'

### ISSUE THREAD

**Issue by IRKnyazev** [aeon-toolkit/aeon#1841]
### Describe the issue linked to the documentation

Under the section Understanding time series data: 

We commonly refer to the number of observations for a time series as n_timepoints or n_timepoints. If a series is multivariate, we refer to the dimensions as channels (to avoid confusion with the dimensions of array) and in code use n_channels. Dimensions may also be referred to as variables.

This paragraph provides the same term twice as alternatives for describing the number of observations.

**Edit: found a small typo further down: Collections of time series may also be referred to a Panels. Collections of time series will often be accompanied by an array of target variables.

### Suggest a potential alternative/fix

Either remove the second option of 'n_timepoints' or provide a correct alternative term.

**Edit: second typo should be corrected to ' Collections of time series may also be referred to as Panels....'

**Comment by TonyBagnall** [comment]
@IRKnyazev assume #1842 should have closed this, typo on the PR number

**Comment by IRKnyazev** [comment]
> @IRKnyazev assume #1842 should have closed this, typo on the PR number

@TonyBagnall Oops yes sorry 😬
