### ISSUE TITLE
[BUG] Possible circular import in forecasting

### ISSUE THREAD

**Issue by lmmentel** [aeon-toolkit/aeon#188]
**Describe the bug**

Currently in [`aeon/forecasting/base/__init__.py`](https://github.com/aeon-toolkit/aeon/blob/main/sktime/forecasting/base/__init__.py) the order of imports is:

```python
from sktime.forecasting.base._fh import ForecastingHorizon
from sktime.forecasting.base._base import BaseForecaster
```

however after running `isort` it will be reversed and create a circular import error in testing.

**To Reproduce**

Revert the imports order to 

```python
from sktime.forecasting.base._base import BaseForecaster
from sktime.forecasting.base._fh import ForecastingHorizon
```

and run the test suite, or call `test_all_estimators`.

**Expected behavior**

Ideally the code would be refactored to not be dependent on the import order.

**Additional context**

**Comment by TonyBagnall** [comment]
Nice to see we are all working together:), does this help? https://github.com/sktime/sktime/pull/4329

**Comment by lmmentel** [comment]
> Nice to see we are all working together:), does this help? [sktime/sktime#4329](https://github.com/sktime/sktime/pull/4329)

Thanks for sharing, that should make it easier to resolve :wink:
