### ISSUE TITLE
[DOC] Update paper referenced in Arsenal docs

### ISSUE THREAD

**Issue by TonyBagnall** [aeon-toolkit/aeon#1885]
### Describe the issue linked to the documentation

https://www.aeon-toolkit.org/en/stable/api_reference/auto_generated/aeon.classification.convolution_based.Arsenal.html#aeon.classification.convolution_based.Arsenal

references the arxiv paper rather than the open access paper in machine learning

https://link.springer.com/article/10.1007/s10994-021-06057-9

just a note to self and an excuse to remind everyone we have a classifier called Arsenal :)

**Comment by Cyril-Meyer** [comment]
@aeon-actions-bot assign @Cyril-Meyer

**Comment by MatthewMiddlehurst** [comment]
Yay, glad that works now 🙂. Be careful with formatting on the API webpages, references can be a bit peculiar.
