### ISSUE TITLE
[ENH,MNT] Adding Init saving for deep clustering module

### ISSUE THREAD

**Issue by hadifawaz1999** [aeon-toolkit/aeon#1903]
### Describe the feature or idea you want to propose

Following the updates in #1826 , would be nice to have the same functionality and testing in the deep clustering module.

### Describe your proposed solution

- Adding `save_init_model` flag parameter to each deep clustering module, default to False
- Adding `init_file_name` default to "init_model"
- Follow same procedure to save init model such as in #1826 
- Adding a save/load testing function in deep clustering module such as in #1826

**Comment by neuron283** [comment]
Hi! I'd like to work on this.

**Comment by neuron283** [comment]
Aeon-Assign bot assign @neuron283

**Comment by neuron283** [comment]
@hadifawaz1999 Where should I add the testing function for deep clustering?
Under ```tests``` subdirectory there are 2 files: ```test_deep_clusterer_base.py``` and ```test_random_state_deep_learning_cluster.py```

**Comment by neuron283** [comment]
Also, the tests for classification and regression mentioned in #1826 are missing from latest version of aeon. It's a little confusing. Can you please elaborate?

**Comment by hadifawaz1999** [comment]
the tests were moved into a new directory recently, @MatthewMiddlehurst could you give us an idea to where the new tests should go  after the revamp we got in ?

**Comment by MatthewMiddlehurst** [comment]
If you want the test to run for each individual estimator, see the relevant yield file in `testing/estimator_checking/`. You will want to add a check there (or look at the functions there currently if just viewing).

Currently, clustering is being ported here #1877.

**Comment by neuron283** [comment]
should I wait before clustering gets ported or just carry on and create a PR?

**Comment by hadifawaz1999** [comment]
> should I wait before clustering gets ported or just carry on and create a PR?

probably will be simpler i think yes

**Comment by hadifawaz1999** [comment]
closing as completed in #2359
