### ISSUE TITLE
[BUG] Matplotlib upper bound

### ISSUE THREAD

**Issue by hadifawaz1999** [aeon-toolkit/aeon#1913]
### Describe the bug

Matplotlib presented some issues with latest releases `3.9.1` and `3.9.2`, see [here](https://github.com/matplotlib/matplotlib/issues/28551)
For now #1906 fixed it by adding an upper bound, we should wait till they sort out this issue and then remove upper bound

### Expected results

CI does not break

### Actual results

CI is breaking

**Comment by QuLogic** [comment]
3.9.1 was yanked, so you can remove the pin already. There is no 3.9.2 yet, but it will be out soon.

**Comment by hadifawaz1999** [comment]
we still have the bound in pyproject.toml so still not fixed @TonyBagnall , @MatthewMiddlehurst any update on this ?
