### ISSUE TITLE
[DOC] Confusing placement for shell error solution

### ISSUE THREAD

**Issue by phershbe** [aeon-toolkit/aeon#1914]
### Describe the issue linked to the documentation

https://github.com/aeon-toolkit/aeon/blob/main/docs/developer_guide/dev_installation.md

Step 2
```
To build and install aeon from source, navigate to the local clone's root directory and type:
pip install --editable .[dev]
```
...is at the top

And then an explanation for a problem with it...

```
If this results in a "no matches found" error, it may be due to how your shell handles special characters. Try surrounding the dependency portion with quotes:
pip install --editable ."[dev]"
```
...is at the bottom after the explanations of the `.`, `--editable`, and `all_extras`

I didn't make it to the bottom initially, and had the problem and searched for it and it seems to be a really common problem, and then noticed it here later, so it could be more inviting to new contributors to change the order.

### Suggest a potential alternative/fix

Change the order to...

```
To build and install aeon from source, navigate to the local clone's root directory and type:
pip install --editable .[dev]
```
...and then...

```
If this results in a "no matches found" error, it may be due to how your shell handles special characters. Try surrounding the dependency portion with quotes:
pip install --editable ."[dev]"
```
...and then mention the explanations of `.`, `--editable`, and `all_extras`

The start of the solution is in bold already = **If this results in a "no matches found" error** = so having it immediately after the problem that it is trying to correct should help to make things clearer

**Comment by baraline** [comment]
One alternative is to consider it as a formal definition, where introducing the terms used after the definition can be a bit confusing !

Would having the definition/explanation of  `.` and `--editable` before 
```
To build and install aeon from source, navigate to the local clone's root directory and type:
pip install --editable .[dev]
```
And then immediately followed by the possible error cause as you suggested be a good solution ? I think it would balance both point of views on this issue (parameter first vs expected error first).

**Comment by phershbe** [comment]
That would make sense to me for introducing a function for example, but here I think that the most important thing is to make sure that the user can get the project built from source and move on to contributing. 

I do have a counter proposal that includes the idea of what you mentioned...

```
To build and install aeon from source, navigate to the local clone's root directory and type:
pip install --editable .[dev]

Alternatively, the . may be replaced with a full or relative path to the root directory.

If this results in a "no matches found" error, it may be due to how your shell handles special characters. Try surrounding the dependency portion with quotes:
pip install --editable ."[dev]"
```
...because also in that case I guess that the `.` does apply to the situation above and not below, although my programming is not so advanced yet so you can tell me if I am wrong.

The code section above though is how I should have explained it in the beginning instead of the explanation being so long. It seems like the part explaining the error should be closer to the actual error, as shown above, and not at the bottom of the section.

I could make a draft pull request if you wanted and you could see how it looks in practice, because it is a lot clearer in my opinion.

**Comment by baraline** [comment]
Sure thing, the whole issue makes sense to me and the change would be welcome. I'll take a look at the PR once it's ready. Thanks again !

**Comment by phershbe** [comment]
The pull request is in. I ended up doing what I proposed initially because I played with it and it seemed clearest to have the solution directly after the issue that it is trying to solve. Feel free to change it if you need to obviously.

On another quick note and a different topic, on your previous post it would be "Thanks again!" with no space before the exclamation mark. It seems that you are French, it is a common mistake with French speakers in English. 🙂

**Comment by MatthewMiddlehurst** [comment]
Agreed it should be higher up, but another improvement would be putting it in a notation like we have done for the regular installation instructions (https://aeon-toolkit--1915.org.readthedocs.build/en/1915/installation.html). Will leave this open for now.

**Comment by MatthewMiddlehurst** [comment]
While looking I also noticed the first notation in the install instructions has a typo, should be "While we try to keep output similar between OS and Python version, we cannot guarantee the estimators will output the same results for macOS ARM processors.".

Little extra for if anyone wants to do the above 🙂.

**Comment by phershbe** [comment]
Okay those are both done and another pull request has been made! I noticed a few small mistakes that I had made after making the pull request this time, they are changed and noted in the commits, everything should be okay now though.
