### ISSUE TITLE
[DOC] Outdated Classification Notebook

### ISSUE THREAD

**Issue by Moonzyyy** [aeon-toolkit/aeon#1919]
### Describe the issue linked to the documentation

I was reading the classification notebook to learn more about classifiers, there were some confusing parts so I reached out on the slack for some help. It seems though as the classification notebook guides are completely outdated.

Notebook in discussion: https://www.aeon-toolkit.org/en/stable/examples/classification/classification.html

### Suggest a potential alternative/fix

I was told that:  "Old BaseTransformers are soon to be removed. We now have BaseCollectionTransformers, which assume shape (n_cases, n_channels, n_timepoints) and BaseSeriesTransformers that default to (n_channels, n_timepoints) but can be set with an axis parameter to take (n_timepoints,n_channels)."

It is worth going through the notebook and re-write some sections of it (not fully rewriting the whole notebook.)

**Comment by TonyBagnall** [comment]
the notebook has been rewritten for V1.0.0
