### ISSUE TITLE
[ENH] Smoothing filters as BaseSeriesTransformers

### ISSUE THREAD

**Issue by TonyBagnall** [aeon-toolkit/aeon#1920]
### Describe the feature or idea you want to propose

A while back (five years?) we compared different smoothing algorithms for time series classification. 

https://link.springer.com/chapter/10.1007/978-3-030-29859-3_5

Now, we found it did not make much difference on the UCR data, but that does not mean it is not of use. It would be good to implement some or all of these as BaseSeriesTransformers, most are pretty simple.

### Describe your proposed solution

we looked at the following, but there are probably many more. These are all parameterised, so it would be good to have an automatic way of 

- [x]  Simple Moving Average (good first issue)
- [x] Exponential smoothing (good first issue)
- [x] Gaussian filter (good first issue)
- [x] Savitzky-Golay filter
- [x] Discrete Fourier Approximation #1967 @Cyril-Meyer 
- [x] Recursive Median Sieve

### Describe alternatives you've considered, if relevant

list any others below

**Comment by Cyril-Meyer** [comment]
Aeon-Assign bot assign @Cyril-Meyer

I will continue to work on this when #1967 (DFT) is merged (the next filters will be based on this implementation, so I prefer to have it validated before). I will focus on Savitzky-Golay and Recursive Median Sieve to let some good first issue for new members.
Eventually, I will finish what has not been done after some weeks.

**Comment by Datadote** [comment]
I've implemented "Simple Moving Average" in PR #1927 . It is waiting for a review

Now, I'm starting on "Exponential Smoothing", and will add a draft PR.

**Comment by TonyBagnall** [comment]
all done, nice one @Cyril-Meyer and @Datadote
