### ISSUE TITLE
[BUG] Proximity Forest Accuracy tests fail CI 

### ISSUE THREAD

**Issue by aadya940** [aeon-toolkit/aeon#1936]
### Describe the bug

The proximity forest test `accuracy >= 0.9` fails randomly sometimes.

A possible fix would be to set a tolerance as follow:
`accuracy + 0.1 >= 0.9` ?

### Expected results

Shouldn't fail.

### Actual results

Tests don't pass.

**Comment by CodeLionX** [comment]
Thanks for the report, can you link to a failed CI run?

**Comment by aadya940** [comment]
@CodeLionX  #1923

**Comment by aadya940** [comment]
And some others as well I'm actively working on
