### ISSUE TITLE
[MNT] Add metrics parameter for deep clustering module

### ISSUE THREAD

**Issue by hadifawaz1999** [aeon-toolkit/aeon#1945]
### Describe the issue

The deep clustering module is missing the metrics parameter, in AEResNEet it exists but unused

### Suggest a potential alternative/fix

it should be default to None, and then set to ["mse"] if its None internally, the same way its done in deep clustering but here its mse instead of accuracy

### Additional context

Its for verbose purpose, doesnt affect anything else

**Comment by neuron283** [comment]
Hi. I'd like to work on this.
Could you please elaborate more on the issue?

**Comment by neuron283** [comment]
Aeon-Assign bot assign @neuron283

**Comment by hadifawaz1999** [comment]
> Hi. I'd like to work on this. Could you please elaborate more on the issue?

Thank you for taking care of this. If you look into the classification/deep_learning module, you would see a `metrics` parameter that is then set to `accuracy` by default if the user does not choose any. In the regression/deep_learning its the same thing but the default will be `mse`, in the case of clustering/deep_learning, it would be good to have the same functionality as well, and given the models are Auto Encoder based, we can have the metric by default to `mse` such as in regression
