### ISSUE TITLE
[ENH] Adapt ChannelSelector for regression

### ISSUE THREAD

**Issue by TonyBagnall** [aeon-toolkit/aeon#1951]
### Describe the feature or idea you want to propose

the ChannelSelector class evaluates each channel independently and picks the best. It could easily be adapted for regression.

### Describe your proposed solution

adapt the class so it can take a Regressor or Classifier, then use MSE or equivalent to score

**Comment by aryanpola** [comment]
Hello, I'm new to contributing to aeon, could you point me to resources that would help me to understand the issue.

**Comment by aryanpola** [comment]
Aeon-Assign bot assign @aryanpola

**Comment by MatthewMiddlehurst** [comment]
Bit late but I would look at the contributor guide. If you still need help, what part are you confused about?

**Comment by TonyBagnall** [comment]
fixed in #1993 I think
