### ISSUE TITLE
[ENH] Add test that the estimator "algorithm_type" is valid

### ISSUE THREAD

**Issue by TonyBagnall** [aeon-toolkit/aeon#1952]
### Describe the feature or idea you want to propose

for collection estimators we use the 
    _tags = {"algorithm_type": "distance"}
as a taxonomy of algorithms. However we dont test they are valid, as identified in #1935 

### Describe your proposed solution

add a test the type is one of a valid list, probably defined in the base class?

**Comment by aryanpola** [comment]
@TonyBagnall @MatthewMiddlehurst Just creating a list of distances (like dtw, euclidean etc) in the base class and checking them to be valid in subclasses would solve the issue?

**Comment by MatthewMiddlehurst** [comment]
It would be a test checking that the value of `algorithm_type` is valid i.e. `distance`, `interval`, `shapelet` etc.

**Comment by aryanpola** [comment]
aeon-assign bot assign @aryanpola

**Comment by MatthewMiddlehurst** [comment]
I wouldn't raise an error for now

**Comment by MatthewMiddlehurst** [comment]
Above is outdated, all estimators should have the tag now.
