### ISSUE TITLE
[MNT] Replace assertions in networks module with raising Value errors

### ISSUE THREAD

**Issue by hadifawaz1999** [aeon-toolkit/aeon#1956]
### Describe the issue

In all networks module, the parameters handled as input lists have an assertion for the length of the list, but assertions are not a good idea, they should be replaced by raise ValueError message

### Suggest a potential alternative/fix

Example

instead of:
```Python
assert len(self.strides) == self.n_conv_per_residual_block
```
It should be :

```Python
if len(self.strides) != self.n_conv_per_residual_block:
    raise ValueError(
        f"Number of strides {len(self.strides)} should be"
        f" the same as number of convolution layers per block but is"
        f" not: {self.n_conv_per_residual_block}."
    )
```

**Comment by hadifawaz1999** [comment]
reserved issue

**Comment by hadifawaz1999** [comment]
Aeon-Assign bot assign @JjmWeber

**Comment by MatthewMiddlehurst** [comment]
@aeon-actions-bot assign @JjmWeber

**Comment by MatthewMiddlehurst** [comment]
@aeon-actions-bot assign @hadifawaz1999

**Comment by MatthewMiddlehurst** [comment]
Ok looks like it wont let you add unrelated people to issues. Probably been abused in the past 🙂

**Comment by hadifawaz1999** [comment]
yeah still requires a comment to be able to assign

**Comment by JjmWeber** [comment]
So here is my comment 😉
