### ISSUE TITLE
[DOC] Anomaly detection getting started notebook

### ISSUE THREAD

**Issue by SebastianSchmidl** [aeon-toolkit/aeon#1960]
### Describe the issue linked to the documentation

Aeon is still missing the anomaly detection getting started notebook (linked from the home page): https://www.aeon-toolkit.org/en/stable/examples/anomaly_detection/anomaly_detection.html

PR #1932 introduced some general documentation in the API documentation that needs to be moved to this notebook as well.

**Comment by perceptronq** [comment]
Hi! I'd like to work on this.

**Comment by CodeLionX** [comment]
You are welcome to do so. If you require any further assistance, please let us know here or in Slack.

**Comment by CodeLionX** [comment]
I already created an example notebook for one of our tutorials. It can be used as a starting point: https://github.com/aeon-toolkit/aeon-tutorials/blob/main/ECML-2024/Notebooks/part6_anomaly_detection.ipynb
