### ISSUE TITLE
[GSoC '24] Tracker Issue

### ISSUE THREAD

**Issue by aadya940** [aeon-toolkit/aeon#1962]
### Describe the issue

Just organizing too many PRs :))

### Suggest a potential alternative/fix

- [x] AEBiGRUNetwork
- [x] AEAttentionBiGRUNetwork
- [x] AEDCNNNetwork
- [x] DCNNNetwork
- [x] AEDRNNNetwork 
- [x] AEBiGRUClusterer
- [x] AEAttentionBiGRUClusterer
- [x] AEDCNNClusterer
- [x] DCNNClusterer
- [x] AEDRNNClusterer
- [x] Multi-Rec Loss FCN Network
- [x] Multi-Rec Loss Residual Network

**Comment by aadya940** [comment]
@hadifawaz1999 Anything left to do here?

**Comment by hadifawaz1999** [comment]
> @hadifawaz1999 Anything left to do here?

i think not i just need to find time to review the PRs but i think its all good for now !

**Comment by hadifawaz1999** [comment]
closing this as completed
