### ISSUE TITLE
[MNT] New distance compatibility tests timeout with numba disabled

### ISSUE THREAD

**Issue by MatthewMiddlehurst** [aeon-toolkit/aeon#1991]
### Describe the issue

See https://github.com/aeon-toolkit/aeon/actions/runs/10445759452/job/28922165687.

These tests take too long with numba disabled. We have an extended timeout duration for these tests, but it still reaches it.

### Suggest a potential alternative/fix

Increase the efficiency of these tests and/or split them up. If not possible, disable them if numba is disabled.

**Comment by TonyBagnall** [comment]
=========================== short test summary info ============================
FAILED aeon/distances/tests/test_sklearn_compatibility.py::test_multivariate[task0-3-dist14] - Failed: Timeout >1800.0s
FAILED aeon/regression/distance_based/tests/test_time_series_neighbors.py::test_knn_neighbors[twe] - Failed: Timeout >1800.0s

Additional context

**Comment by MatthewMiddlehurst** [comment]
@TonyBagnall was this fixed?

**Comment by TonyBagnall** [comment]
this is I believe fixed, reopenm a new issue if not
