### ISSUE TITLE
[ENH] Make similarity search support both channel dependent and independent distance computations

### ISSUE THREAD

**Issue by baraline** [aeon-toolkit/aeon#1992]
### Describe the feature or idea you want to propose

Currently, the distance computations made in similarity search compute the distances independently for each channel and sum them together. 

### Describe your proposed solution

Expose an argument to choose between channel-dependent and independent computations

### Describe alternatives you've considered, if relevant

Just make the whole module channel dependent, as the independent case is extremely rare / a preprocessing issue

**Comment by Sharathchenna** [comment]
Aeon-Assign bot assign @Sharathchenna

**Comment by baraline** [comment]
Hey, if you need any help or have any question don't hesitate to ask !
