### ISSUE TITLE
[GOV] New governance for aeon

### ISSUE THREAD

**Issue by TonyBagnall** [aeon-toolkit/aeon#2]
hi, what do you think we should do with sktime governance? Personally I would like to scrap it all and start again, but htat might be too disruptive?

The current governance roles are:
- Core developer
- Community council (CC)
- Code of conduct committee (CoCC)
- Algorithm maintainer (in codeowners file)

**Comment by MatthewMiddlehurst** [comment]
IMO we should retain the CC, CoCC and Core Developer roles from the previous governance with a less powerful CC. I have drafted a slimmer governance document in the style of Scikit-learn to this effect.

None of this is set in stone and I can just close the above if we want to go in a different direction.

**Comment by ltsaprounis** [comment]
Just putting it out there, but I think going for a **BDFL** might be a good option, you can't have many captains in a boat. Of course I'm out of any consideration because I'm the first who said it 🤣

**Comment by MatthewMiddlehurst** [comment]
I think BDFL has its benefits, but I think the package has too much of a split focus for a candidate to be selected without someone taking issue, personally. That discussion can wait to be had only if everyone decides a BDFL is necessary, however 🙂. I think it will add too much of a role hierarchy for most though.

**Comment by TonyBagnall** [comment]
I'm not sure we really need the BDFL role(s), at least not atm. The schism was not about code. My preference would be to move forward with a lightweight governance along the lines of scikit learn, remove hierarchy, and see where it takes us.

**Comment by MatthewMiddlehurst** [comment]
Resolved by #195. The document has also moved to the front of the documentation rather than behind get_involved.
