### ISSUE TITLE
[DOC] ShapeletClassifierVisualizer doesn't support STC default estimator

### ISSUE THREAD

**Issue by IRKnyazev** [aeon-toolkit/aeon#2007]
### Describe the bug

Currently unable to visualise STC using the default rotational forest estimator.

### Steps/Code to reproduce the bug

rst_rf = ShapeletTransformClassifier(
    max_shapelets=10,
    random_state=99,  # Same random state as for the individual transform from above
).fit(X_gun_train, y_gun_train)
rst_rf_vis = ShapeletClassifierVisualizer(rst_rf)

### Expected results

No error.

### Actual results

NotImplementedError: The classifier linked to the estimator is not supported. We expect a classifier inheriting from LinearClassifierMixin, BaseForest or BaseDecisionTree but got <class 'aeon.classification.sklearn._rotation_forest_classifier.RotationForestClassifier'>

**Comment by baraline** [comment]
Just seen this one, in short as the rotation tree use PCA, tracing back the feature importance to the shapelet would need to be made on the PCA coefs.
So technically not a bug, just hard to make it !

**Comment by IRKnyazev** [comment]
Okay cool! Do you think there should be some mention in the docstring for this?

**Comment by baraline** [comment]
Always good to document these kind of things, maybe in the notebook about shapelet where I use the tool also.
