### ISSUE TITLE
[DOC] Failed Example

### ISSUE THREAD

**Issue by twobitunicorn** [aeon-toolkit/aeon#2015]
### Describe the issue linked to the documentation

Hi.  In the "getting started" documentation [here](https://www.aeon-toolkit.org/en/stable/getting_started.html) there is an example for **Pipelines for aeon estimators**.  This example throws the following error
```
ValueError: Multivariate data not supported by BoxCoxTransformer
```
This might be an issue with either the documentation or even the transformer as it is a `pd.Series` being passed in so I am unsure why this error exists.

### Suggest a potential alternative/fix

Either fix the documentation or it might be an error with the transformer itsef.

**Comment by TonyBagnall** [comment]
Thanks, we will fix it

**Comment by TonyBagnall** [comment]
fixed now, thanks for pointing this out
