### ISSUE TITLE
[BUG] Hierarchical forecasting broken when for 2 hierarchy levels there is only 1 observation

### ISSUE THREAD

**Issue by aiwalter** [aeon-toolkit/aeon#202]
@aiwalter  fill this issue

**Describe the bug**

**To Reproduce**

```python
<Paste your code here>
```

**Expected behavior**

**Additional context**

**Versions**
<details>

</details>

**Comment by MatthewMiddlehurst** [comment]
This still needs to be filled out 🙂

**Comment by TonyBagnall** [comment]
I'm going to close this due to lack of information, feel free to populate it and reopn @aiwalter
