### ISSUE TITLE
[ENH] Rework distance/matrix profile import system

### ISSUE THREAD

**Issue by baraline** [aeon-toolkit/aeon#2021]
### Describe the issue

Currently, when selecting between distance or matrix profile options in `QuerySearch` or `SeriesSearch` a dict is used with as values the functions to use. This requires to import all of them at the start of the module, while only one will be used. 

### Suggest a potential alternative/fix

Make a function that only imports the necessary method at runtime.

**Comment by aryanpola** [comment]
@baraline Lazy loading(dynamic importing) would be the way to solve the issue?

**Comment by aryanpola** [comment]
Also, how do I classify a certain module as heavy?

**Comment by baraline** [comment]
The idea would simply to import the distance profile / matrix profile functions matching the distance and speed ups paramater given during initialisation
