### ISSUE TITLE
[DOC] Improve similarity search docstrings

### ISSUE THREAD

**Issue by baraline** [aeon-toolkit/aeon#2023]
### Describe the issue linked to the documentation

- In some dosctring, the math environment is used, which can lead to some variables like `query_length` being not displayed correctly due to the underscore
- Other docstrings, should also be reviewed as some are non-descriptive (e.g. predict function in Series Search)
- Make sure similar parameters use the same docstrings through the whole module.

### Suggest a potential alternative/fix

Replace math environments with double quote?

**Comment by aryanpola** [comment]
@baraline haven't found any docstring that raises issues like `query_length` in the math environment.
