### ISSUE TITLE
[ENH] Add algorithm_type tag to clusterers

### ISSUE THREAD

**Issue by TonyBagnall** [aeon-toolkit/aeon#2035]
### Describe the feature or idea you want to propose

for classification/regression we group algorithms by core technique, e.g."algorithm_type": "distance". Currently clusterers do not have this tag, 

### Describe your proposed solution

would be good to add it

**Comment by aryanpola** [comment]
aeon-assign bot assign @aryanpola

**Comment by aryanpola** [comment]
@aeon-actions-bot assign @aryanpola

**Comment by TonyBagnall** [comment]
fixed by #2041
