### ISSUE TITLE
[ENH] TimeSeriesKMeans init_algorithm

### ISSUE THREAD

**Issue by TonyBagnall** [aeon-toolkit/aeon#2036]
### Describe the feature or idea you want to propose

the sklearn KMeans has an argument called `init` which is a string specifying the initialisation algorithm. The aeon version has the same, which can also take an array, but it is called `init_algorithm` 

### Describe your proposed solution

probably adopt sklearn names to reduce confusion?

**Comment by Sharathchenna** [comment]
Aeon-Assign bot assign @Sharathchenna

**Comment by Sharathchenna** [comment]
@TonyBagnall, should I change init_algorithm to init? Is that correct?

**Comment by Sharathchenna** [comment]
@aeon-actions-bot assign @Sharathchenna

**Comment by TonyBagnall** [comment]
#2040 fixed
