### ISSUE TITLE
[DOC] Link for forecasting notebook is off 

### ISSUE THREAD

**Issue by nairbenrekia** [aeon-toolkit/aeon#2063]
### Describe the issue linked to the documentation

Hi,

The link at the end of this paragraph (for forecasting) is not working: 

Time Series Forecasting Regression (TSFR) relates to forecasting reduced to regression through a sliding window. This is the more familiar type to most people. The notebook for forecasting using supervised regressors can be found [here](**https://www.aeon-toolkit.org/en/stable/examples/forecasting/forecasting_sklearn.ipynb**).

Yassine NAIR BENREKIA

**Comment by danielroberts20** [comment]
@aeon-actions-bot assign @danielroberts20

**Comment by TonyBagnall** [comment]
thanks for that, the forecasting module is undergoing a big overhaul. For now, it would be good to just remove the reference to the notebook,. i.e. delete "The notebook for forecasting using supervised regressors can be found here". Happy for you to do this!
