### ISSUE TITLE
[ENH] Make all collection and series transformer files private, access through init

### ISSUE THREAD

**Issue by TonyBagnall** [aeon-toolkit/aeon#2068]
### Describe the feature or idea you want to propose

currently like this
![image](https://github.com/user-attachments/assets/71194a8f-a11f-4e98-8ee2-2ace3693eef5)
should be like series transformers 
![image](https://github.com/user-attachments/assets/51d33cbb-b4ad-40a7-869b-8f76b351a845)

### Describe your proposed solution

make files private, import through init

**Comment by notaryanramani** [comment]
Can you assign this to me?
