### ISSUE TITLE
[ENH] Tidy up ROCKET variants

### ISSUE THREAD

**Issue by TonyBagnall** [aeon-toolkit/aeon#208]
the convolution_base l Transformers need tidying up and speeding up. Current situation is this

## rocket.py: Rocket
   fit: calls _generate_kernels: randomly generates convolutions and randomly generated from randomly selected subset of channels, stores it all in self.kernels (should be self.kernels_ I think). n_jobs is set, but I cant see where its actually used

  transform: calls _apply_kernels 

## multirocket.py: MultiRocket
  fit: flattens the data, then normalises. This is wrong, should normalise first, although the flattening is pointless as its not multivariate capable. (X.shape[1] == 1), calls _get_parameter

 transform: calls another method called transform, with a long hard coded array 

## multirocket_multivariate.py: MultiRocketMultivariate w

orks directly with 3D numpy, hard coded edge case for short series, seems identical to MultiRocket otherwise. 

## minirocket_multivariate_variable: MiniRocketMultivariateVariable

seems unnecessary.

- [ ] Set up the transformers to only use numpy when equal length
- [ ] Allow for skipping of all conversion and meta data extraction 
- [ ] Merge multivariate and univariate versions
- [ ] Facilitate unequal length series transformers (merge existing multivariate version)
- [ ] Profile and see if can be optimised at all

**Comment by hadifawaz1999** [comment]
@TonyBagnall isn't there a lot of common stuff between all rocket variants ?
why not create a rocket base
for instance applying the convolution kernel can be common with a list of strs as arguments to indicate which poolings to use, which is different from variant to variant

**Comment by TonyBagnall** [comment]
lets make an AEP for convolution based estimators

**Comment by TonyBagnall** [comment]
replaced by #1699
