### ISSUE TITLE
[ENH] Split `RocketClassifier` and `RocketRegressor` into multiple classes

### ISSUE THREAD

**Issue by MatthewMiddlehurst** [aeon-toolkit/aeon#2089]
### Describe the feature or idea you want to propose

Currently, Rocket, Mini-Rocket and Multi-Rocket are condensed into a single estimator. This is not very consistent with other files we have for similar algorithms i.e. SAST/RSAST, WEASEL/WEASELV2/MUSE etc. 

### Describe your proposed solution

Split `RocketClassifier` and `RocketRegressor` into:

- [ ] `RocketClassifier` 
- [ ] `MiniRocketClassifier` 
- [ ] `MultiRocketClassifier` 
- [ ] `RocketRegressor`
- [ ] `MiniRocketRegressor`
- [ ] `MultiRocketRegressor`

### Describe alternatives you've considered, if relevant

There is an argument to be made that we should condense these similar algorithms into a single class instead, but this is simpler for now.

**Comment by TonyBagnall** [comment]
not sure about this, and what about hydra/multirocket hydra?

**Comment by TonyBagnall** [comment]
the alternative is to go the other way, encapsulate SAST/RSAST, WEASEL, HIVE-COTE etc into single configurable classifiers. One to discuss at the next classification/regression dev meeting

**Comment by MatthewMiddlehurst** [comment]
Hydra and MRH are already separate
