### ISSUE TITLE
[ENH] Add PyODAdapter-implementation for IsolationForest

### ISSUE THREAD

**Issue by CodeLionX** [aeon-toolkit/aeon#2108]
### Describe the feature or idea you want to propose

The [`PyODAdapter`](https://github.com/aeon-toolkit/aeon/blob/main/aeon/anomaly_detection/_pyodadapter.py) in aeon allows us to use any outlier detector from [PyOD](https://github.com/yzhao062/pyod), which were originally proposed for relational data, also for time series anomaly detection (TSAD). Not all detectors are equally well suited for TSAD, however. We want to represent the frequently used and competitive outlier detection techniques within the `anomaly_detection` module of aeon directly.

Implement the [IsolationForest method](https://github.com/yzhao062/pyod/blob/master/pyod/models/iforest.py#L49) using the `PyODAdapter`.

### Describe your proposed solution

- Create a new file in `aeon.anomaly_detection` for the method
- Create a new estimator class with `PyODAdapter` as the parent
- Expose the algorithm's hyperparameters as constructor arguments, create the PyOD model and pass it to the super-constructor
- Document your class
- Add tests for certain edge cases if necessary

---

Example for IsolationForest:

```python
class IsolationForest(PyODAdapter):
    """documentation ..."""
    def __init__(n_estimators: int = 100, max_samples: int | str = "auto", ..., window_size: int, stride: int):
        model = IForest(n_estimators, max_samples, ...
        super().__init__(model, window_size, stride)

    @classmethod
    def get_test_params(cls, parameter_set="default"):
        """..."""
        return {"n_estimators": 10, ...}
```

**Comment by notaryanramani** [comment]
Just wanted to get a feedback on how I plan to solve this problem:

1. Create `IsolationForest` class inherited from `PyODAdapter`
2. Create instance of `IForest` from `pyod`, then call super constructor.
3. Define `fit`, `predict` and `fit_predict` methods to call `_fit`, `_predict` and `_fit_predict` from parent class respectively.
4. Override the `get_test_params` method.
5. Document everything.
6. Write test cases.

Is there anything else you would like me to be aware about?

**Comment by CodeLionX** [comment]
I am convinced that step 3 is not necessary.
The `PyODAdapter` should already contain the logic required (anyway, please never override `fit`, `predict` and `fit_predict` methods; estimators are just allowed to overwrite the `_fit`, `_predict`, and `_fit_predict` methods).

No, just give it a shot, and we'll take a look at the PR afterward 👍🏼

**Comment by notaryanramani** [comment]
Okay! Can you assign this issue to me?

**Comment by CodeLionX** [comment]
@aeon-actions-bot assign notaryanramani
