### ISSUE TITLE
[ENH] Add PyODAdapter-implementation for CBLOF

### ISSUE THREAD

**Issue by CodeLionX** [aeon-toolkit/aeon#2110]
### Describe the feature or idea you want to propose

The [`PyODAdapter`](https://github.com/aeon-toolkit/aeon/blob/main/aeon/anomaly_detection/_pyodadapter.py) in aeon allows us to use any outlier detector from [PyOD](https://github.com/yzhao062/pyod), which were originally proposed for relational data, also for time series anomaly detection (TSAD). Not all detectors are equally well suited for TSAD, however. We want to represent the frequently used and competitive outlier detection techniques within the `anomaly_detection` module of aeon directly.

**Implement the [CBLOF method](https://github.com/yzhao062/pyod/blob/master/pyod/models/cblof.py#L25)** using the `PyODAdapter`.

### Describe your proposed solution

- Create a new file in `aeon.anomaly_detection` for the method
- Create a new estimator class with `PyODAdapter` as the parent
- Expose the algorithm's hyperparameters as constructor arguments, create the PyOD model and pass it to the super-constructor
- Document your class
- Add tests for certain edge cases if necessary

---

Example for IsolationForest:

```python
class IsolationForest(PyODAdapter):
    """documentation ..."""
    def __init__(n_estimators: int = 100, max_samples: int | str = "auto", ..., window_size: int, stride: int):
        model = IForest(n_estimators, max_samples, ...
        super().__init__(model, window_size, stride)

    @classmethod
    def get_test_params(cls, parameter_set="default"):
        """..."""
        return {"n_estimators": 10, ...}
```

**Comment by notaryanramani** [comment]
Can you assign this to me?

**Comment by CodeLionX** [comment]
One at a time please. You can also ask the @aeon-actions-bot to do this for you 😉

**Comment by notaryanramani** [comment]
@aeon-actions-bot assign @notaryanramani
