### ISSUE TITLE
[ENH] Self-organising map (SOM) clusterer

### ISSUE THREAD

**Issue by chrisholder** [aeon-toolkit/aeon#2130]
### Describe the feature or idea you want to propose

SOM has been used with DTW in the literature and is easily extendable to all the elastic distances we have in aeon. A link to the first paper I could find that used it was: https://arxiv.org/abs/2004.08176.

### Describe your proposed solution

I propose with implement an "ElasticSOM" clusterer.

**Comment by TonyBagnall** [comment]
closed complete #2149
