### ISSUE TITLE
[ENH] Distance module cleanup

### ISSUE THREAD

**Issue by chrisholder** [aeon-toolkit/aeon#2161]
### Describe the issue

The distance module has now got quite a lot of distances. Having all the distances as a flat directory makes it quite hard to manage and navigate.

### Suggest a potential alternative/fix

We should split the distance module into sub directories based on the distances type. To begin I think we should have a directory for 'elastic' distances and the rest can be at the root level.

In addition while doing this I want to clean up the utility functions in _distance.py and organise the tests based on this new structure.

**Comment by TonyBagnall** [comment]
finished by #2178
