### ISSUE TITLE
[BUG] RandomIntervalClassifier and SupervisedIntervalClassifier do not set n_jobs in contained scikit learn estimator

### ISSUE THREAD

**Issue by TonyBagnall** [aeon-toolkit/aeon#2211]
### Describe the bug

found when writing tests. These classifiers set the contained estimators n_jobs as follows

```python
        self._estimator = _clone_estimator(
            (
                RandomForestClassifier(n_estimators=200)
                if self.estimator is None
                else self.estimator
            ),
            self.random_state,
        )

        m = getattr(self._estimator, "n_jobs", None)
        if m is not None:
            self._estimator.n_jobs = self._n_jobs
```
I assume the problem is with 

        m = getattr(self._estimator, "n_jobs", None)

returns None if the attribute is present (which it is) but set to the value None

![image](https://github.com/user-attachments/assets/d7cc86ef-171b-4f52-88f7-decfeb2ccbe1)

### Steps/Code to reproduce the bug

```python
import pytest
from aeon.classification.interval_based import RandomIntervalClassifier, SupervisedIntervalClassifier
from aeon.testing.data_generation import make_example_3d_numpy
from sklearn.svm import SVC

@pytest.mark.parametrize("cls",[SupervisedIntervalClassifier, RandomIntervalClassifier])
def test_random_interval_classifier(cls):
    X,y = make_example_3d_numpy(n_cases=5, n_channels=1, n_timepoints=12)
    r = cls(estimator=SVC())
    r.fit(X, y)
    p = r.predict_proba(X)
    assert p.shape == (5, 2)
    r = cls(n_jobs=2)
    r.fit(X, y)
    assert r._estimator.n_jobs == 2
```

### Expected results

test should pass

### Actual results

test_interval_pipelines.py::test_random_interval_classifier[SupervisedIntervalClassifier] FAILED [ 50%]
aeon\classification\interval_based\tests\test_interval_pipelines.py:7 (test_random_interval_classifier[SupervisedIntervalClassifier])
None != 2

Expected :2
Actual   :None

**Comment by CodeLionX** [comment]
There is `hasattr(obj, "name") -> boolean`. Might help with the solution.

**Comment by TonyBagnall** [comment]
yes solution in #2213 does this
```python
        m = hasattr(self._estimator, "n_jobs")
        if m:
            self._estimator.n_jobs = self._n_jobs
```
