### ISSUE TITLE
[BUG] Random test failure of SFA

### ISSUE THREAD

**Issue by aiwalter** [aeon-toolkit/aeon#223]
Failed test `test_sfa_anova[information-gain]` randomly here: https://github.com/aeon-toolkit/aeon/actions/runs/4489276050/jobs/7895037324?pr=221

is this related https://github.com/aeon-toolkit/aeon/pull/196 @TonyBagnall ?

**Comment by TonyBagnall** [comment]
probably, I'll look, its probably testing seems SFA is returning just inf
![image](https://user-images.githubusercontent.com/9594042/226917941-37fb7c2d-ed3a-4e24-926b-aeffb6fc5758.png)
