### ISSUE TITLE
[DOC] Replace NOTES by REFERENCES in docstrings

### ISSUE THREAD

**Issue by hadifawaz1999** [aeon-toolkit/aeon#2280]
### Describe the issue linked to the documentation

Noticed that some docstrings use NOTES instead of REFERENCES in docstrings, making the api doc not linking refs correctly

### Suggest a potential alternative/fix

just should be replaced, i noticed it in some deep learners but would be good to do a check all over aeon at some point

**Comment by MatthewMiddlehurst** [comment]
NOTES is a valid header, but if its used in place of references it should be replaced yeah

**Comment by TonyBagnall** [comment]
might require splitting into Notes and References, please post any instances here

**Comment by aryanpola** [comment]
![Screenshot 2024-10-31 214208](https://github.com/user-attachments/assets/3f092f1c-105b-4661-ad20-6d526e9332c2)
aeon.classification.deep_learning._inception_time.py

**Comment by TonyBagnall** [comment]
so I would have 
Notes
------
Adapted from ...

References
------------
..[1] Fawaz et al.

**Comment by hadifawaz1999** [comment]
> ## so I would have
> Notes
> 
> Adapted from ...
> ## References
> 
> ..[1] Fawaz et al.

Yes this and also the paper references to be in references
