### ISSUE TITLE
[DOC] Update history?

### ISSUE THREAD

**Issue by patrickzib** [aeon-toolkit/aeon#232]
the story does not really match. 

https://www.aeon-toolkit.org/en/latest/about/history.html

**Comment by MatthewMiddlehurst** [comment]
Actual content is in progress, but I want to condense the whole "about us" section including history #241

**Comment by aiwalter** [comment]
we should also add a part about the name and give credits to @logicabrity for handing over the PyPI to us and possibly to me for proposing the name :)
