### ISSUE TITLE
[BUG] Dataset InsectSound cannot be loaded

### ISSUE THREAD

**Issue by CodeLionX** [aeon-toolkit/aeon#2322]
### Describe the bug

When downloading the InsectSound dataset, the extracted files are placed in a subfolder instead of the dataset's root folder and the `*.ts`-files are missing:

![image](https://github.com/user-attachments/assets/b7d27814-7151-4060-82fa-9dd4a6001f04)

This leads to aeon not finding the train or test splits.

### Steps/Code to reproduce the bug

```python
>>> from aeon.datasets import load_classification
>>> X, y, meta = load_classification("InsectSound", extract_path="data", return_metadata=True)
```

### Expected results

No error and the dataset is successfully loaded.

### Actual results

![image](https://github.com/user-attachments/assets/8b530de9-c9e2-4505-a718-206d79bed624)

### Versions

<details>

```python
>>> from aeon import show_versions; show_versions()

System:
    python: 3.9.18 (main, Sep 11 2023, 13:41:44)  [GCC 11.2.0]
executable: /home/sebastian/.conda/envs/ts-clustering/bin/python
   machine: Linux-5.15.0-124-generic-x86_64-with-glibc2.35

Python dependencies:
          pip: 23.3.1
   setuptools: 68.2.2
 scikit-learn: 1.1.3
         aeon: 0.11.1
  statsmodels: 0.14.1
        numpy: 1.23.5
        scipy: 1.12.0
       pandas: 1.5.3
   matplotlib: 3.8.2
       joblib: 1.3.2
        numba: 0.56.4
     pmdarima: None
      tsfresh: 0.20.0
```
</details>

**Comment by TonyBagnall** [comment]
thanks, there is also no ts file for this, I cant even remember where we used this dataset! I'll sort it now

**Comment by TonyBagnall** [comment]
should work now @CodeLionX

**Comment by CodeLionX** [comment]
works 👍🏼
