### ISSUE TITLE
[BUG] Different p-values in scatter and MCM

### ISSUE THREAD

**Issue by TonyBagnall** [aeon-toolkit/aeon#2358]
### Describe the bug

both these plotting tools show a one sided p-value for wilcoxon sign rank test, but in or lates experiments these are different, possibly from calling different functions. Needs investigation

### Steps/Code to reproduce the bug

plot both with same data

### Expected results

same p vals

### Actual results

![image](https://github.com/user-attachments/assets/8b9bbf87-2198-4fe8-9c8b-0e95ee42f430)
![image](https://github.com/user-attachments/assets/f4a43bd0-5bd3-43ea-a0f0-d0480c2ee05f)

**Comment by hadifawaz1999** [comment]
can you provide the code that generates this ? is it from a notebook ?

**Comment by hadifawaz1999** [comment]
@TonyBagnall in scatter plot the wilcoxon from scipy is called as such:
![image](https://github.com/user-attachments/assets/3d38fc7e-23fa-43a2-bf25-c9fe1e6c65ca)

in MCM, the default set of wilcoxon is zero_method="pratt" and one sided for alternative

**Comment by TonyBagnall** [comment]
yeah I will try to recreate, just dumping here as writing a paper, I may just be wrong. scatter also calls the same function, will investigate further

**Comment by TonyBagnall** [comment]
ah thanks @hadifawaz1999 you have saved me a job :)

**Comment by TonyBagnall** [comment]
Definitely default to a standard, I will look into it and choose one

**Comment by TonyBagnall** [comment]
also need to use the same default in CD drawing. @hadifawaz1999 for now I will standardise with whatever is used by CD drawing. I cannot imagine that it will make any difference

**Comment by TonyBagnall** [comment]
so CD and scatter use  zero_method="wilcox", will switch mcm to that if thats ok @hadifawaz1999

**Comment by TonyBagnall** [comment]
so will set to wilcox, but maybe we should pass as argument, possibly as kwargs?

**Comment by hadifawaz1999** [comment]
> zero_method = "wilcox" is the default for scipy, so will set to wilcox, but maybe we should pass as argument, possibly as kwargs?

For the mcm i added a parameter called pvalue_test_params dictionary, set to None, and if None will set default values of  zero method to Pratt and alternative to one sided 

I don't mind whats the default behavior of it, but its good to have the same parameter for scatter plots and cd
