### ISSUE TITLE
[DOC] Use of the term "metric" in the distance functions

### ISSUE THREAD

**Issue by TonyBagnall** [aeon-toolkit/aeon#2379]
### Describe the issue linked to the documentation

The term "metric" is used in the distances module for things that are not metrics. Refactor to distances

**Comment by chrisholder** [comment]
Both measure and method were proposed. For now going with "measure". Happy to review at a later date if opinions change.

**Comment by chrisholder** [comment]
I originally tried "measure" but it didnt feel right so I changed it to method.
