### ISSUE TITLE
[ENH] Add multiple seasonality support to STLForecaster

### ISSUE THREAD

**Issue by aiwalter** [aeon-toolkit/aeon#240]
`statsmodels` is stuck with release of the `MSTL` but its already in develop and we could just copy that over or think about how else to get multiple seasonality approach implemented into `STLForecaster`.

here it is:
https://github.com/statsmodels/statsmodels/blob/6b66b2713c408483dfeb069212fa57c0ee1e078b/statsmodels/tsa/stl/mstl.py

**Comment by TonyBagnall** [comment]
KWF
