### ISSUE TITLE
[DOC] Wrong FCN paper reference 

### ISSUE THREAD

**Issue by adilsonmedronha** [aeon-toolkit/aeon#2439]
### Describe the issue linked to the documentation

The reference for the FCNClassifier implementation is stated to have been adapted from:

- [1] Zhao et al., Convolutional Neural Networks for Time Series Classification, Journal of Systems Engineering and Electronics, 28(1):2017.

However, the reference should point to the paper that originally proposed the FCN:

- [1] Z. Wang, W. Yan and T. Oates, "Time series classification from scratch with deep neural networks: A strong baseline," 2017 International Joint Conference on Neural Networks (IJCNN), Anchorage, AK, USA, 2017, pp. 1578-1585.

### Suggest a potential alternative/fix

Let "Notes" to be the observation that this FCN implementation was adapted from Fawaz et. al, but mention the orignal paper in the "References". 

```
Notes
-----
Adapted from the implementation from Fawaz et. al
https://github.com/hfawaz/dl-4-tsc/blob/master/classifiers/fcn.py

References
----------
.. [1] Z. Wang, W. Yan and T. Oates, "Time series classification from scratch with deep neural networks: A strong baseline," 2017 International Joint Conference on Neural Networks (IJCNN), Anchorage, AK, USA, 2017, pp. 1578-1585.
```

**Comment by adilsonmedronha** [comment]
@aeon-actions-bot assign @adilsonmedronha

**Comment by MatthewMiddlehurst** [comment]
Please use the PR template and link issues in the future so these are closed when the PR is merged.

**Comment by MatthewMiddlehurst** [comment]
#2440
