### ISSUE TITLE
[ENH] Breakpoints calculation in SAX

### ISSUE THREAD

**Issue by hadifawaz1999** [aeon-toolkit/aeon#257]
In [this line](https://github.com/aeon-toolkit/aeon/blob/548dd73153a6277d456b0ae1bd8fb545d74385de/aeon/transformations/panel/dictionary_based/_sax.py#L175)
it seems that the breakpoints for the SAX algorithm are hardcoded, someone correct me if am wrong. If this is the case, why dont we do it using the scipy.norm.ppf ? as it does generate the breakpoints we need for the algorithm. As follows:

`scipy.norm.ppf(np.arange(1, number_of_segments) / number_of_segments)`

**Comment by hadifawaz1999** [comment]
I think the first step to re-do SAX code is to remove the pandas stuff first, after doing that it can be taken care of.

**Comment by TonyBagnall** [comment]
@hadifawaz1999 FYI, SAX is numpy based now

**Comment by hadifawaz1999** [comment]
Great @TonyBagnall ! Will try to give it a look on automating the breakpoints with scipy.

**Comment by hadifawaz1999** [comment]
Actually PAA is numpy based, should we also remove pandas stuff from the bag of words ? This way the return will also be numpy
