### ISSUE TITLE
[ENH] Remove nested_univ input data format for forecasting

### ISSUE THREAD

**Issue by aiwalter** [aeon-toolkit/aeon#258]
nobody in the whole world is using such data in industry for forecasting, has to go!

**Comment by TonyBagnall** [comment]
remove from aeon

**Comment by TonyBagnall** [comment]
@aiwalter Ive had a look and its not actually used at all in forecasting nor in the forecasting data loaders. It is allowed in certain places. I think we want to leave it as an option for backward compatibility, but it need never been seen. Can we close this issue?

**Comment by TonyBagnall** [comment]
no nested_univ in forecasting
