### ISSUE TITLE
[ENH] Add new regression algorithms from simple classifiers

### ISSUE THREAD

**Issue by MatthewMiddlehurst** [aeon-toolkit/aeon#264]
We have some simple unsupervised transforms which are used in classification which could easily be classifiers. i.e. TSFresh, Catch22 and some of the interval classifiers.

As discussed in the 30/03 meeting, I think this would be a good addition for the first release.

**Comment by TonyBagnall** [comment]
@MatthewMiddlehurst think we can close this?
