### ISSUE TITLE
[ENH] Ideas for global forecasting

### ISSUE THREAD

**Issue by MatthewMiddlehurst** [aeon-toolkit/aeon#265]
In the previous meeting some issues were raised with the current way global forecasting works. Even if it is not included in the first release, it would be nice to include some ideas about what we want to improve for some areas.

**Comment by MatthewMiddlehurst** [comment]
@ltsaprounis I believe you linked to some previous ideas (https://github.com/sktime/sktime/issues/3224#issuecomment-1227669136)

**Comment by TonyBagnall** [comment]
KWF (can bring back later)
