### ISSUE TITLE
[BUG] Imputer does not fill when missing_values=0 (on panel data?)

### ISSUE THREAD

**Issue by aiwalter** [aeon-toolkit/aeon#266]
tbd

**Comment by TonyBagnall** [comment]
this is because of this line
        # replace missing_values with np.nan
        if self.missing_values:
            X = X.replace(to_replace=self.missing_values, value=np.nan)

python interpets 0 as False, It can  can fix this easily by

        # replace missing_values with np.nan
        if self.missing_values != None:
            X = X.replace(to_replace=self.missing_values, value=np.nan)

I'll put in a PR now. This transformer is inner type pd.DataFrame, so should be spared the nested_univ problems
