### ISSUE TITLE
[BUG] `attrs` dependency discussion

### ISSUE THREAD

**Issue by MatthewMiddlehurst** [aeon-toolkit/aeon#282]
The `attrs` dependency is no longer being installed on CI, we should add it as an actual dependency or remove its usage.
It is currently only used in 2 annotation estimators (GGS and IGTS) which I believe were developed by @lmmentel.

----

Issue for discussion of `attrs` as a dependency.

**Comment by lmmentel** [comment]
Yup, I wrote those estimators and it would be great to take attrs as a dependency for those. Happy to submit a PR with the change.

**Comment by MatthewMiddlehurst** [comment]
Not against it, but just wondering what the benefits are of keeping it. Seems like it would be incompatible with the soft dependency structure.

**Comment by MatthewMiddlehurst** [comment]
I have put up a PR replacing the dependency with the inbuilt `dataclass` functionality. I believe with the current usage there should not be much of a difference, but feel free to tell me otherwise.
