### ISSUE TITLE
[DOC] ROCKET variants examples are not consistent with the variant in question

### ISSUE THREAD

**Issue by hadifawaz1999** [aeon-toolkit/aeon#299]
For all the ROCKET variants except for _minirocket_multivariate_variable, the examples provided in the docstrings imports ROCKET always, and then the transformation used is correct, just was never imported.
![image](https://user-images.githubusercontent.com/54309336/232103154-ac1afacd-2a6a-4c4a-ba50-a00a678fa6ff.png)

**Comment by TonyBagnall** [comment]
good spot! Thats probably me cut and pasting too much :)
