### ISSUE TITLE
[ENH] Add tests for plot_series with pred_interval param

### ISSUE THREAD

**Issue by aiwalter** [aeon-toolkit/aeon#304]
param `pred_interval` is not tested for the `plot_series` function, seems not to work as intended?

**Comment by MatthewMiddlehurst** [comment]
I wouldn't mind adding a test and checking to see if it's broken, but I'm not quite sure what the expected output is. 

Do you have an example of what you want to happen?

**Comment by TonyBagnall** [comment]
I'll leave this issue open but I dont think we have enouigh information to call it a bug

**Comment by TonyBagnall** [comment]
I'm closing this as we do not let have forecasters with prediction intervals, or indeed any forecasters (see #2266). plot_series needs redesigning to take numpy arrays in any case
