### ISSUE TITLE
[ENH] Wrapper for calculating error metrics for each panel/hierarchy in forecasting

### ISSUE THREAD

**Issue by aiwalter** [aeon-toolkit/aeon#337]
### Describe the feature or idea you want to propose

I want to apply performance metrics on each panel and/or hierarchy and get a `DataFrame` back with the errors. 

### Describe your proposed solution

We need a simple wrapper class or function, e.g. `make_panel_scorer` and `PanelScorer` that gets a performance metric and a param to describe the level where to calculate the errors on. Good start would be to do it for all panel combinations.

**Comment by TonyBagnall** [comment]
no longer relevant, we dont use the term Panel any more,
