### ISSUE TITLE
[ENH] Clustering algorithm `labels_` attribute test

### ISSUE THREAD

**Issue by MatthewMiddlehurst** [aeon-toolkit/aeon#345]
### Describe the feature or idea you want to propose

Some clusterers have a `labels_` attribute when `fit` is called to store the cluster labels, but I don't believe this is enforced for all clusterers. IMO it should be.

### Describe your proposed solution

A test for all clusterers should be created that ensures that when clusterers call `fit`, they have a `labels_` attribute the same length as the input data. Some verification could also be done, comparing the contents to `predict` on the same data.

**Comment by TonyBagnall** [comment]
to do: add a function in `_yield_clustering_checks.py` and call it in _yield_clustering_checks function
