### ISSUE TITLE
[ENH] Loading data when return_X_y is false

### ISSUE THREAD

**Issue by TonyBagnall** [aeon-toolkit/aeon#383]
### Describe the feature or idea you want to propose

post #355 if return_X_y is true (default) all collections loaders return either 3D numpy for equal length X or list of 2D numpy for unequal length X, and y as a numpy array. However,  if return_X_y is False, it still loads it into a nested_univ (pd.DataFrame), This needs to be done better. The problem is that Y can contain strings or floats(e.g. BasicMotions has string class labels).

I want to do this post #355. The only place return_X_y is used is in the moribund part of the benchmarking module. 

### Describe your proposed solution

I'm assuming you cannot mix floats and strings in the same numpy array (although could it an object array? Not sure how python deals with primitives as objects, weirdly I would imagine). So then we could

1. No longer allow the combined return. Butting labels and time series 
2. Encode the strings to map them onto integers. This is what happens internally with the label encoder. However, this may have side effects. We could return the string labels as meta data
3. Leave it as nested univariate until it breaks for someone

**Comment by chrisholder** [comment]
So you could use numpy for this something like this:

`res = np.array(("TEXT", 1, 1), dtype='|S4, i4, i4')
`
See: https://stackoverflow.com/questions/24832715/numpy-array-matrix-of-mixed-types for more examples

I don't know how much numba would like this? I don't know if there really is an instance where you'd be calling a numba function with the label in the same array as the time series (most of the numba stuff in aeon I see assumes the data is without the label or has it split already) so it might not be an issue.

Other suggestions could be having a tuple returns like:

(ts_collection, labels) 

where ts_collection is 3D np.ndarray (or List[np.ndarray]) of floats that is the data and labels is 1D np.ndarray of str that .

**Comment by TonyBagnall** [comment]
so we now just return it as a tuple if return_X_y is true, and thats ok for me, alternative would be just remove the option, but no need for that
