### ISSUE TITLE
[ENH] ability to control the `fill_value` in padding transformer

### ISSUE THREAD

**Issue by hadifawaz1999** [aeon-toolkit/aeon#402]
### Describe the feature or idea you want to propose

For instance the user can choose a method for the padding, by default it should always be zero padding, but the user can either choose different values of filling per sequence (i.e. an array of fill values) or for example to padd with the average of the sequence

### Describe your proposed solution

I think these could be helpful:

- [ ] `fill_value` can be array-like
- [ ] `fill_value` can be string indicating 'avg' 'max', 'min' etc.

**Comment by MatthewMiddlehurst** [comment]
would you consider this resolved with #1373 @hadifawaz1999?

**Comment by hadifawaz1999** [comment]
Oh nice wasn't aware of the PR ! thanks for the mention, closing this now as completed
