### ISSUE TITLE
[BUG] ResNetClassifier does not copy network parameters 

### ISSUE THREAD

**Issue by TonyBagnall** [aeon-toolkit/aeon#420]
### Describe the bug

whilst removing some exclusions, I found that the ResNetClassifier fails this test

test_dl_constructor_initializes_deeply

because it does not copy the parameters in this line

        self._network = ResNetNetwork(random_state=random_state)

### Expected results

it should pass the test, simply copy the parameters in constructor

### Actual results

fails the tes

**Comment by hadifawaz1999** [comment]
Thats my bad :) will take care of it
