### ISSUE TITLE
[MNT] `test_write_to_tsfile_unequal_length` occasionally raises a `FileNotFoundError`

### ISSUE THREAD

**Issue by MatthewMiddlehurst** [aeon-toolkit/aeon#449]
### Describe the issue

This happens sporadically, see:

https://github.com/aeon-toolkit/aeon/actions/runs/5013217453/jobs/8986467056
https://github.com/aeon-toolkit/aeon/actions/runs/4990819828/jobs/8995302918?pr=318

**Comment by TonyBagnall** [comment]
huh, I'll take a look
