### ISSUE TITLE
[ENH]  Benchmarking tools for download, collation and display of bake off results

### ISSUE THREAD

**Issue by TonyBagnall** [aeon-toolkit/aeon#451]
### Describe the feature or idea you want to propose

I would like to be able to pull reference results from timeseriesclassification.com, compare against my own results, perform tests of difference, plot results and generally auto-generate a report on differences. 

### Describe your proposed solution

suite of tools in the revamped benchmarking module

**Comment by TonyBagnall** [comment]
so my wish list of things I would like to be able to draw from data drawn from tsc.com

1. box/violin plots (@patrickzib maybe?)
![image](https://github.com/aeon-toolkit/aeon/assets/9594042/bea09214-3212-423c-967f-579f5f70be29)

2. pairwise scatter plots (but with the w/d/l)
![image](https://github.com/aeon-toolkit/aeon/assets/9594042/6107ccf0-9294-47fd-8f8a-b57ea1e43bf7)

3. Funky heat maps (@hadifawaz1999)
![image](https://github.com/aeon-toolkit/aeon/assets/9594042/9bc295b4-83f0-4b46-b978-a1b6edfdfae3)

4. Time accuracy graphs (clearly problematic with hardware!)
![image](https://github.com/aeon-toolkit/aeon/assets/9594042/da4095de-cf97-499b-9e12-4e4421c59a22)

**Comment by TonyBagnall** [comment]
I was wondering whether to actually put the results in aeon in the benchmarking module. They are small, one tiny csv per classifier, and it would remove the need to go via timeseriesclassification.com

**Comment by patrickzib** [comment]
> I was wondering whether to actually put the results in aeon in the benchmarking module. They are small, one tiny csv per classifier, and it would remove the need to go via timeseriesclassification.com

Just a small comment: if you load data from the tsc.com website, via:

```python
    URL = "https://..."
    data = np.loadtxt(URL, ...)
```

It will get cached locally by numpy. Thus, all subsequent requests by the same script are can be answered via the local cache.

**Comment by hadifawaz1999** [comment]
![image](https://github.com/aeon-toolkit/aeon/assets/54309336/b74146e5-ab14-47b2-a8bb-9ffda4024a46)

**Comment by TonyBagnall** [comment]
so we now can load results and have the visualisation module, so I think we can close this and anything specific to those modules can be a separate issue
