### ISSUE TITLE
[BUG]  GMMHMM test failing on windows 3.10

### ISSUE THREAD

**Issue by chrisholder** [aeon-toolkit/aeon#458]
### Describe the bug

In the test suite im getting a error on windows 3.10 for the GMMHMM.

### Expected results

Im not really sure what this is or why it's failing in my PR.

### Actual results

__________________________ test_output_type[GMMHMM] ___________________________
[gw0] win32 -- Python 3.10.9 C:\Miniconda\envs\test\python.exe

Estimator = <class 'aeon.annotation.hmm_learn.gmm.GMMHMM'>

    @pytest.mark.parametrize("Estimator", ALL_ANNOTATORS)
    def test_output_type(Estimator):
        """Test annotator output type."""
        if not _check_estimator_deps(Estimator, severity="none"):
            return None
    
        estimator = Estimator.create_test_instance()
    
        arg = make_annotation_problem(
            n_timepoints=50, estimator_type=estimator.get_tag("distribution_type")
        )
        estimator.fit(arg)
        arg = make_annotation_problem(
            n_timepoints=10, estimator_type=estimator.get_tag("distribution_type")
        )
>       y_pred = estimator.predict(arg)

Estimator  = <class 'aeon.annotation.hmm_learn.gmm.GMMHMM'>
arg        = 2000-01-01    2.477357
2000-01-02    3.995984
2000-01-03    1.247356
2000-01-04    2.186866
2000-01-05    2.0[404](https://github.com/aeon-toolkit/aeon/actions/runs/5080555472/jobs/9127886286?pr=454#step:10:405)75
200...038
2000-01-07    1.000000
2000-01-08    2.082835
2000-01-09    2.014511
2000-01-10    2.207950
Freq: D, dtype: float64
estimator  = GMMHMM(n_components=3, random_state=7)

aeon\annotation\tests\test_all_annotators.py:34:

Full log can be seen here: https://github.com/aeon-toolkit/aeon/actions/runs/5080555472/jobs/9127886286?pr=454

**Comment by TonyBagnall** [comment]
we have not seen this again but will leave it open for reference

**Comment by TonyBagnall** [comment]
closing now in the spirit of tidiness, never seen this again.
