### ISSUE TITLE
[ENH] Function to write to Monash tsf style

### ISSUE THREAD

**Issue by TonyBagnall** [aeon-toolkit/aeon#469]
### Describe the feature or idea you want to propose

we have a function that can load forecasting data in tsf format used by https://forecastingdata.org/. It would be good to have the ability to save files into the same format

### Describe your proposed solution

function along the lines of write_to_tsfile in the datasets module, _data_loaders.py

**Comment by itsdivya1309** [comment]
Hii, I would like to contribute to this issue. We want to create a function that saves data in tsf file format right?

**Comment by baraline** [comment]
Hi @itsdivya1309 welcome to aeon ! 
You are right, the goal would be to write a function that write a tsf file. It would be implemented in the `_data_writers.py` file in the `datasets` module. 

You can take inspiration from the function that write ts files [here](https://github.com/aeon-toolkit/aeon/blob/f6843c706bb697e36790493e3a207d0f1d8a86f4/aeon/datasets/_data_writers.py#L10). 

Don't hesitate to come ask more question in our slack server or in this issue if you need to.
