### ISSUE TITLE
[BUG] ResNetClassifier fails tests

### ISSUE THREAD

**Issue by TonyBagnall** [aeon-toolkit/aeon#472]
### Describe the bug

ResNetClassifier fails all the tests due to an issue cloning the classifier

E RuntimeError: Cannot clone object ResNetClassifier(batch_size=4, n_epochs=10, optimizer=(None,)), as the constructor either does not set or modifies parameter optimizer

### Steps/Code to reproduce the bug

_config, comment out resnet, then run test_all_estimators

### Expected results

pass the tests

### Actual results

estimator = ResNetClassifier(batch_size=4, n_epochs=10, optimizer=(None,))

    def clone(estimator, *, safe=True):
        """Construct a new unfitted estimator with the same parameters.
    
        Clone does a deep copy of the model in an estimator
        without actually copying attached data. It returns a new estimator
        with the same parameters that has not been fitted on any data.
    
        Parameters
        ----------
        estimator : {list, tuple, set} of estimator instance or a single \
                estimator instance
            The estimator or group of estimators to be cloned.
        safe : bool, default=True
            If safe is False, clone will fall back to a deep copy on objects
            that are not estimators.
    
        Returns
        -------
        estimator : object
            The deep copy of the input, an estimator if input is an estimator.
    
        Notes
        -----
        If the estimator's `random_state` parameter is an integer (or if the
        estimator doesn't have a `random_state` parameter), an *exact clone* is
        returned: the clone and the original estimator will give the exact same
        results. Otherwise, *statistical clone* is returned: the clone might
        return different results from the original estimator. More details can be
        found in :ref:`randomness`.
        """
        estimator_type = type(estimator)
        # XXX: not handling dictionaries
        if estimator_type in (list, tuple, set, frozenset):
            return estimator_type([clone(e, safe=safe) for e in estimator])
        elif not hasattr(estimator, "get_params") or isinstance(estimator, type):
            if not safe:
                return copy.deepcopy(estimator)
            else:
                if isinstance(estimator, type):
                    raise TypeError(
                        "Cannot clone object. "
                        + "You should provide an instance of "
                        + "scikit-learn estimator instead of a class."
                    )
                else:
                    raise TypeError(
                        "Cannot clone object '%s' (type %s): "
                        "it does not seem to be a scikit-learn "
                        "estimator as it does not implement a "
                        "'get_params' method." % (repr(estimator), type(estimator))
                    )
    
        klass = estimator.__class__
        new_object_params = estimator.get_params(deep=False)
        for name, param in new_object_params.items():
            new_object_params[name] = clone(param, safe=False)
        new_object = klass(**new_object_params)
        params_set = new_object.get_params(deep=False)
    
        # quick sanity check of the parameters of the clone
        for name in new_object_params:
            param1 = new_object_params[name]
            param2 = params_set[name]
            if param1 is not param2:
>               raise RuntimeError(
                    "Cannot clone object %s, as the constructor "
                    "either does not set or modifies parameter %s" % (estimator, name)
                )
E               RuntimeError: Cannot clone object ResNetClassifier(batch_size=4, n_epochs=10, optimizer=(None,)), as the constructor either does not set or modifies parameter optimizer

..\..\venv\lib\site-packages\sklearn\base.py:98: RuntimeError

**Comment by hadifawaz1999** [comment]
I am not following, why are we cloning the optimizer ? and why is it failing only for ResNet ? I thought it was fixed in the latest update of deep learners #433

**Comment by TonyBagnall** [comment]
cloning happens in testing, this type of error is usually because something declared in constructor is being incorrectly set somewhere else. Related to the underscore suffix thing.
