### ISSUE TITLE
[ENH] implement Minkowski distance function

### ISSUE THREAD

**Issue by TonyBagnall** [aeon-toolkit/aeon#484]
### Describe the feature or idea you want to propose

currently we have hard coded Euclidean distance and are adding Manhattan distance. It would be good to generalis to any power, i.e. implement Minkowski distance

https://en.wikipedia.org/wiki/Minkowski_distance#:~:text=The%20Minkowski%20distance%20or%20Minkowski,the%20German%20mathematician%20Hermann%20Minkowski.

particularly in light of this paper

https://arxiv.org/pdf/2301.10350.pdf

### Describe your proposed solution

implement a number function with a power parameter and make sure it is numba efficient (i.e. not recompiled every time)

**Comment by akshatvishu** [comment]
Hey , can I take a shot at this open issue?

**Comment by MatthewMiddlehurst** [comment]
Thanks for showing interest! Feel free to have a go, there is a `distances` channel on Slack if you have any questions (or you can ask in the `contributor` channel or here).

The [Euclidean distance file](https://github.com/aeon-toolkit/aeon/blob/main/aeon/distances/_euclidean.py) may also be helpful. I imagine it will be in the same style.

**Comment by TonyBagnall** [comment]
Hi @akshatvishu that would be great, thanks. Do ask on slack if you have any questions, and I'll tag @chrisholder here too

**Comment by TonyBagnall** [comment]
thanks for the PR @akshatvishu. I'm travelling this week but will take a good look at it next week.
