### ISSUE TITLE
[FORK] Retaining documentation of previous contributors and core developers

### ISSUE THREAD

**Issue by TonyBagnall** [aeon-toolkit/aeon#5]
Do we keep the contributors? I'm not sure of the protocol

**Comment by TonyBagnall** [comment]
once we have a name, I think we should ask those listed as algorithm owners/maintainers whether they want to remain as such

**Comment by MatthewMiddlehurst** [comment]
I think this is mostly sorted. Only issue I can see is codeowners. Close this and reopen the other issue?
