### ISSUE TITLE
[ENH] Refactor all classifiers to suffix Classifier

### ISSUE THREAD

**Issue by TonyBagnall** [aeon-toolkit/aeon#502]
### Describe the issue

given we have gone for duplication for classification/regression/clustering, and that we have also decided naming is best as AlgorithmClassifier/AlgorithmRegressor/AlgorithmClusterer, I think we should do this for all algorithms before we turn deprecation back on. Any thoughts? Alternative would to do it incrementally as regressors come into the package, but that will involve a 2 month cycle at least for each onc we are deprecating, which I think we should start doing ASAP

**Comment by MatthewMiddlehurst** [comment]
I don't think we should do it for every estimator, just those which have duplicates. 

When it comes to deprecation, the old name can just be a wrapper until removal. i.e. for DrCIF, DrCIFClassifier, DrCIFRegressor, DrCIF would just wrap DrCIFClassifier until it is removed and all the actual functionality would be with the new name.

**Comment by TonyBagnall** [comment]
ok that sounds fair enough, lets do that
