### ISSUE TITLE
[BUG] Data loader not working

### ISSUE THREAD

**Issue by haskarb** [aeon-toolkit/aeon#521]
### Describe the bug

I'm using load_classification, however that doesn't seem to be working.  
![Screenshot 2023-06-28 at 14 38 53](https://github.com/aeon-toolkit/aeon/assets/20501023/c778d76d-4709-4332-b646-b51706c14dc4)

### Steps/Code to reproduce the bug

```python
from aeon.datasets import load_classification
X, y, meta = load_classification(name="ArrowHead") #DOCTEST +Skip
```

### Expected results

No error should be shown.

### Actual results

```python-traceback
ImportError: cannot import name 'load_classification' from 'aeon.datasets' (/Users/bhaskar/.pyenv/versions/3.8.10/envs/tslen38/lib/python3.8/site-packages/aeon/datasets/__init__.py)
```

### Versions

System:
    python: 3.8.10 (default, Jan  7 2023, 12:43:27)  [Clang 14.0.0 (clang-1400.0.29.202)]
executable: /Users/bhaskar/.pyenv/versions/3.8.10/envs/tslen38/bin/python3.8
   machine: macOS-13.4-x86_64-i386-64bit

Python dependencies:
          pip: 21.1.1
   setuptools: 56.0.0
      sklearn: None
         aeon: 0.3.0
  statsmodels: None
        numpy: 1.24.4
        scipy: 1.10.1
       pandas: 2.0.2
   matplotlib: None
       joblib: 1.2.0
        numba: 0.57.1
     pmdarima: None
      tsfresh: None

**Comment by TonyBagnall** [comment]
works for me, perhaps you are not up to date with main? 

from aeon.datasets import load_classification
X, y, meta = load_classification(name="ArrowHead")
X, y, meta = load_classification(name="Yoga")
X, y, meta = load_classification(name="ArrowHead", split="train")
X, y, meta = load_classification(name="ArrowHead", split="test")

**Comment by haskarb** [comment]
> I can also run the function currently, perhaps it is already fixed on main. Does this work for you?
> 
> `from aeon.datasets._data_loaders import load_classification`

No, it doesn't.

I did a quick check on [colab](https://colab.research.google.com/drive/1Ru8AgVfoEVjXR0WqlSDTgg2aKtfPAvy2?usp=sharing), does not seem to work there as well.

**Comment by MatthewMiddlehurst** [comment]
If you installed using `pip install aeon` I don't believe the function is in release v0.3.0. It should be in v0.4.0.

If you want to use it instead of the alternatives in the release you can install directly from GitHub main, I think the following should work `pip install git+https://github.com/aeon-toolkit/aeon.git@main`

I updated your colab link and it seems to run fine

**Comment by haskarb** [comment]
Awesome. It works now. I think it was about versions, maybe it was about version.
