### ISSUE TITLE
[BUG] tslearn version 0.6 introduces torch dependency 

### ISSUE THREAD

**Issue by TonyBagnall** [aeon-toolkit/aeon#543]
### Describe the feature or idea you want to propose

tslearn (used in clustering) introduced new dependencies in version 0.6, including torch, which we are not ready to include as yet. We have pinned it at <0.6, 

https://pypi.org/project/tslearn/

### Describe your proposed solution

this issue is here to just remind us of this, and to explore removing the bound when we include torch as a softdep.

**Comment by MatthewMiddlehurst** [comment]
`torch` is now a regular soft dependency I believe with the addition of Hydra and Quant.
