### ISSUE TITLE
[BUG] Skipped doctests still being run?

### ISSUE THREAD

**Issue by MatthewMiddlehurst** [aeon-toolkit/aeon#546]
### Describe the bug

This main test fails due to a doctest which is supposed to be skipped.

https://github.com/aeon-toolkit/aeon/actions/runs/5478731072/jobs/9979784969

### Steps/Code to reproduce the bug

N/A

### Expected results

Doctests with the skip comment are skipped.

### Actual results

A doctest line with a skip comment is run and fails.

### Versions

N/A

**Comment by TonyBagnall** [comment]
weird! Maybe is not quite formatted correctly, I'll take a look

**Comment by TonyBagnall** [comment]
think its meant to be 
  #DOCTEST: +Skip
not
  #DOCTEST +Skip
