### ISSUE TITLE
[DOC] Add example to InceptionTime docstring for classification and regression

### ISSUE THREAD

**Issue by TonyBagnall** [aeon-toolkit/aeon#550]
### Describe the issue linked to the documentation

there are no inception time docstring examples

### Suggest a potential alternative/fix

something like this @hadifawaz1999 ?

    Examples
    --------
    >>> from aeon.classification.deep_learning.fcn import FCNClassifier
    >>> from aeon.datasets import load_unit_test
    >>> X_train, y_train = load_unit_test(split="train", return_X_y=True)
    >>> X_test, y_test = load_unit_test(split="test", return_X_y=True)
    >>> fcn = FCNClassifier(n_epochs=20,batch_size=4)  # doctest: +SKIP
    >>> fcn.fit(X_train, y_train)  # doctest: +SKIP
    FCNClassifier(...)

**Comment by hadifawaz1999** [comment]
Yeah I remember we wanted to do it but for some reason CI wasn't skipping some lines of the example (too long for code quality) when we used the 'doctest skip' thing so we decided to let it go for the moment.

Will put up a PR it and we'll see if it still fails or not
