### ISSUE TITLE
[BUG] there is no data folder with data , but it is used in code

### ISSUE THREAD

**Issue by Sandy4321** [aeon-toolkit/aeon#590]
### Describe the bug

there is no data folder with data , but it is used in code 
https://github.com/aeon-toolkit/aeon/blob/main/examples/datasets/data_files_structures.ipynb

This can be demonstrated using the Arrow Head problem that is included in aeon under aeon/datasets/data

![image](https://github.com/aeon-toolkit/aeon/assets/11426119/5aa06060-f04c-40ed-bb85-175bad71758d)

### Steps/Code to reproduce the bug

This can be demonstrated using the Arrow Head problem that is included in aeon under aeon/datasets/data

### Expected results

data folder with data , but it is used in code

by the way do you have code for reading data from web 
if yes 
what data sets are supported 

### Actual results

This can be demonstrated using the Arrow Head problem that is included in aeon under aeon/datasets/data

**Comment by TonyBagnall** [comment]
hi, the datasets provided are all in the directory aeon/datasets/data

![image](https://github.com/aeon-toolkit/aeon/assets/9594042/346a0913-0f84-4d08-bf05-992aaca9f64b)

yes you can download directly from our website timeseriesclassification.com with something like this

```python
from aeon.datasets import load_classification
X, y, meta_data = load_classification("Yoga")
print(" Shape of X = ", X.shape)
print(" Meta data = ", meta_data)
```
lists of datsets are in aeon/datasets/tcs_data_lists.py (tser for regression, tsf for forecasting). This loads the UCR/UEA/Monash archives of data

**Comment by TonyBagnall** [comment]
hi @Sandy4321 are  you still having problems with this? If so, happy to help, but if not, could you close the issue? thanks

**Comment by Sandy4321** [comment]
according to 
Time Series (Extrinsic) Regression
https://github.com/aeon-toolkit/aeon/blob/main/examples/datasets/load_data_from_web.ipynb

I try to download by code
import pickle

from aeon.datasets import  load_regression 
from aeon.datasets.dataset_collections import list_available_tser_datasets

print(list_available_tser_datasets())
print('number of data sets ', len(   list_available_tser_datasets()  ))

for data_set_name in  list_available_tser_datasets():
    print('\nstart download', data_set_name)
    X, y,  metadata = load_regression(data_set_name)
    with open(data_set_name + '.pickle', 'wb') as handle:           
        pickle.dump([X , y,  metadata], handle)        
    print(X.shape)
    print('\n finish download', data_set_name)

q = 0
but get error for first data set AppliancesEnergy
lib\site-packages\aeon\datasets\_data_loaders.py", line 166, in <listcomp>
  data_series = [float(x) for x in data_series]

builtins.ValueError: could not convert string to float: '(2016-02-28 17'

![image](https://github.com/aeon-toolkit/aeon/assets/11426119/bb6ea0cd-f567-40ca-ad79-969de0d86c9c)

**Comment by Sandy4321** [comment]
import pickle

from aeon.datasets import  load_classification 
from aeon.datasets.tsc_data_lists import  multivariate 


data_to_download = sorted( list(multivariate )  )
print( data_to_download )
print('number of data sets ', len(  data_to_download) )
i =  0
j =  0
failed_data_sets =  []
for data_set_name in  data_to_download :
    print('\nstart download', data_set_name)
    try:
        X, y,  metadata = load_classification(data_set_name)
        
        with open(data_set_name + '.pickle', 'wb') as handle:           
            pickle.dump([X , y,  metadata], handle)        
        print(X.shape)
        i =  i + 1
        print('\n finish download'   , data_set_name,  '  good data sets count ' ,  i)
        
    except:
        failed_data_sets.append(data_set_name)
        j =  j + 1
        print('\n error to  download', data_set_name)
        q = 0
        


q = 0
print('  good data sets count ' ,  i)
print('  bad  data sets count ' ,  j)
print('failed_data_sets')
print(failed_data_sets)
q = 0
'''
failed_data_sets
['AsphaltObstaclesCoordinates', 'AsphaltPavementTypeCoordinates', 'AsphaltRegularityCoordinates', 'CharacterTrajectories', 'InsectWingbeat', 'JapaneseVowels', 'SpokenArabicDigits']


'''

**Comment by Sandy4321** [comment]
import pickle

from aeon.datasets import  load_classification 
from aeon.datasets.tsc_data_lists import  univariate #multivariate,


data_to_download = sorted( list(univariate )  )
print( data_to_download )
print('number of data sets ', len(  data_to_download) )
i =  0
j =  0
failed_data_sets =  []
for data_set_name in  data_to_download :
    print('\nstart download', data_set_name)
    try:
        X, y,  metadata = load_classification(data_set_name)
        
        with open(data_set_name + '.pickle', 'wb') as handle:           
            pickle.dump([X , y,  metadata], handle)        
        print(X.shape)
        i =  i + 1
        print('\n finish download'   , data_set_name,  '  good data sets count ' ,  i)
        
    except:
        failed_data_sets.append(data_set_name)
        j = j  + 1
        print('\n error to  download', data_set_name)
        q = 0
        


q = 0
print('  good data sets count ' ,  i)
print('  bad  data sets count ' ,  j)
print('failed_data_sets')
print(failed_data_sets)
q = 0
'''
failed_data_sets
['AllGestureWiimoteX', 'AllGestureWiimoteY', 'AllGestureWiimoteZ', 'GestureMidAirD1', 'GestureMidAirD2', 'GestureMidAirD3', 'GesturePebbleZ1', 'GesturePebbleZ2', 'MelbournePedestrian', 'PLAID', 'PickupGestureWiimoteZ', 'ShakeGestureWiimoteZ']

'''

**Comment by TonyBagnall** [comment]
Sorry, missed this those are the unequal length problems, which historically we have ignored. I'll look into this and try your code, I think they are probably just not on tsc.com so I'll put them there. thanks for this

**Comment by TonyBagnall** [comment]
took a while, but this all now works
```python
from aeon.datasets import load_regression
from aeon.datasets.dataset_collections import list_available_tser_datasets

print(list_available_tser_datasets())
print('number of data sets ', len( list_available_tser_datasets() ))

for data_set_name in list_available_tser_datasets():
    print('\nstart download', data_set_name)
    try:
        X, y, metadata = load_regression(data_set_name)
        print(X.shape)
    except:
        print('failed to download', data_set_name)
print('\n finish download', data_set_name)

from aeon.datasets import load_classification
from aeon.datasets.tsc_data_lists import multivariate, univariate

data_to_download = sorted( list(multivariate ) )
print('number of data sets ', len( data_to_download) )
for data_set_name in data_to_download :
    try:
        X, y, metadata = load_classification(data_set_name)
    except:
        print('failed to download', data_set_name)

data_to_download = sorted( list(univariate ) )
print('number of data sets ', len( data_to_download) )
for data_set_name in data_to_download :
    print('\nstart download', data_set_name)
    try:
        X, y, metadata = load_classification(data_set_name)
    except:
        print('failed to download', data_set_name)


```
I'll close this issue, please open a new one if you have further problems with the data loaders
