### ISSUE TITLE
[DOC] Add "Papers with aeon" in others section of documentation.

### ISSUE THREAD

**Issue by haskarb** [aeon-toolkit/aeon#604]
### Describe the issue linked to the documentation

It would be nice to see papers that use Aeon for their work. This would provide Aeon with credibility and visibility, and it would also help to promote the author's work. Authors can submit a pull request to include their paper (rather link pointing to the paper), along with the paper's repository, in the Aeon documentation.

**Comment by TonyBagnall** [comment]
great idea, I will set it up, unless you want to :)

**Comment by TonyBagnall** [comment]
I think an item on the left sidebar menu "papers with aeon" or "papers using aeon"? 
![image](https://github.com/aeon-toolkit/aeon/assets/9594042/e0636653-7a35-4a77-8021-ffe2559d2d12)

**Comment by TonyBagnall** [comment]
maybe under "using aeon"

**Comment by TonyBagnall** [comment]
thats fantastic, feel free to ask me or @MatthewMiddlehurst about it on slack
