### ISSUE TITLE
[DOC] API webpages

### ISSUE THREAD

**Issue by MatthewMiddlehurst** [aeon-toolkit/aeon#615]
### Describe the issue linked to the documentation

The API docs webpage needs a bit of a tidy up. There are two parts to this really:

1. How we structure the API, including the landing page (https://aeon-toolkit--598.org.readthedocs.build/en/598/api_reference.html)
2. Individual fixes to the auto-generated API pages by updating docstrings in functions and classes (i.e. #587)

**Comment by MatthewMiddlehurst** [comment]
May be related to #614, and structure may have to adjust if the current way is the source of large build times

**Comment by TonyBagnall** [comment]
think I'll close this as the link to the API doesnt work, and I think we are at a better place and need more specific requirements for improvements
