### ISSUE TITLE
[BUG] SFA transform uses bit_length in a way that crashes without numba

### ISSUE THREAD

**Issue by TonyBagnall** [aeon-toolkit/aeon#626]
### Describe the bug

when we turn off numba for all the tests, the test function
FAILED aeon/transformations/collection/dictionary_based/tests/test_sfa.py::test_typed_dict - AttributeError: 'numpy.int64' object has no attribute 'bit_length'

fails here

<img width="464" alt="image" src="https://github.com/aeon-toolkit/aeon/assets/9594042/aecb4ded-6ef8-45d8-9bf7-e1628df2723b">

any ideas @patrickzib ?

### Steps/Code to reproduce the bug

turn off numba, run the test

### Expected results

not crash

### Actual results

crash

**Comment by patrickzib** [comment]
Thank you. I will look into it next week, once back in the office.

**Comment by patrickzib** [comment]
@TonyBagnall How do I run tests with numb a turned off?

**Comment by TonyBagnall** [comment]
there is a global environment, set NUMBA_DISABLE_JIT to 1, but I confess, I didnt get it working correctly. Let me know if you get it working! @MatthewMiddlehurst is the man who knows, but he is off this week, back next

**Comment by patrickzib** [comment]
@TonyBagnall Sorry for taking so long. The reason seems to be related to `typed_dict=True`. The typed dict is a numba type. Thus, by disabling numba, we disable its functionality.

A minimal failing example

```python

def test_typed_dict_plain():
    import os
    os.environ["NUMBA_DISABLE_JIT"] = "1"

    from numba import types
    from numba.typed import Dict
    Dict.empty(
        key_type=types.UniTuple(types.int64, 2), value_type=types.uint32
    )
```

@MatthewMiddlehurst The best solution might be to force `typed_dict=False` in SFA, if NUMBA_DISABLE_JIT is set?

What do you think?

**Comment by MatthewMiddlehurst** [comment]
Sorry, been away for the most part! The example here doesn't actually crash for me on numba 0.58.0.

I extended your PR changes to TDE in #786 @patrickzib, but may be worth revisiting at some point. I think it is fine for now though.

**Comment by patrickzib** [comment]
TDE is the only class to use the old, slow SFA class. All others have been refactored to use sfa_fast, which does not use the concept of a typed dict anymore.

**Comment by TonyBagnall** [comment]
I think we can close this, we should move TDE onto the fast SFA and maybe deprecate the old one?
