### ISSUE TITLE
[DOC] typos in TSR documentation

### ISSUE THREAD

**Issue by jerronl** [aeon-toolkit/aeon#645]
### Describe the issue linked to the documentation

in this notebook https://github.com/aeon-toolkit/aeon/blob/main/examples/regression/regression.ipynb , a lot of "Regression" were mistaken as "Classification" .

### Suggest a potential alternative/fix

search and replace?

**Comment by MatthewMiddlehurst** [comment]
Oops! Thanks for letting us know. 

Should be easy to fix if anyone wants to take it on, if not I will do it some point before next release.

**Comment by TonyBagnall** [comment]
thanks, thats on me, I do that all the time! If you fancy making a PR to correct, happy to help if needed in any way
