### ISSUE TITLE
[BUG] Use `scikit-learn` and not `sklearn` in your `show_versions`

### ISSUE THREAD

**Issue by sylvaincom** [aeon-toolkit/aeon#670]
### Describe the bug

Hi,

First of all, thanks for the great work at `aeon`.

When creating an [issue](https://github.com/aeon-toolkit/aeon/issues/669) yesterday, I did, as asked:
```python
from aeon import show_versions; show_versions()
```
and was surprised to see that my version of `sklearn` is `0.0`.

Actually, the correct way would be to write `scikit-learn` and not `sklearn` at line 50 of `aeon/aeon/utils/_maint/_show_versions.py` due to the [`sklearn` package deprecation](https://twitter.com/scikit_learn/status/1597178713896284161?s=20).

### Expected results

```python-traceback
scikit-learn: 1.2.2
```

### Actual results

```python-traceback
sklearn: 0.0
```

**Comment by TonyBagnall** [comment]
thanks for spotting that, would welcome a PR to correct it
