### ISSUE TITLE
[BUG] extract_path in load_classification() requires a forward slash

### ISSUE THREAD

**Issue by BenGravell** [aeon-toolkit/aeon#676]
### Describe the bug

Datasets do not load properly when using the `extract_path` kwarg in `aeon.datasets.load_classification()` when the `extract_path` does not end with a forward slash `/` to indicate that it is a directory. 

This is a sharp edge for users, as the output of `os.path.join()` does not produce a forward slash. A basic OS-independent example of the `extract_path` is given in the [attached gist](https://gist.github.com/BenGravell/9a0a8257d4fed5f543a721a2ad6d0ee0). This would be a more useful example for the docs at https://www.aeon-toolkit.org/en/latest/api_reference/auto_generated/aeon.datasets.load_classification.html#aeon.datasets.load_classification instead of the ad-hoc `C:/Temp/` which is Windows-specific and is not even a default created directory for new installs of Windows (at least on my machine).

### Steps/Code to reproduce the bug

https://gist.github.com/BenGravell/9a0a8257d4fed5f543a721a2ad6d0ee0

### Expected results

No error thrown & dataset loaded properly as
```
X, y, meta_data = load_classification(dataset_name, extract_path=extract_path)
```
when `extract_path` does not end in a forward slash, e.g. with `extract_path=os.path.join(tempfile.gettempdir(), "aeon", "datasets")`.

### Actual results

```python-traceback
PS C:\Users\bjgra\GitHub\vibes> python .\extract_test.py
Traceback (most recent call last):
  File "C:\Users\bjgra\GitHub\vibes\extract_test.py", line 23, in <module>
    X, y, meta_data = load_classification(dataset_name, extract_path=extract_path)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bjgra\venv\vibes\Lib\site-packages\aeon\datasets\_data_loaders.py", line 1279, in load_classification
    return _load_tsc_dataset(
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\bjgra\venv\vibes\Lib\site-packages\aeon\datasets\_data_loaders.py", line 466, in _load_tsc_dataset
    return _load_saved_dataset(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bjgra\venv\vibes\Lib\site-packages\aeon\datasets\_data_loaders.py", line 301, in _load_saved_dataset
    X_train, y_train, meta_data = load_from_tsfile(abspath, return_meta_data=True)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bjgra\venv\vibes\Lib\site-packages\aeon\datasets\_data_loaders.py", line 224, in load_from_tsfile
    with open(full_file_path_and_name, "r", encoding="utf-8") as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\bjgra\\AppData\\Local\\Temp\\UWaveGestureLibrary\\UWaveGestureLibrary_TRAIN.ts'
```

### Versions

<details>
System:
    python: 3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)]
executable: C:\Users\bjgra\venv\vibes\Scripts\python.exe
   machine: Windows-10-10.0.22621-SP0

Python dependencies:
          pip: 23.2.1
   setuptools: 65.5.0
      sklearn: None
         aeon: 0.4.0
  statsmodels: None
        numpy: 1.24.4
        scipy: 1.11.1
       pandas: 1.5.3
   matplotlib: 3.7.2
       joblib: 1.3.2
        numba: 0.57.1
     pmdarima: None
      tsfresh: None
</details>

**Comment by TonyBagnall** [comment]
Thanks very much for this, would appreciate a PR, otherwise will fix next week

**Comment by TonyBagnall** [comment]
hi @BenGravell I think this PR fizxes this bug
https://github.com/aeon-toolkit/aeon/pull/679
if so, could you close this issue? If any further problems dont hesitate to let us know. Thanks, Tony

**Comment by BenGravell** [comment]
@TonyBagnall 
1. Pulled latest `main`
2. Made a new `venv`
3. Ran `pip install -e .`
4. Ran the following snippet:
```
import os
import tempfile
from aeon.datasets import load_classification


def make_dir_if_it_does_not_exist(path):
    if not os.path.exists(path):
        os.makedirs(path)
        print(f"Directory created at: {path}")


def load_data(dataset_name):
    root_tmp_dir = tempfile.gettempdir()
    make_dir_if_it_does_not_exist(root_tmp_dir)
    extract_path = os.path.join(root_tmp_dir, "aeon", "datasets")
    print(f"Downloading data to {extract_path}")
    X, y, meta_data = load_classification(dataset_name, extract_path=extract_path)
    print("Successfully downloaded data :)")
    print("Dataset metadata:")
    print(meta_data)
    return X, y, meta_data


X, y, meta_data = load_data("UWaveGestureLibrary")
```
and it worked.

Thanks!
