### ISSUE TITLE
[ENH] Averaging techniques in their own module

### ISSUE THREAD

**Issue by hadifawaz1999** [aeon-toolkit/aeon#695]
### Describe the feature or idea you want to propose

There should be a proper module for time series averaging instead of being under clustering module because its not only related to clustering

### Describe your proposed solution

a propoer averagin module in root

**Comment by TonyBagnall** [comment]
so we would need a plan for this. Would we have fit and predict? Is it really a form of CollectionTransformer? Could have supervised I'm guessing?

I think it might be good to start off thinking what applications there are for averaging and what methods we would consider.

Applications: 
   finding centroids for k-means
   nearest centroid classification
   dimensionality reduction as a pre processing transformer

I cant really think of an algorithms any other than means and barycenter averaging? Post links here

**Comment by hadifawaz1999** [comment]
Actually its very usefull in data augmentation as well, in this case you just need a module that takes your data and generates the average(s)

https://germain-forestier.info/publis/aaltd2018.pdf
https://germain-forestier.info/publis/icdm2017.pdf

It also can be used as a metric for choosing the source/target datasets for transfer learning
https://germain-forestier.info/publis/bigdata2018.pdf

**Comment by hadifawaz1999** [comment]
I think it would have fit and predict yes, fit would generate the weights if the user chooses the option of weights (first and second paper i sent above) where these weights are generated from the data
and predict would simply give back the average(s)

**Comment by TonyBagnall** [comment]
decided not to do this @hadifawaz1999

**Comment by hadifawaz1999** [comment]
It was decided to keep the module as is, though should be added to API

**Comment by TonyBagnall** [comment]
see #1537
