### ISSUE TITLE
[BUG] Intermittent test fail from shapelet transform

### ISSUE THREAD

**Issue by TonyBagnall** [aeon-toolkit/aeon#711]
### Describe the bug

the test, 
aeon/transformations/collection/tests/test_shapelet_transform.py::test_st_on_basic_motions

fails occasionally with results different from expected. Possible obscure lack of seeding, perhaps when shapelets are equal? Both of below are on ubuntu 22.04, but different python versions. If we see more, post link here

### Steps/Code to reproduce the bug

see
https://github.com/aeon-toolkit/aeon/actions/runs/6040287686/job/16391060741?pr=673
and
https://github.com/aeon-toolkit/aeon/actions/runs/6019651707/job/16329767004

### Expected results

not fail tests. 

### Actual results

fails test

**Comment by TonyBagnall** [comment]
https://github.com/aeon-toolkit/aeon/actions/runs/6058143042/job/16440031225?pr=650

**Comment by TonyBagnall** [comment]
https://github.com/aeon-toolkit/aeon/actions/runs/6119665293/job/16610201937

**Comment by MatthewMiddlehurst** [comment]
https://github.com/aeon-toolkit/aeon/actions/runs/6121348243/job/16615093102

**Comment by MatthewMiddlehurst** [comment]
https://github.com/aeon-toolkit/aeon/blob/main/aeon/transformations/collection/shapelet_based/tests/test_shapelet_transform.py#L29

The test itself. Not gone through the logs, but wonder how small the difference in results is
