### ISSUE TITLE
[MNT] Split the annotation module into different packages

### ISSUE THREAD

**Issue by hadifawaz1999** [aeon-toolkit/aeon#722]
### Describe the issue

The `annotation` module is currently a mix of different tasks including anomaly detection, segmentation, motif discovery, etc.

After a discussion on 05/09/23, attending developers thought it would be better to split this module up into different packages, i.e. `anomaly_detection`, `segmentation`.

This issue is here for further discussion on the topic, feel free to give your thoughts.

### Suggest a potential alternative/fix

Create new packages for each task, and migrate algorithms currently in `annotation` over time.

**Comment by TonyBagnall** [comment]
see #592 

I think we should split this into segmentation and anomaly detection, and we should do it before reinstating the deprecation policy. It would also be much easier to have coherent base classes

segmentation
           ClaspSegmentation: Segmentation (BaseSeriesAnnotator)
           GGS: Segmentation (no base class)
           IGTS: Segmentation (no base class)
           InformationGainSegmentation: Segmentation (SegmentationMixin)

anomaly detection:
          STRAY: robust anomaly detection in data streams with concept drift. **(BaseTransformer)**
          PyODAnnotator. "Transformer that applies outlier detector from pyOD." (BaseSeriesAnnotator)


not sure about:

HMM: "Implements a simple HMM fitted with Viterbi algorithm." (BaseSeriesAnnotator). 
EAAgglo: "is a non-parametric clustering approach for multivariate timeseries" Should then be in clustering, but this class extends BaseTransformer, which seems a bit odd. Name not exactly informative

**Comment by TonyBagnall** [comment]
Think we can close this now and open more specific issues if required
