### ISSUE TITLE
[BUG] Slack link timed out

### ISSUE THREAD

**Issue by hadifawaz1999** [aeon-toolkit/aeon#728]
### Describe the bug

The slack link in the github page is timed out, needs to be renewed with this one:

https://join.slack.com/t/aeon-toolkit/shared_invite/zt-22ogbd26d-cgcDrSof2ON2xkGHc1x9jA

### Expected results

the slack link should work

### Actual results

slack link not working

**Comment by MatthewMiddlehurst** [comment]
What do you see when you click it? The current one appears to redirect me ok.

**Comment by hadifawaz1999** [comment]
> What do you see when you click it? The current one appears to redirect me ok.

In slack when you are already in the server it redirects you, when you're not it will break if the link is broken
I used the one in the github page down, all of these are the same:
![image](https://github.com/aeon-toolkit/aeon/assets/54309336/1fe529be-afcc-42bd-9e9d-853fcda140e9)
Was trying to send it to a new person to join and didn't work so i used the one from aeon app
