### ISSUE TITLE
Interactive examples for aeon

### ISSUE THREAD

**Issue by edublancas** [aeon-toolkit/aeon#744]
Hi aeon team!

My team maintains a few [open-source](https://github.com/ploomber/jupysql) projects, and we've seen that having interactive examples greatly helps newcomers! We're maintaining a Binder cluster that provides ephemeral JupyterLab sessions ([example](https://binder.ploomber.io/v2/gh/ploomber/jupysql/master?urlpath=lab/tree/doc/quick-start.md)). It essentially spins up a JupyterLab session with pre-made examples.

We're happy to sponsor aeon with some computing power. If you're interested, please get in touch with me! (my contact info is in my [profile](https://github.com/edublancas/))

**Comment by TonyBagnall** [comment]
hi, that sounds interesting, we will take a look and get back to you

**Comment by edublancas** [comment]
Sounds great! In the meantime, I enabled aeon in our binder cluster:

https://binder.ploomber.io/v2/gh/aeon-toolkit/aeon/main?filepath=examples

This cluster is managed by my team so it doesn't have the capacity issues as the public one.

Happy to open a PR to switch the binder link on the README!

**Comment by MatthewMiddlehurst** [comment]
Hi, I have been away for a bit so did not see this. 

Would this just be as simple as swapping out the links in the `README` and `conf.py` etc. to your link? Happy to use a less congested server for our examples.

**Comment by edublancas** [comment]
Hi @MatthewMiddlehurst. Yes, the change implies swapping the links. Unfortunately, we have already onboarded a few open-source projects and have no capacity. We might open new slots soon; I’ll contact you if that happens!
