### ISSUE TITLE
[BUG] k-medoids produces empty cluster

### ISSUE THREAD

**Issue by steipatr** [aeon-toolkit/aeon#752]
### Describe the bug

I am trying to perform k-medoids clustering on a dataset containing 50 time series for two observational units. When doing some extreme value testing, I tried to cluster for 10 clusters and got 9 clusters with time series in them, and one empty cluster. Curiously, it's cluster no.7 (not no.0 or no.9, which would have maybe made some intuitive sense). There is no error message.

If I run the clustering for 9 clusters, there is no empty cluster. 

I checked the issues for something related, maybe #672 is somehow relevant?

Figure for illustration:
![empty cluster](https://github.com/aeon-toolkit/aeon/assets/29459692/5fd48f3d-03ef-4f8f-b1bc-28e646d8c1c3)

### Steps/Code to reproduce the bug

I have attached a Jupyter notebook and pickle file to reproduce the bug. Please let me know if you need the data in a different format.

[aeon empty cluster bug.zip](https://github.com/aeon-toolkit/aeon/files/12671238/aeon.empty.cluster.bug.zip)

### Expected results

I expect every cluster to include time series from the data set.

### Actual results

One cluster contains no time series.

### Versions

System:
    python: 3.11.0 (main, Oct 24 2022, 18:26:48) [MSC v.1933 64 bit (AMD64)]
executable: c:\...\python.exe
   machine: Windows-10-10.0.19045-SP0

Python dependencies:
          pip: 22.3
   setuptools: 65.5.0
      sklearn: None
         aeon: 0.3.0
  statsmodels: 0.14.0
        numpy: 1.24.3
        scipy: 1.11.1
       pandas: 2.0.3
   matplotlib: 3.7.2
       joblib: 1.3.1
        numba: 0.57.1
     pmdarima: None
      tsfresh: None

**Comment by TonyBagnall** [comment]
thanks for pointing this out, really helpful. It might be related to this 

https://github.com/aeon-toolkit/aeon/issues/672

@chrisholder did you say you found a reason for this?

**Comment by chrisholder** [comment]
Yea I found the reason for this im pushing a fix for it this weekend!
