### ISSUE TITLE
[ENH] Improved error message for MultIndex DataFrames in case level(-1) is not containing a time index

### ISSUE THREAD

**Issue by aiwalter** [aeon-toolkit/aeon#77]
**Is your feature request related to a problem? Please describe.**
for panel forecasting we use `MultiIndex` and the inner index level has to be the time index. This is an established convention within the framework and should therefore raise a more informative error message and checks on that. Users might not be aware of this convention.

**Comment by TonyBagnall** [comment]
where would this error message be raised? Via the datatypes conversions called in the base forecaster?

**Comment by TonyBagnall** [comment]
I'm closing this issue as we are moving away from multiindex, feel free to reopen if there is more information
