### ISSUE TITLE
[ENH] Operator overloading in BaseClasses

### ISSUE THREAD

**Issue by TonyBagnall** [aeon-toolkit/aeon#78]
**Is your feature request related to a problem? Please describe.**

Operator overloading (apparently called magic or dunder methods by python people) was introduced across the toolkit last year. 

https://github.com/sktime/sktime/pull/2164

I simply does see the need, for classification, clustering and regression at least. It seems like a contrivance for doing it just because you can. I can see no issues asking for it, no genuine use case and to me at least the high level logic of equating pipeline with multiplication is not at all intuitive. It is not, for example, transitive. It may be that other people like it, in which case no problem. 
  
**Describe the solution you'd like**

In the push for a simpler toolkit, I would like to strip it out and focus instead on using sklearn pipelines, which are more familiar to users.

**Describe alternatives you've considered**

if these are popular we can leave them as is, I'm just looking to simplify are reduce the bloatiness of the base classes. 

**Additional context**
I would like to do the same for clustering and regression

**Comment by TonyBagnall** [comment]
as with the delegates, having these overloaded operators causes no harm. No one has said anything here, so I think leave them for now, going to close this

**Comment by TonyBagnall** [comment]
reopening after discussion with @MatthewMiddlehurst

**Comment by MatthewMiddlehurst** [comment]
Closing after further discussion 🙂.
