### ISSUE TITLE
[BUG] test_plot_boxplot_median failing test

### ISSUE THREAD

**Issue by TonyBagnall** [aeon-toolkit/aeon#785]
### Describe the bug

test failing for test_plot_boxplot_median 

https://github.com/aeon-toolkit/aeon/actions/runs/6356146502/job/17265494483?pr=781

### Expected results

pass tests

### Actual results

FAILED aeon/benchmarking/tests/test_results_plotting.py::test_plot_boxplot_median - TypeError: Got both 'linewidth' and 'lw', which are aliases of one another
= 1 failed, 16338 passed, 362 skipped, 2 xfailed, 1 xpassed, 326 warnings in 1886.18s (0:31:26) =

**Comment by dguijo** [comment]
fixed with PR #786 done by Matthew. Thank you!
