### ISSUE TITLE
[MNT] Deprecation of old ShapeDTW classifier

### ISSUE THREAD

**Issue by hadifawaz1999** [aeon-toolkit/aeon#788]
### Describe the issue

After having ShapeDTW in the distance module (see #754 ) , the old [ShapeDTW classifier](https://github.com/aeon-toolkit/aeon/blob/main/aeon/classification/distance_based/_shape_dtw.py) can be deprecated given its KNN couple with ShapeDTW.

The implementation supposes that shapeDTW with knn is simply knn-dtw on transformed series, this is false.

### Suggest a potential alternative/fix

When deprecation policy is back we can take care of this before releasing v0.9.0

**Comment by TonyBagnall** [comment]
we should also consider whether to deprecate all the associated transformers that are used here and no where else. I have no real strong feeling either way, but we should discuss it

**Comment by TonyBagnall** [comment]
this is done
