### ISSUE TITLE
[ENH] Where to locate plotting functionality?

### ISSUE THREAD

**Issue by TonyBagnall** [aeon-toolkit/aeon#794]
### Describe the feature or idea you want to propose

during #782 I came across series plotting utils in annotation. We have other plotting functionality for both series and results in various locations. I think it could be tidied up. 

any thoughts?

### Describe your proposed solution

Possible solutions
1. Move all plotting to utils.
2. Move all to benchmarking
3. Introduce a visualisation module, where the results plotting (benchmarking) and series plotting (annotation and utils)

feel free to add more.

**Comment by ltsaprounis** [comment]
if we have a lot of plotting thingies, I'd prefer a separate plotting module. Will be nice to have all plotting things in one place.
