### ISSUE TITLE
[FORK] GitHub Billing

### ISSUE THREAD

**Issue by MatthewMiddlehurst** [aeon-toolkit/aeon#8]
The GitHub organisation is currently on GitHub Free, which has a number of limitations (including limited actions minutes). https://github.com/organizations/scikit-time/settings/billing

How did sktime deal with this issue? I assume we can leverage our academic links i.e. https://docs.github.com/en/billing/managing-billing-for-your-github-account/discounted-subscriptions-for-github-accounts

**Comment by TonyBagnall** [comment]
I'm bumping this to remind me to do it once I've completed my move

**Comment by MatthewMiddlehurst** [comment]
Done
