### ISSUE TITLE
[BUG] Inconsistency in online_shapelet_distance

### ISSUE THREAD

**Issue by TonyBagnall** [aeon-toolkit/aeon#862]
### Describe the bug

raised in the old place, this seems like a genuine bug that will alter results. Thank you @margauxgeuzaine by proxy

https://github.com/sktime/sktime/issues/5480

"There is an inconsistency in sktime/transformations/panel/_shapelet_transform_numba.py, between line 24 where "std = (sum2 - mean * mean * length) / length" and line 56 where "std = math.sqrt((sums2[n] - mean * mean * length) / length)".

Because of that, some time series are treated differently than others regarding normalization. The former are actually divided by the variance, and the latter are divided by the standard deviation. The second way of doing is supposed to be the right one."

### Expected results

add sqrt to stdv calculation, will alter reference results and will need to assess if it makes any sig difference overall *may make it better :)

### Actual results

doesnt take sqrt

**Comment by margauxgeuzaine** [comment]
It is a real problem indeed. I ended up with a mix of shapelets transforms which were actually computed quite differently from one another, therefore affecting the classification. Not sure it will improve the accuracy though cause your transforms will be less distinct afterwards… Anyways needs to be fixed.

**Comment by MatthewMiddlehurst** [comment]
welp, thats just been there forever apparently 🙂 

If we go by the [original](https://github.com/time-series-machine-learning/tsml-java/blob/master/src/main/java/tsml/transformers/shapelet_tools/distance_functions/OnlineShapeletDistance.java#L121), having the sqrt in the loop seems to be the error?

Can test both I guess.
