### ISSUE TITLE
[BUG] Custom callable distance function does not work

### ISSUE THREAD

**Issue by thibaut-germain** [aeon-toolkit/aeon#889]
### Describe the bug

I have tried to used a callable custom distance with TimeSeriesKMedoids but it does not work. It seems like the object is only looking for known distance from the DISTANCE list. 

### Steps/Code to reproduce the bug

from aeon.clustering import TimeSeriesKMedoids
from aeon.datasets import load_basic_motions

X_train, y_train = load_basic_motions(split="TRAIN")
X_test, y_test = load_basic_motions(split="TEST")
n_patterns = len(np.unique(y_train))

def mydistance(x,y): 
    return np.sum((x-y)**2)

km = TimeSeriesKMedoids(n_clusters=n_patterns, distance= mydistance, random_state=1)
km.fit(X_train)

### Expected results

The method should work

### Actual results

<matplotlib.legend.Legend at 0x7f2a9ac333d0>

Text(0, 0.5, 'distance')

[<matplotlib.lines.Line2D at 0x7f2a9af49890>]

[<matplotlib.lines.Line2D at 0x7f2b94085c10>]
[<matplotlib.lines.Line2D at 0x7f78b062d210>]

 
 
 
 
 
 
 
 

 
 
 

[<matplotlib.lines.Line2D at 0x7f2a9af8b250>]

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/home/germain/code/Forcasting/time_invariant.ipynb Cellule 27 line 2
      1 km = TimeSeriesKMedoids(n_clusters=n_patterns, distance= mydistance)
----> 2 km.fit(X_train)

File ~/mambaforge/envs/geom-ts/lib/python3.11/site-packages/aeon/clustering/base.py:78, in BaseClusterer.fit(self, X, y)
     73         raise AttributeError(
     74             "self.n_jobs must be set if capability:multithreading is True"
     75         )
     77 start = int(round(time.time() * 1000))
---> 78 self._fit(X)
     79 self.fit_time_ = int(round(time.time() * 1000)) - start
     80 self._is_fitted = True

File ~/mambaforge/envs/geom-ts/lib/python3.11/site-packages/aeon/clustering/k_medoids.py:185, in TimeSeriesKMedoids._fit(self, X, y)
    184 def _fit(self, X: np.ndarray, y=None):
--> 185     self._check_params(X)
    187     best_centers = None
    188     best_inertia = np.inf

File ~/mambaforge/envs/geom-ts/lib/python3.11/site-packages/aeon/clustering/k_medoids.py:462, in TimeSeriesKMedoids._check_params(self, X)
    457 if self.n_clusters > X.shape[0]:
    458     raise ValueError(
    459         f"n_clusters ({self.n_clusters}) cannot be larger than "
    460         f"n_instances ({X.shape[0]})"
    461     )
--> 462 self._distance_callable = get_distance_function(metric=self.distance)
    463 self._distance_cache = np.full((X.shape[0], X.shape[0]), np.inf)
    465 if self.method == "alternate":

File ~/mambaforge/envs/geom-ts/lib/python3.11/site-packages/aeon/distances/_distance.py:527, in get_distance_function(metric)
    494 def get_distance_function(metric: Union[str, DistanceFunction]) -> DistanceFunction:
    495     """Get the distance function for a given metric string or callable.
    496 
    497     Parameters
   (...)
    525     874.0
    526     """
--> 527     return _resolve_key_from_distance(metric, "distance")

File ~/mambaforge/envs/geom-ts/lib/python3.11/site-packages/aeon/distances/_distance.py:647, in _resolve_key_from_distance(metric, key)
    645 dist = DISTANCES_DICT.get(metric)
    646 if dist is None:
--> 647     raise ValueError(f"Unknown metric {metric}")
    648 dist_callable = dist.get(key)
    649 if dist_callable is None:

ValueError: Unknown metric <function mydistance at 0x7f2a9a0c51c0>

### Versions

System:
    python: 3.11.6 | packaged by conda-forge | (main, Oct  3 2023, 10:40:35) [GCC 12.3.0]
executable: [/home/germain/mambaforge/envs/geom-ts/bin/python](https://vscode-remote+ssh-002dremote-002bpomme.vscode-resource.vscode-cdn.net/home/germain/mambaforge/envs/geom-ts/bin/python)
   machine: Linux-6.1.0-9-amd64-x86_64-with-glibc2.36

Python dependencies:
          pip: 23.3.1
   setuptools: 68.2.2
      sklearn: None
         aeon: 0.4.0
  statsmodels: None
        numpy: 1.24.4
        scipy: 1.11.3
       pandas: 2.0.3
   matplotlib: 3.8.1
       joblib: 1.3.2
        numba: 0.57.1
     pmdarima: None
      tsfresh: None

**Comment by TonyBagnall** [comment]
thanks for that, I can rerecreate that, we will look into it.

**Comment by TonyBagnall** [comment]
hi @thibaut-germain, got round to fixing it finally, sorry for the delay
