### ISSUE TITLE
[ENH] Make RDST use online shapelet distance

### ISSUE THREAD

**Issue by baraline** [aeon-toolkit/aeon#894]
### Describe the feature or idea you want to propose

Similarly to the [online shapelet distance function in shapelet transform](https://github.com/aeon-toolkit/aeon/blob/e3eb134d8ba1f360561ca6ad74eb30f2d35a41c2/aeon/transformations/collection/shapelet_based/_shapelet_transform.py#L578), dilated shapelet transform could use an "online" computation of the distance vector to avoid recomputing most parts of the distances.

### Describe your proposed solution

The proposed solution may take inspiration from the sliding mean and std computation already implemented for dilated subsequences [here](https://github.com/aeon-toolkit/aeon/blob/e3eb134d8ba1f360561ca6ad74eb30f2d35a41c2/aeon/utils/numba/general.py#L397).

**Comment by TonyBagnall** [comment]
I've just been looking at this, and Im not sure
a) if the extra computation is worth the saving and
b) whether the way we are doing this currently is the most efficient.

Im doing some stuff with STC atm, so I will report back here when I get to early abandon

**Comment by baraline** [comment]
Hi Tony,

Just to be sure, online Shapelet distance is the algorithmic equivalent of rolling mean and std computation (i.e keep a rolling sum), in order to only compute the last element of a new comparison instead of the whole comparison each time right ?

I don't see a way where doing this would result in a less efficient solution (maybe I'm missing some obvious detail tho), could we maybe discuss this in the next aeon dev meeting ?

**Comment by TonyBagnall** [comment]
issue has conflated two issues, and got us a bit confused :) Closing this with agreement of module meeting on 1/11/24
