### ISSUE TITLE
[ENH] Compatibility with latest numpy and scikit-learn versions

### ISSUE THREAD

**Issue by ogencoglu** [aeon-toolkit/aeon#917]
### Describe the bug

Currently it requires `numpy<1.25.0`

### Expected results

Works with latest numpy release

### Actual results

The conflict is caused by:
    The user requested numpy==1.25.2
    aeon 0.5.0 depends on numpy<1.25.0 and >=1.21.0

The conflict is caused by:
    The user requested scikit-learn==1.3.0
    aeon 0.5.0 depends on scikit-learn<1.3.0 and >=1.0.0

**Comment by MatthewMiddlehurst** [comment]
Thanks for opening this, I am working on this currently and should be able to include the most recent versions in the next release (as well as update the bound more consistently in the future).

**Comment by MatthewMiddlehurst** [comment]
Should be fixed with #940 and #935.
