### ISSUE TITLE
[BUG] Benchmarking `plot_scatter` produces strange figures with small amounts of data

### ISSUE THREAD

**Issue by MatthewMiddlehurst** [aeon-toolkit/aeon#920]
### Describe the bug

Running the `plot_scatter` function with 3 datasets, I get this output:

![output](https://github.com/aeon-toolkit/aeon/assets/25731235/6264b895-9b78-4262-83d7-cb422d8a2be8)

### Steps/Code to reproduce the bug

I can provide the input used and a pickled version of the figure if requested, it is part of a larger evaluation framework.

### Expected results

The figure is drawn without errors

### Actual results

There are three issues which I can see:
- The text labels are in the centre instead of the corners and are overlapping with the plotted points
- The points where ROCKET wins are orange instead of green, and draws are blue instead of orange. This may be because TSF wins on 0 datasets.
- The axis labels go up to 1.02, which is impossible for accuracy. This may be less of a bug as the metric won't always be accuracy, but it may be good allow users to select bounds.

**Comment by Halzorg** [comment]
I would like to take a look at this issue and attempt to fix it. Could you please assign it to me?

**Comment by MatthewMiddlehurst** [comment]
Done, feel free to ask any questions here or on Slack.

**Comment by TonyBagnall** [comment]
hi, I think this is fixed now @MatthewMiddlehurst? I was just drawing some with 3 data and got this 
![image](https://github.com/aeon-toolkit/aeon/assets/9594042/83a286a6-0c99-4ae5-9e94-4edcc4d74077)
