### ISSUE TITLE
[BUG] `test_load_forecasting_from_repo` failing on nightly CI

### ISSUE THREAD

**Issue by MatthewMiddlehurst** [aeon-toolkit/aeon#971]
### Describe the bug

The test is currently failing on all versions and OS with `ValueError: too many values to unpack (expected 2)`.

### Steps/Code to reproduce the bug

See CI failure example here https://github.com/aeon-toolkit/aeon/actions/runs/7095058970/job/19311381594#step:7:739

### Expected results

The test passes.

### Actual results

The test fails.

**Comment by TonyBagnall** [comment]
ah I know why, will fix
